import 'package:flutter/material.dart';
import 'package:flutterapp/helpers/transform/transform.dart';
import 'package:flutterapp/routeeapp/generatednavbarwidget1/generated/GeneratedTopBarWidget1.dart';
import 'package:flutterapp/routeeapp/generatednavbarwidget1/generated/GeneratedRouteLabelWidget1.dart';

/* Group navbar
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedNavbarWidget1 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: Container(
      width: 453.0,
      height: 87.671142578125,
      child: Stack(
          fit: StackFit.expand,
          alignment: Alignment.center,
          overflow: Overflow.visible,
          children: [
            Positioned(
              left: 0.0,
              top: 0.0,
              right: 0.0,
              bottom: 0.0,
              width: null,
              height: null,
              child: LayoutBuilder(
                  builder: (BuildContext context, BoxConstraints constraints) {
                final double width = constraints.maxWidth * 0.19353453107753862;

                final double height = constraints.maxHeight * 5.167036571883676;

                return Stack(children: [
                  TransformHelper.translate(
                      x: constraints.maxWidth,
                      y: constraints.maxHeight * 2.5934836567302195e-15,
                      z: 0,
                      child: Container(
                        width: width,
                        height: height,
                        child: GeneratedTopBarWidget1(),
                      ))
                ]);
              }),
            ),
            Positioned(
              left: 111.13522338867188,
              top: 44.0,
              right: null,
              bottom: null,
              width: 234.07650756835938,
              height: 34.0,
              child: GeneratedRouteLabelWidget1(),
            )
          ]),
    ));
  }
}
