import 'package:flutter/material.dart';
import 'package:flutterapp/routeeapp/generatedsearchsresultsactivitywidget6/generated/GeneratedGenaralSuggestionsWidget.dart';
import 'package:flutterapp/routeeapp/generatedsearchsresultsactivitywidget6/generated/GeneratedPeopleWidget31.dart';
import 'package:flutterapp/routeeapp/generatedsearchsresultsactivitywidget6/generated/GeneratedStartPointButtonWidget16.dart';
import 'package:flutterapp/routeeapp/generatedsearchsresultsactivitywidget6/generated/GeneratedStartEndTimeButtonWidget7.dart';
import 'package:flutterapp/routeeapp/generatedsearchsresultsactivitywidget6/generated/GeneratedRouteSelectionsWidget22.dart';
import 'package:flutterapp/routeeapp/generatedsearchsresultsactivitywidget6/generated/GeneratedRoutesLabelWidget7.dart';
import 'package:flutterapp/routeeapp/generatedsearchsresultsactivitywidget6/generated/GeneratedStartPointButtonWidget15.dart';
import 'package:flutterapp/helpers/transform/transform.dart';
import 'package:flutterapp/routeeapp/generatedsearchsresultsactivitywidget6/generated/GeneratedEndTimeIconWidget5.dart';
import 'package:flutterapp/routeeapp/generatedsearchsresultsactivitywidget6/generated/GeneratedHomeWidget20.dart';
import 'package:flutterapp/routeeapp/generatedsearchsresultsactivitywidget6/generated/GeneratedEndPointButtonWidget7.dart';
import 'package:flutterapp/routeeapp/generatedsearchsresultsactivitywidget6/generated/GeneratedRoutesLabelWidget6.dart';
import 'package:flutterapp/routeeapp/generatedsearchsresultsactivitywidget6/generated/GeneratedEndTimeIconWidget6.dart';
import 'package:flutterapp/routeeapp/generatedsearchsresultsactivitywidget6/generated/GeneratedPeopleWidget37.dart';
import 'package:flutterapp/routeeapp/generatedsearchsresultsactivitywidget6/generated/GeneratedEndPointButtonWidget8.dart';
import 'package:flutterapp/routeeapp/generatedsearchsresultsactivitywidget6/generated/GeneratedStartTimeIconWidget9.dart';
import 'package:flutterapp/routeeapp/generatedsearchsresultsactivitywidget6/generated/GeneratedVectorWidget742.dart';
import 'package:flutterapp/routeeapp/generatedsearchsresultsactivitywidget6/generated/GeneratedBackButtonWidget56.dart';
import 'package:flutterapp/routeeapp/generatedsearchsresultsactivitywidget6/generated/GeneratedRouteSelectionsWidget25.dart';
import 'package:flutterapp/routeeapp/generatedsearchsresultsactivitywidget6/generated/GeneratedBackButtonWidget64.dart';
import 'package:flutterapp/routeeapp/generatedsearchsresultsactivitywidget6/generated/GeneratedStartTimeIconWidget10.dart';
import 'package:flutterapp/routeeapp/generatedsearchsresultsactivitywidget6/generated/GeneratedStartEndTimeButtonWidget8.dart';
import 'package:flutterapp/routeeapp/generatedsearchsresultsactivitywidget6/generated/GeneratedVectorWidget676.dart';

/* Frame Search's Results Activity
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedSearchsResultsActivityWidget6 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(child: LayoutBuilder(
        builder: (BuildContext context, BoxConstraints constraints) {
      return SingleChildScrollView(
        scrollDirection: Axis.vertical,
        child: Container(
            height: 905.0,
            child: Stack(children: [
              Container(
                  width: constraints.maxWidth,
                  child: Container(
                    width: 430.0,
                    height: 905.0,
                    child: Stack(
                        fit: StackFit.expand,
                        alignment: Alignment.center,
                        overflow: Overflow.visible,
                        children: [
                          Positioned(
                            left: -16.0,
                            top: -8.0,
                            right: null,
                            bottom: null,
                            width: 446.0,
                            height: 892.0,
                            child: GeneratedHomeWidget20(),
                          ),
                          Positioned(
                            left: 0.0,
                            top: 0.0,
                            right: 0.0,
                            bottom: 0.0,
                            width: null,
                            height: null,
                            child: LayoutBuilder(builder: (BuildContext context,
                                BoxConstraints constraints) {
                              double percentWidth = 0.06227483971174373;
                              double scaleX =
                                  (constraints.maxWidth * percentWidth) /
                                      26.778181076049805;

                              double percentHeight = 0.023815717749832745;
                              double scaleY =
                                  (constraints.maxHeight * percentHeight) /
                                      21.553224563598633;

                              return Stack(children: [
                                TransformHelper.translateAndScale(
                                    translateX: constraints.maxWidth *
                                        0.8387431299963662,
                                    translateY: constraints.maxHeight *
                                        0.3263248338225138,
                                    translateZ: 0,
                                    scaleX: scaleX,
                                    scaleY: scaleY,
                                    scaleZ: 1,
                                    child: GeneratedVectorWidget676())
                              ]);
                            }),
                          ),
                          Positioned(
                            left: 18.0,
                            top: 294.0,
                            right: null,
                            bottom: null,
                            width: 384.0,
                            height: 30.0,
                            child: GeneratedRouteSelectionsWidget22(),
                          ),
                          Positioned(
                            left: 106.0,
                            top: 31.0,
                            right: null,
                            bottom: null,
                            width: 215.0,
                            height: 34.0,
                            child: GeneratedRoutesLabelWidget6(),
                          ),
                          Positioned(
                            left: 19.0,
                            top: 38.0,
                            right: null,
                            bottom: null,
                            width: 20.0,
                            height: 20.0,
                            child: GeneratedBackButtonWidget56(),
                          ),
                          Positioned(
                            left: 18.0,
                            top: 90.0,
                            right: null,
                            bottom: null,
                            width: 382.0,
                            height: 55.0,
                            child: GeneratedStartPointButtonWidget15(),
                          ),
                          Positioned(
                            left: 18.0,
                            top: 153.0,
                            right: null,
                            bottom: null,
                            width: 382.0,
                            height: 55.0,
                            child: GeneratedEndPointButtonWidget7(),
                          ),
                          Positioned(
                            left: 18.0,
                            top: 216.0,
                            right: null,
                            bottom: null,
                            width: 382.0,
                            height: 55.0,
                            child: GeneratedStartEndTimeButtonWidget7(),
                          ),
                          Positioned(
                            left: 39.0,
                            top: 235.0,
                            right: null,
                            bottom: null,
                            width: 20.0,
                            height: 20.0,
                            child: GeneratedStartTimeIconWidget9(),
                          ),
                          Positioned(
                            left: 0.0,
                            top: 0.0,
                            right: 0.0,
                            bottom: 0.0,
                            width: null,
                            height: null,
                            child: LayoutBuilder(builder: (BuildContext context,
                                BoxConstraints constraints) {
                              final double width =
                                  constraints.maxWidth * 0.04877035451489826;

                              final double height =
                                  constraints.maxHeight * 0.022123895297392955;

                              return Stack(children: [
                                TransformHelper.translate(
                                    x: constraints.maxWidth *
                                        0.5610859715661337,
                                    y: constraints.maxHeight *
                                        0.261797758492317,
                                    z: 0,
                                    child: Container(
                                      width: width,
                                      height: height,
                                      child: GeneratedEndTimeIconWidget5(),
                                    ))
                              ]);
                            }),
                          ),
                          Positioned(
                            left: 170.0,
                            top: 625.0,
                            right: null,
                            bottom: null,
                            width: 30.0,
                            height: 32.30769348144531,
                            child: GeneratedPeopleWidget31(),
                          ),
                          Positioned(
                            left: 482.0,
                            top: -8.0,
                            right: null,
                            bottom: null,
                            width: 326.25390625,
                            height: 892.000244140625,
                            child: GeneratedGenaralSuggestionsWidget(),
                          ),
                          Positioned(
                            left: 0.0,
                            top: 0.0,
                            right: 0.0,
                            bottom: 0.0,
                            width: null,
                            height: null,
                            child: LayoutBuilder(builder: (BuildContext context,
                                BoxConstraints constraints) {
                              double percentWidth = 0.06227483971174373;
                              double scaleX =
                                  (constraints.maxWidth * percentWidth) /
                                      26.778181076049805;

                              double percentHeight = 0.023815717749832745;
                              double scaleY =
                                  (constraints.maxHeight * percentHeight) /
                                      21.553224563598633;

                              return Stack(children: [
                                TransformHelper.translateAndScale(
                                    translateX: constraints.maxWidth *
                                        2.036338628724564,
                                    translateY: constraints.maxHeight *
                                        0.3498325411127417,
                                    translateZ: 0,
                                    scaleX: scaleX,
                                    scaleY: scaleY,
                                    scaleZ: 1,
                                    child: GeneratedVectorWidget742())
                              ]);
                            }),
                          ),
                          Positioned(
                            left: 506.0,
                            top: 294.0,
                            right: null,
                            bottom: null,
                            width: 384.0,
                            height: 30.0,
                            child: GeneratedRouteSelectionsWidget25(),
                          ),
                          Positioned(
                            left: 594.0,
                            top: 31.0,
                            right: null,
                            bottom: null,
                            width: 215.0,
                            height: 34.0,
                            child: GeneratedRoutesLabelWidget7(),
                          ),
                          Positioned(
                            left: 507.0,
                            top: 38.0,
                            right: null,
                            bottom: null,
                            width: 20.0,
                            height: 20.0,
                            child: GeneratedBackButtonWidget64(),
                          ),
                          Positioned(
                            left: 506.0,
                            top: 90.0,
                            right: null,
                            bottom: null,
                            width: 382.0,
                            height: 55.0,
                            child: GeneratedStartPointButtonWidget16(),
                          ),
                          Positioned(
                            left: 506.0,
                            top: 153.0,
                            right: null,
                            bottom: null,
                            width: 382.0,
                            height: 55.0,
                            child: GeneratedEndPointButtonWidget8(),
                          ),
                          Positioned(
                            left: 506.0,
                            top: 216.0,
                            right: null,
                            bottom: null,
                            width: 382.0,
                            height: 55.0,
                            child: GeneratedStartEndTimeButtonWidget8(),
                          ),
                          Positioned(
                            left: 527.0,
                            top: 235.0,
                            right: null,
                            bottom: null,
                            width: 20.0,
                            height: 20.0,
                            child: GeneratedStartTimeIconWidget10(),
                          ),
                          Positioned(
                            left: 0.0,
                            top: 0.0,
                            right: 0.0,
                            bottom: 0.0,
                            width: null,
                            height: null,
                            child: LayoutBuilder(builder: (BuildContext context,
                                BoxConstraints constraints) {
                              final double width =
                                  constraints.maxWidth * 0.04877035451489826;

                              final double height =
                                  constraints.maxHeight * 0.022123895297392955;

                              return Stack(children: [
                                TransformHelper.translate(
                                    x: constraints.maxWidth *
                                        1.6959696924963663,
                                    y: constraints.maxHeight *
                                        0.2617977922133978,
                                    z: 0,
                                    child: Container(
                                      width: width,
                                      height: height,
                                      child: GeneratedEndTimeIconWidget6(),
                                    ))
                              ]);
                            }),
                          ),
                          Positioned(
                            left: 658.0,
                            top: 625.0,
                            right: null,
                            bottom: null,
                            width: 30.0,
                            height: 32.30769348144531,
                            child: GeneratedPeopleWidget37(),
                          )
                        ]),
                  ))
            ])),
      );
    }));
  }
}
