import 'package:flutter/material.dart';
import 'package:flutterapp/routeeapp/generatedprofileactivitywidget1/generated/GeneratedFrameWidget139.dart';
import 'package:flutterapp/routeeapp/generatedprofileactivitywidget1/generated/GeneratedNotificationsWidget6.dart';
import 'package:flutterapp/routeeapp/generatedprofileactivitywidget1/generated/GeneratedSettingsWidget2.dart';
import 'package:flutterapp/routeeapp/generatedprofileactivitywidget1/generated/GeneratedHomeWidget28.dart';
import 'package:flutterapp/routeeapp/generatedprofileactivitywidget1/generated/GeneratedHelpWidget1.dart';
import 'package:flutterapp/routeeapp/generatedprofileactivitywidget1/generated/GeneratedWalletoutlineWidget1.dart';
import 'package:flutterapp/routeeapp/generatedprofileactivitywidget1/generated/GeneratedFrameWidget140.dart';
import 'package:flutterapp/routeeapp/generatedprofileactivitywidget1/generated/GeneratedLine3Widget2.dart';
import 'package:flutterapp/routeeapp/generatedprofileactivitywidget1/generated/GeneratedNotificationsWidget7.dart';
import 'package:flutterapp/routeeapp/generatedprofileactivitywidget1/generated/GeneratedSsarrigmailcomWidget1.dart';
import 'package:flutterapp/routeeapp/generatedprofileactivitywidget1/generated/GeneratedDocumenttextoutlineWidget1.dart';
import 'package:flutterapp/routeeapp/generatedprofileactivitywidget1/generated/GeneratedChangePaymentInformationWidget1.dart';
import 'package:flutterapp/routeeapp/generatedprofileactivitywidget1/generated/Generated19920Widget1.dart';
import 'package:flutterapp/routeeapp/generatedprofileactivitywidget1/generated/GeneratedWidget17.dart';
import 'package:flutterapp/routeeapp/generatedprofileactivitywidget1/generated/GeneratedTermsofUseWidget2.dart';
import 'package:flutterapp/routeeapp/generatedprofileactivitywidget1/generated/GeneratedLine5Widget1.dart';
import 'package:flutterapp/routeeapp/generatedprofileactivitywidget1/generated/GeneratedOnlineWidget1.dart';
import 'package:flutterapp/routeeapp/generatedprofileactivitywidget1/generated/GeneratedLine4Widget1.dart';
import 'package:flutterapp/routeeapp/generatedprofileactivitywidget1/generated/GeneratedStavroulaSarriWidget1.dart';
import 'package:flutterapp/routeeapp/generatedprofileactivitywidget1/generated/GeneratedLine6Widget2.dart';

/* Frame Profile Activity
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedProfileActivityWidget1 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(child: LayoutBuilder(
        builder: (BuildContext context, BoxConstraints constraints) {
      return SingleChildScrollView(
        scrollDirection: Axis.vertical,
        child: Container(
            height: 901.3642578125,
            child: Stack(children: [
              Container(
                  width: constraints.maxWidth,
                  child: Container(
                    width: 416.7637939453125,
                    height: 901.3642578125,
                    child: Stack(
                        fit: StackFit.expand,
                        alignment: Alignment.center,
                        overflow: Overflow.visible,
                        children: [
                          Positioned(
                            left: -13.0,
                            top: 0.0,
                            right: null,
                            bottom: null,
                            width: 429.7637939453125,
                            height: 900.02490234375,
                            child: GeneratedHomeWidget28(),
                          ),
                          Positioned(
                            left: 18.0,
                            top: 244.0,
                            right: null,
                            bottom: null,
                            width: 384.0,
                            height: 27.0,
                            child: GeneratedSsarrigmailcomWidget1(),
                          ),
                          Positioned(
                            left: 18.0,
                            top: 275.0,
                            right: null,
                            bottom: null,
                            width: 384.0,
                            height: 27.0,
                            child: GeneratedOnlineWidget1(),
                          ),
                          Positioned(
                            left: 16.0,
                            top: 213.0,
                            right: null,
                            bottom: null,
                            width: 389.0,
                            height: 33.0,
                            child: GeneratedStavroulaSarriWidget1(),
                          ),
                          Positioned(
                            left: 58.00537109375,
                            top: 359.0,
                            right: null,
                            bottom: null,
                            width: 364.0,
                            height: 36.0,
                            child: GeneratedNotificationsWidget6(),
                          ),
                          Positioned(
                            left: 58.00537109375,
                            top: 403.0,
                            right: null,
                            bottom: null,
                            width: 364.0,
                            height: 36.0,
                            child: GeneratedSettingsWidget2(),
                          ),
                          Positioned(
                            left: 58.00537109375,
                            top: 443.0,
                            right: null,
                            bottom: null,
                            width: 364.0,
                            height: 36.0,
                            child: GeneratedHelpWidget1(),
                          ),
                          Positioned(
                            left: 58.00537109375,
                            top: 482.0,
                            right: null,
                            bottom: null,
                            width: 361.0,
                            height: 33.0,
                            child: GeneratedTermsofUseWidget2(),
                          ),
                          Positioned(
                            left: 18.00537109375,
                            top: 404.0,
                            right: null,
                            bottom: null,
                            width: 26.0,
                            height: 26.0,
                            child: GeneratedFrameWidget139(),
                          ),
                          Positioned(
                            left: 18.00537109375,
                            top: 446.0,
                            right: null,
                            bottom: null,
                            width: 26.0,
                            height: 26.0,
                            child: GeneratedFrameWidget140(),
                          ),
                          Positioned(
                            left: 0.0,
                            top: 395.525390625,
                            right: null,
                            bottom: null,
                            width: 416.01080322265625,
                            height: 0.5,
                            child: GeneratedLine3Widget2(),
                          ),
                          Positioned(
                            left: 0.00537109375,
                            top: 439.0,
                            right: null,
                            bottom: null,
                            width: 416.0,
                            height: 0.5,
                            child: GeneratedLine4Widget1(),
                          ),
                          Positioned(
                            left: 0.00537109375,
                            top: 480.0,
                            right: null,
                            bottom: null,
                            width: 416.01080322265625,
                            height: 0.5,
                            child: GeneratedLine5Widget1(),
                          ),
                          Positioned(
                            left: 1.0,
                            top: 44.0,
                            right: null,
                            bottom: null,
                            width: 421.0,
                            height: 37.0,
                            child: GeneratedWidget17(),
                          ),
                          Positioned(
                            left: 18.00537109375,
                            top: 364.0,
                            right: null,
                            bottom: null,
                            width: 26.0,
                            height: 26.0,
                            child: GeneratedNotificationsWidget7(),
                          ),
                          Positioned(
                            left: 57.00537109375,
                            top: 323.0,
                            right: null,
                            bottom: null,
                            width: 361.0,
                            height: 33.0,
                            child: GeneratedChangePaymentInformationWidget1(),
                          ),
                          Positioned(
                            left: -1.0,
                            top: 359.525390625,
                            right: null,
                            bottom: null,
                            width: 416.01080322265625,
                            height: 0.5,
                            child: GeneratedLine6Widget2(),
                          ),
                          Positioned(
                            left: 158.0,
                            top: 113.0,
                            right: null,
                            bottom: null,
                            width: 100.0,
                            height: 100.0,
                            child: Generated19920Widget1(),
                          ),
                          Positioned(
                            left: 20.00537109375,
                            top: 485.0,
                            right: null,
                            bottom: null,
                            width: 25.0,
                            height: 25.0,
                            child: GeneratedDocumenttextoutlineWidget1(),
                          ),
                          Positioned(
                            left: 21.0,
                            top: 330.0,
                            right: null,
                            bottom: null,
                            width: 20.0,
                            height: 20.0,
                            child: GeneratedWalletoutlineWidget1(),
                          )
                        ]),
                  ))
            ])),
      );
    }));
  }
}
