import 'package:flutter/material.dart';
import 'package:flutterapp/routeeapp/generatedpaymentprocesswidget/generated/GeneratedLine12Widget.dart';
import 'package:flutterapp/routeeapp/generatedpaymentprocesswidget/generated/GeneratedImage16Widget.dart';
import 'package:flutterapp/routeeapp/generatedpaymentprocesswidget/generated/GeneratedHomeWidget2.dart';
import 'package:flutterapp/routeeapp/generatedpaymentprocesswidget/generated/GeneratedDecember2021Widget.dart';
import 'package:flutterapp/routeeapp/generatedpaymentprocesswidget/generated/GeneratedGroup29Widget.dart';
import 'package:flutterapp/routeeapp/generatedpaymentprocesswidget/generated/GeneratedGroup27Widget.dart';
import 'package:flutterapp/routeeapp/generatedpaymentprocesswidget/generated/GeneratedWidget2.dart';
import 'package:flutterapp/routeeapp/generatedpaymentprocesswidget/generated/GeneratedGroup26Widget1.dart';
import 'package:flutterapp/routeeapp/generatedpaymentprocesswidget/generated/GeneratedGroup28Widget.dart';
import 'package:flutterapp/routeeapp/generatedpaymentprocesswidget/generated/GeneratedFrameWidget6.dart';

/* Frame Payment process
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedPaymentprocessWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(child: LayoutBuilder(
        builder: (BuildContext context, BoxConstraints constraints) {
      return SingleChildScrollView(
        scrollDirection: Axis.vertical,
        child: Container(
            height: 901.3642578125,
            child: Stack(children: [
              Container(
                  width: constraints.maxWidth,
                  child: Container(
                    width: 416.7637939453125,
                    height: 901.3642578125,
                    child: Stack(
                        fit: StackFit.expand,
                        alignment: Alignment.center,
                        overflow: Overflow.visible,
                        children: [
                          Positioned(
                            left: -11.0,
                            top: 0.0,
                            right: null,
                            bottom: null,
                            width: 427.7637939453125,
                            height: 900.02490234375,
                            child: GeneratedHomeWidget2(),
                          ),
                          Positioned(
                            left: 1.0,
                            top: 44.0,
                            right: null,
                            bottom: null,
                            width: 418.0,
                            height: 34.0,
                            child: GeneratedWidget2(),
                          ),
                          Positioned(
                            left: 22.0,
                            top: 50.0,
                            right: null,
                            bottom: null,
                            width: 20.0,
                            height: 20.0,
                            child: GeneratedFrameWidget6(),
                          ),
                          Positioned(
                            left: 209.0,
                            top: 150.0,
                            right: null,
                            bottom: null,
                            width: 150.0,
                            height: 52.0,
                            child: GeneratedDecember2021Widget(),
                          ),
                          Positioned(
                            left: 32.0,
                            top: 112.0,
                            right: null,
                            bottom: null,
                            width: 115.89351654052734,
                            height: 120.0,
                            child: GeneratedImage16Widget(),
                          ),
                          Positioned(
                            left: 33.0,
                            top: 404.0,
                            right: null,
                            bottom: null,
                            width: 359.0,
                            height: 65.0,
                            child: GeneratedGroup26Widget1(),
                          ),
                          Positioned(
                            left: 33.0,
                            top: 404.0,
                            right: null,
                            bottom: null,
                            width: 359.0,
                            height: 65.0,
                            child: GeneratedGroup27Widget(),
                          ),
                          Positioned(
                            left: 33.0,
                            top: 404.0,
                            right: null,
                            bottom: null,
                            width: 359.0,
                            height: 65.0,
                            child: GeneratedGroup28Widget(),
                          ),
                          Positioned(
                            left: 25.0,
                            top: 252.0,
                            right: null,
                            bottom: null,
                            width: 405.0,
                            height: 329.0,
                            child: GeneratedGroup29Widget(),
                          ),
                          Positioned(
                            left: 254.0,
                            top: 581.0,
                            right: null,
                            bottom: null,
                            width: 55.71355438232422,
                            height: 2.0,
                            child: GeneratedLine12Widget(),
                          )
                        ]),
                  ))
            ])),
      );
    }));
  }
}
