import 'package:flutter/material.dart';
import 'package:flutterapp/routeeapp/generatedpaymentwidget6/generated/GeneratedLine10Widget2.dart';
import 'package:flutterapp/routeeapp/generatedpaymentwidget6/generated/GeneratedLine11Widget1.dart';
import 'package:flutterapp/routeeapp/generatedpaymentwidget6/generated/GeneratedWidget19.dart';
import 'package:flutterapp/routeeapp/generatedpaymentwidget6/generated/GeneratedPleasescanyourticketintheareabelowWidget1.dart';
import 'package:flutterapp/routeeapp/generatedpaymentwidget6/generated/GeneratedLine8Widget2.dart';
import 'package:flutterapp/routeeapp/generatedpaymentwidget6/generated/GeneratedSearchButtonWidget68.dart';
import 'package:flutterapp/routeeapp/generatedpaymentwidget6/generated/GeneratedLine9Widget2.dart';
import 'package:flutterapp/routeeapp/generatedpaymentwidget6/generated/GeneratedHomeWidget33.dart';
import 'package:flutterapp/routeeapp/generatedpaymentwidget6/generated/GeneratedImage8Widget1.dart';
import 'package:flutterapp/routeeapp/generatedpaymentwidget6/generated/GeneratedFrameWidget148.dart';

/* Frame Payment
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedPaymentWidget6 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(child: LayoutBuilder(
        builder: (BuildContext context, BoxConstraints constraints) {
      return SingleChildScrollView(
        scrollDirection: Axis.vertical,
        child: Container(
            height: 901.3642578125,
            child: Stack(children: [
              Container(
                  width: constraints.maxWidth,
                  child: Container(
                    width: 416.7637939453125,
                    height: 901.3642578125,
                    child: Stack(
                        fit: StackFit.expand,
                        alignment: Alignment.center,
                        overflow: Overflow.visible,
                        children: [
                          Positioned(
                            left: 0.0,
                            top: 0.0,
                            right: null,
                            bottom: null,
                            width: 416.7637939453125,
                            height: 901.3642578125,
                            child: GeneratedHomeWidget33(),
                          ),
                          Positioned(
                            left: 1.0,
                            top: 44.0,
                            right: null,
                            bottom: null,
                            width: 418.0,
                            height: 34.0,
                            child: GeneratedWidget19(),
                          ),
                          Positioned(
                            left: 22.0,
                            top: 50.0,
                            right: null,
                            bottom: null,
                            width: 20.0,
                            height: 20.0,
                            child: GeneratedFrameWidget148(),
                          ),
                          Positioned(
                            left: 18.0,
                            top: 753.0,
                            right: null,
                            bottom: null,
                            width: 382.0,
                            height: 47.0,
                            child: GeneratedSearchButtonWidget68(),
                          ),
                          Positioned(
                            left: 18.0,
                            top: 112.0,
                            right: null,
                            bottom: null,
                            width: 400.0,
                            height: 33.0,
                            child:
                                GeneratedPleasescanyourticketintheareabelowWidget1(),
                          ),
                          Positioned(
                            left: 81.5,
                            top: 184.0,
                            right: null,
                            bottom: null,
                            width: 58.0,
                            height: 55.0,
                            child: GeneratedLine8Widget2(),
                          ),
                          Positioned(
                            left: 318.0,
                            top: 561.0,
                            right: null,
                            bottom: null,
                            width: 58.0,
                            height: 55.0,
                            child: GeneratedLine9Widget2(),
                          ),
                          Positioned(
                            left: 27.0,
                            top: 506.0,
                            right: null,
                            bottom: null,
                            width: 58.0,
                            height: 55.0,
                            child: GeneratedLine11Widget1(),
                          ),
                          Positioned(
                            left: 373.0,
                            top: 239.0,
                            right: null,
                            bottom: null,
                            width: 58.0,
                            height: 55.0,
                            child: GeneratedLine10Widget2(),
                          ),
                          Positioned(
                            left: 32.0,
                            top: 187.0,
                            right: null,
                            bottom: null,
                            width: 336.0,
                            height: 370.0,
                            child: GeneratedImage8Widget1(),
                          )
                        ]),
                  ))
            ])),
      );
    }));
  }
}
