import 'package:flutter/material.dart';

/* Text Updates
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedUpdatesWidget2 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: Align(
      alignment: Alignment.centerLeft,
      child: Text(
        '''Updates''',
        overflow: TextOverflow.visible,
        textAlign: TextAlign.left,
        style: TextStyle(
          height: 1.3333333333333333,
          fontSize: 18.0,
          fontFamily: 'Roboto',
          fontWeight: FontWeight.w400,
          color: Color.fromARGB(255, 87, 87, 89),

          /* letterSpacing: 0.0, */
        ),
      ),
    ));
  }
}
