import 'package:flutter/material.dart';
import 'package:flutterapp/routeeapp/generatedpaymentwidget1/generated/GeneratedVALIDWidget.dart';
import 'package:flutterapp/routeeapp/generatedpaymentwidget1/generated/GeneratedImage15Widget.dart';
import 'package:flutterapp/routeeapp/generatedpaymentwidget1/generated/GeneratedWidget4.dart';
import 'package:flutterapp/routeeapp/generatedpaymentwidget1/generated/GeneratedGroup23Widget.dart';
import 'package:flutterapp/routeeapp/generatedpaymentwidget1/generated/GeneratedScanyourtickerPayMonthlyPaidatStationWidget1.dart';
import 'package:flutterapp/routeeapp/generatedpaymentwidget1/generated/GeneratedGroup22Widget2.dart';
import 'package:flutterapp/routeeapp/generatedpaymentwidget1/generated/GeneratedHomeWidget4.dart';
import 'package:flutterapp/routeeapp/generatedpaymentwidget1/generated/GeneratedFrameWidget10.dart';
import 'package:flutterapp/routeeapp/generatedpaymentwidget1/generated/GeneratedYouhaveSubscribedforJanuaryWidget.dart';
import 'package:flutterapp/routeeapp/generatedpaymentwidget1/generated/GeneratedExpirationDate31012022Widget.dart';

/* Frame Payment
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedPaymentWidget1 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(child: LayoutBuilder(
        builder: (BuildContext context, BoxConstraints constraints) {
      return SingleChildScrollView(
        scrollDirection: Axis.vertical,
        child: Container(
            height: 901.3642578125,
            child: Stack(children: [
              Container(
                  width: constraints.maxWidth,
                  child: Container(
                    width: 416.7637939453125,
                    height: 901.3642578125,
                    child: Stack(
                        fit: StackFit.expand,
                        alignment: Alignment.center,
                        overflow: Overflow.visible,
                        children: [
                          Positioned(
                            left: -10.0,
                            top: -15.0,
                            right: null,
                            bottom: null,
                            width: 426.7637939453125,
                            height: 900.41357421875,
                            child: GeneratedHomeWidget4(),
                          ),
                          Positioned(
                            left: 1.0,
                            top: 44.0,
                            right: null,
                            bottom: null,
                            width: 418.0,
                            height: 34.0,
                            child: GeneratedWidget4(),
                          ),
                          Positioned(
                            left: 22.0,
                            top: 50.0,
                            right: null,
                            bottom: null,
                            width: 20.0,
                            height: 20.0,
                            child: GeneratedFrameWidget10(),
                          ),
                          Positioned(
                            left: 28.0,
                            top: 106.0,
                            right: null,
                            bottom: null,
                            width: 361.0,
                            height: 154.0,
                            child:
                                GeneratedScanyourtickerPayMonthlyPaidatStationWidget1(),
                          ),
                          Positioned(
                            left: 326.0,
                            top: 116.0,
                            right: null,
                            bottom: null,
                            width: 57.0,
                            height: 132.0,
                            child: GeneratedGroup22Widget2(),
                          ),
                          Positioned(
                            left: 326.0,
                            top: 168.0,
                            right: null,
                            bottom: null,
                            width: 57.0,
                            height: 28.0,
                            child: GeneratedGroup23Widget(),
                          ),
                          Positioned(
                            left: 92.0,
                            top: 315.0,
                            right: null,
                            bottom: null,
                            width: 231.7870330810547,
                            height: 240.0,
                            child: GeneratedImage15Widget(),
                          ),
                          Positioned(
                            left: 1.0,
                            top: 258.0,
                            right: null,
                            bottom: null,
                            width: 418.0,
                            height: 47.0,
                            child: GeneratedYouhaveSubscribedforJanuaryWidget(),
                          ),
                          Positioned(
                            left: 2.0,
                            top: 611.0,
                            right: null,
                            bottom: null,
                            width: 418.0,
                            height: 47.0,
                            child: GeneratedExpirationDate31012022Widget(),
                          ),
                          Positioned(
                            left: 92.0,
                            top: 569.0,
                            right: null,
                            bottom: null,
                            width: 237.0,
                            height: 37.0,
                            child: GeneratedVALIDWidget(),
                          )
                        ]),
                  ))
            ])),
      );
    }));
  }
}
