import 'package:flutter/material.dart';
import 'package:flutterapp/routeeapp/generatedpaymentwidget/generated/GeneratedGroup22Widget.dart';
import 'package:flutterapp/routeeapp/generatedpaymentwidget/generated/GeneratedRectangle146Widget.dart';
import 'package:flutterapp/routeeapp/generatedpaymentwidget/generated/GeneratedScanyourtickerPayMonthlyPaidatStationWidget.dart';
import 'package:flutterapp/routeeapp/generatedpaymentwidget/generated/GeneratedMonthlySubscriptionWidget.dart';
import 'package:flutterapp/routeeapp/generatedpaymentwidget/generated/GeneratedExpiredWidget1.dart';
import 'package:flutterapp/routeeapp/generatedpaymentwidget/generated/GeneratedHomeWidget3.dart';
import 'package:flutterapp/routeeapp/generatedpaymentwidget/generated/GeneratedExpiredWidget.dart';
import 'package:flutterapp/routeeapp/generatedpaymentwidget/generated/GeneratedWidget3.dart';
import 'package:flutterapp/routeeapp/generatedpaymentwidget/generated/GeneratedFrameWidget8.dart';
import 'package:flutterapp/routeeapp/generatedpaymentwidget/generated/GeneratedRectangle144Widget.dart';
import 'package:flutterapp/routeeapp/generatedpaymentwidget/generated/GeneratedYoursavedticketsWidget.dart';
import 'package:flutterapp/routeeapp/generatedpaymentwidget/generated/GeneratedImage14Widget.dart';
import 'package:flutterapp/routeeapp/generatedpaymentwidget/generated/GeneratedImage12Widget.dart';

/* Frame Payment
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedPaymentWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(child: LayoutBuilder(
        builder: (BuildContext context, BoxConstraints constraints) {
      return SingleChildScrollView(
        scrollDirection: Axis.vertical,
        child: Container(
            height: 901.3642578125,
            child: Stack(children: [
              Container(
                  width: constraints.maxWidth,
                  child: Container(
                    width: 416.7637939453125,
                    height: 901.3642578125,
                    child: Stack(
                        fit: StackFit.expand,
                        alignment: Alignment.center,
                        overflow: Overflow.visible,
                        children: [
                          Positioned(
                            left: -8.0,
                            top: 0.0,
                            right: null,
                            bottom: null,
                            width: 424.7637939453125,
                            height: 900.41357421875,
                            child: GeneratedHomeWidget3(),
                          ),
                          Positioned(
                            left: 1.0,
                            top: 44.0,
                            right: null,
                            bottom: null,
                            width: 418.0,
                            height: 34.0,
                            child: GeneratedWidget3(),
                          ),
                          Positioned(
                            left: 22.0,
                            top: 50.0,
                            right: null,
                            bottom: null,
                            width: 20.0,
                            height: 20.0,
                            child: GeneratedFrameWidget8(),
                          ),
                          Positioned(
                            left: 28.0,
                            top: 106.0,
                            right: null,
                            bottom: null,
                            width: 361.0,
                            height: 154.0,
                            child:
                                GeneratedScanyourtickerPayMonthlyPaidatStationWidget(),
                          ),
                          Positioned(
                            left: 29.0,
                            top: 279.0,
                            right: null,
                            bottom: null,
                            width: 361.0,
                            height: 47.0,
                            child: GeneratedYoursavedticketsWidget(),
                          ),
                          Positioned(
                            left: 326.0,
                            top: 116.0,
                            right: null,
                            bottom: null,
                            width: 57.0,
                            height: 132.0,
                            child: GeneratedGroup22Widget(),
                          ),
                          Positioned(
                            left: 11.0,
                            top: 596.0,
                            right: null,
                            bottom: null,
                            width: 394.0,
                            height: 185.0,
                            child: GeneratedRectangle146Widget(),
                          ),
                          Positioned(
                            left: 189.0,
                            top: 625.0,
                            right: null,
                            bottom: null,
                            width: 163.0,
                            height: 31.0,
                            child: GeneratedMonthlySubscriptionWidget(),
                          ),
                          Positioned(
                            left: 195.0,
                            top: 670.0,
                            right: null,
                            bottom: null,
                            width: 183.0,
                            height: 37.0,
                            child: GeneratedExpiredWidget(),
                          ),
                          Positioned(
                            left: 29.0,
                            top: 608.0,
                            right: null,
                            bottom: null,
                            width: 154.52468872070312,
                            height: 160.0,
                            child: GeneratedImage14Widget(),
                          ),
                          Positioned(
                            left: 10.0,
                            top: 327.0,
                            right: null,
                            bottom: null,
                            width: 394.0,
                            height: 243.0,
                            child: GeneratedRectangle144Widget(),
                          ),
                          Positioned(
                            left: 31.0,
                            top: 538.0,
                            right: null,
                            bottom: null,
                            width: 350.0,
                            height: 37.0,
                            child: GeneratedExpiredWidget1(),
                          ),
                          Positioned(
                            left: 29.0,
                            top: 334.0,
                            right: null,
                            bottom: null,
                            width: 346.53912353515625,
                            height: 204.0,
                            child: GeneratedImage12Widget(),
                          )
                        ]),
                  ))
            ])),
      );
    }));
  }
}
