import 'package:flutter/material.dart';
import 'package:flutterapp/routeeapp/generatedsearchsresultsactivitywidget4/generated/GeneratedExpectedWidget5.dart';
import 'package:flutterapp/routeeapp/generatedsearchsresultsactivitywidget4/generated/GeneratedU2Widget3.dart';
import 'package:flutterapp/routeeapp/generatedsearchsresultsactivitywidget4/generated/GeneratedBackButtonWidget36.dart';
import 'package:flutterapp/routeeapp/generatedsearchsresultsactivitywidget4/generated/GeneratedStartEndTimeButtonWidget5.dart';
import 'package:flutterapp/routeeapp/generatedsearchsresultsactivitywidget4/generated/GeneratedRouteSelectionsWidget12.dart';
import 'package:flutterapp/routeeapp/generatedsearchsresultsactivitywidget4/generated/GeneratedRouteSelectionsWidget15.dart';
import 'package:flutterapp/routeeapp/generatedsearchsresultsactivitywidget4/generated/Generated3Widget3.dart';
import 'package:flutterapp/routeeapp/generatedsearchsresultsactivitywidget4/generated/GeneratedPeopleWidget18.dart';
import 'package:flutterapp/routeeapp/generatedsearchsresultsactivitywidget4/generated/GeneratedRouteSelectionsWidget13.dart';
import 'package:flutterapp/routeeapp/generatedsearchsresultsactivitywidget4/generated/GeneratedPeopleWidget19.dart';
import 'package:flutterapp/routeeapp/generatedsearchsresultsactivitywidget4/generated/GeneratedNowWidget5.dart';
import 'package:flutterapp/routeeapp/generatedsearchsresultsactivitywidget4/generated/GeneratedEndPointButtonWidget5.dart';
import 'package:flutterapp/routeeapp/generatedsearchsresultsactivitywidget4/generated/GeneratedStartPointButtonWidget13.dart';
import 'package:flutterapp/routeeapp/generatedsearchsresultsactivitywidget4/generated/GeneratedBackButtonWidget33.dart';
import 'package:flutterapp/routeeapp/generatedsearchsresultsactivitywidget4/generated/GeneratedRouteSelectionsWidget14.dart';
import 'package:flutterapp/routeeapp/generatedsearchsresultsactivitywidget4/generated/GeneratedStartTimeIconWidget7.dart';
import 'package:flutterapp/routeeapp/generatedsearchsresultsactivitywidget4/generated/GeneratedArrivedin40minutesWidget3.dart';
import 'package:flutterapp/routeeapp/generatedsearchsresultsactivitywidget4/generated/GeneratedGroup8Widget9.dart';
import 'package:flutterapp/routeeapp/generatedsearchsresultsactivitywidget4/generated/GeneratedHomeWidget18.dart';
import 'package:flutterapp/routeeapp/generatedsearchsresultsactivitywidget4/generated/GeneratedPeopleWidget17.dart';
import 'package:flutterapp/routeeapp/generatedsearchsresultsactivitywidget4/generated/GeneratedRoutesLabelWidget4.dart';
import 'package:flutterapp/routeeapp/generatedsearchsresultsactivitywidget4/generated/GeneratedArrivedin20minutesWidget3.dart';
import 'package:flutterapp/routeeapp/generatedsearchsresultsactivitywidget4/generated/Generated1Widget4.dart';
import 'package:flutterapp/routeeapp/generatedsearchsresultsactivitywidget4/generated/GeneratedEndTimeIconWidget3.dart';
import 'package:flutterapp/routeeapp/generatedsearchsresultsactivitywidget4/generated/GeneratedEvery10minutesfromFranzSperrWegWidget3.dart';
import 'package:flutterapp/routeeapp/generatedsearchsresultsactivitywidget4/generated/GeneratedPeopleWidget15.dart';
import 'package:flutterapp/routeeapp/generatedsearchsresultsactivitywidget4/generated/Generated2Widget3.dart';
import 'package:flutterapp/helpers/transform/transform.dart';

/* Frame Search's Results Activity
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedSearchsResultsActivityWidget4 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: Container(
      width: 450.0,
      height: 890.0,
      child: Stack(
          fit: StackFit.expand,
          alignment: Alignment.center,
          overflow: Overflow.visible,
          children: [
            Positioned(
              left: -6.0,
              top: -11.0,
              right: null,
              bottom: null,
              width: 423.0,
              height: 879.4791870117188,
              child: GeneratedHomeWidget18(),
            ),
            Positioned(
              left: 18.0,
              top: 294.0,
              right: null,
              bottom: null,
              width: 384.0,
              height: 30.0,
              child: GeneratedRouteSelectionsWidget12(),
            ),
            Positioned(
              left: 10.0,
              top: 339.0,
              right: null,
              bottom: null,
              width: 384.0,
              height: 24.0,
              child: GeneratedRouteSelectionsWidget13(),
            ),
            Positioned(
              left: 11.0,
              top: 478.0,
              right: null,
              bottom: null,
              width: 384.0,
              height: 24.0,
              child: GeneratedRouteSelectionsWidget14(),
            ),
            Positioned(
              left: 106.0,
              top: 25.0,
              right: null,
              bottom: null,
              width: 215.0,
              height: 34.0,
              child: GeneratedRoutesLabelWidget4(),
            ),
            Positioned(
              left: 19.0,
              top: 32.0,
              right: null,
              bottom: null,
              width: 20.0,
              height: 20.0,
              child: GeneratedBackButtonWidget33(),
            ),
            Positioned(
              left: 37.0,
              top: 91.0,
              right: null,
              bottom: null,
              width: 364.0,
              height: 49.0,
              child: GeneratedStartPointButtonWidget13(),
            ),
            Positioned(
              left: 35.0,
              top: 151.0,
              right: null,
              bottom: null,
              width: 372.0,
              height: 49.0,
              child: GeneratedEndPointButtonWidget5(),
            ),
            Positioned(
              left: 35.0,
              top: 212.0,
              right: null,
              bottom: null,
              width: 364.0,
              height: 49.0,
              child: GeneratedStartEndTimeButtonWidget5(),
            ),
            Positioned(
              left: 59.0,
              top: 224.0,
              right: null,
              bottom: null,
              width: 20.0,
              height: 20.0,
              child: GeneratedStartTimeIconWidget7(),
            ),
            Positioned(
              left: 0.0,
              top: 0.0,
              right: 0.0,
              bottom: 0.0,
              width: null,
              height: null,
              child: LayoutBuilder(
                  builder: (BuildContext context, BoxConstraints constraints) {
                final double width = constraints.maxWidth * 0.04877034505208333;

                final double height =
                    constraints.maxHeight * 0.02212390685349368;

                return Stack(children: [
                  TransformHelper.translate(
                      x: constraints.maxWidth * 0.5288888888888889,
                      y: constraints.maxHeight * 0.2522321379586552,
                      z: 0,
                      child: Container(
                        width: width,
                        height: height,
                        child: GeneratedEndTimeIconWidget3(),
                      ))
                ]);
              }),
            ),
            Positioned(
              left: 9.0,
              top: 360.0,
              right: null,
              bottom: null,
              width: 391.0,
              height: 88.0,
              child: Generated1Widget4(),
            ),
            Positioned(
              left: 50.75,
              top: 403.69232177734375,
              right: null,
              bottom: null,
              width: 12.75,
              height: 14.692307472229004,
              child: GeneratedBackButtonWidget36(),
            ),
            Positioned(
              left: 10.0,
              top: 498.0,
              right: null,
              bottom: null,
              width: 394.0,
              height: 88.0,
              child: Generated2Widget3(),
            ),
            Positioned(
              left: 170.0,
              top: 531.0,
              right: null,
              bottom: null,
              width: 30.0,
              height: 30.0,
              child: GeneratedPeopleWidget15(),
            ),
            Positioned(
              left: 11.0,
              top: 631.0,
              right: null,
              bottom: null,
              width: 392.0,
              height: 88.0,
              child: Generated3Widget3(),
            ),
            Positioned(
              left: 13.0,
              top: 432.0,
              right: null,
              bottom: null,
              width: 276.1730651855469,
              height: 20.88888931274414,
              child: GeneratedEvery10minutesfromFranzSperrWegWidget3(),
            ),
            Positioned(
              left: 15.0,
              top: 415.0,
              right: null,
              bottom: null,
              width: 157.0,
              height: 29.0,
              child: GeneratedArrivedin40minutesWidget3(),
            ),
            Positioned(
              left: 222.0,
              top: 362.0,
              right: null,
              bottom: null,
              width: 70.0,
              height: 30.0,
              child: GeneratedExpectedWidget5(),
            ),
            Positioned(
              left: 0.0,
              top: 0.0,
              right: 0.0,
              bottom: 0.0,
              width: null,
              height: null,
              child: LayoutBuilder(
                  builder: (BuildContext context, BoxConstraints constraints) {
                final double width =
                    constraints.maxWidth * 0.049480421278211804;

                final double height =
                    constraints.maxHeight * 0.01667987952071629;

                return Stack(children: [
                  TransformHelper.translate(
                      x: constraints.maxWidth * 0.1473000759548611,
                      y: constraints.maxHeight * 0.6168539325842697,
                      z: 0,
                      child: Container(
                        width: width,
                        height: height,
                        child: GeneratedU2Widget3(),
                      ))
                ]);
              }),
            ),
            Positioned(
              left: 229.0,
              top: 386.0,
              right: null,
              bottom: null,
              width: 30.0,
              height: 32.30769348144531,
              child: GeneratedPeopleWidget17(),
            ),
            Positioned(
              left: 171.0,
              top: 384.0,
              right: null,
              bottom: null,
              width: 30.0,
              height: 32.30769348144531,
              child: GeneratedPeopleWidget18(),
            ),
            Positioned(
              left: 10.0,
              top: 609.0,
              right: null,
              bottom: null,
              width: 384.0,
              height: 24.0,
              child: GeneratedRouteSelectionsWidget15(),
            ),
            Positioned(
              left: 20.0,
              top: 685.0,
              right: null,
              bottom: null,
              width: 151.07691955566406,
              height: 30.254438400268555,
              child: GeneratedArrivedin20minutesWidget3(),
            ),
            Positioned(
              left: 171.0,
              top: 636.0,
              right: null,
              bottom: null,
              width: 70.0,
              height: 30.0,
              child: GeneratedNowWidget5(),
            ),
            Positioned(
              left: 0.0,
              top: 0.0,
              right: 0.0,
              bottom: 0.0,
              width: null,
              height: null,
              child: LayoutBuilder(
                  builder: (BuildContext context, BoxConstraints constraints) {
                final double width = constraints.maxWidth * 0.07541480170355903;

                final double height =
                    constraints.maxHeight * 0.033707933747366574;

                return Stack(children: [
                  TransformHelper.translate(
                      x: constraints.maxWidth * 0.37148328993055557,
                      y: constraints.maxHeight * 0.7442992478274227,
                      z: 0,
                      child: Container(
                        width: width,
                        height: height,
                        child: GeneratedPeopleWidget19(),
                      ))
                ]);
              }),
            ),
            Positioned(
              left: 91.0,
              top: 383.0,
              right: null,
              bottom: null,
              width: 24.461538314819336,
              height: 26.66666603088379,
              child: GeneratedGroup8Widget9(),
            )
          ]),
    ));
  }
}
