import 'package:flutter/material.dart';

/* Rectangle image 6
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedImage6Widget3 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: Container(
      width: 441.0,
      height: 827.0,
      child: ClipRRect(
        borderRadius: BorderRadius.zero,
        child: Image.asset(
          "assets/images/e5c0bed09adc4dbe8ed727da6f604d1e",
          color: null,
          fit: BoxFit.fill,
          width: 441.0,
          height: 827.0,
          colorBlendMode: BlendMode.dstATop,
        ),
      ),
    ));
  }
}
