import 'package:flutter/material.dart';
import 'package:flutterapp/routeeapp/generatedpaymentwidget2/generated/GeneratedFrameWidget12.dart';
import 'package:flutterapp/routeeapp/generatedpaymentwidget2/generated/GeneratedLine8Widget.dart';
import 'package:flutterapp/routeeapp/generatedpaymentwidget2/generated/GeneratedHomeWidget5.dart';
import 'package:flutterapp/routeeapp/generatedpaymentwidget2/generated/GeneratedSearchButtonWidget.dart';
import 'package:flutterapp/routeeapp/generatedpaymentwidget2/generated/GeneratedPleasescanyourticketintheareabelowWidget.dart';
import 'package:flutterapp/routeeapp/generatedpaymentwidget2/generated/GeneratedGroup22Widget4.dart';
import 'package:flutterapp/routeeapp/generatedpaymentwidget2/generated/GeneratedLine10Widget.dart';
import 'package:flutterapp/routeeapp/generatedpaymentwidget2/generated/GeneratedImage8Widget.dart';
import 'package:flutterapp/routeeapp/generatedpaymentwidget2/generated/GeneratedLine9Widget.dart';
import 'package:flutterapp/routeeapp/generatedpaymentwidget2/generated/GeneratedWidget5.dart';
import 'package:flutterapp/routeeapp/generatedpaymentwidget2/generated/GeneratedScanyourtickerPayMonthlyPaidatStationWidget2.dart';
import 'package:flutterapp/routeeapp/generatedpaymentwidget2/generated/GeneratedGroup21Widget4.dart';
import 'package:flutterapp/routeeapp/generatedpaymentwidget2/generated/GeneratedLine11Widget.dart';

/* Frame Payment
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedPaymentWidget2 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(child: LayoutBuilder(
        builder: (BuildContext context, BoxConstraints constraints) {
      return SingleChildScrollView(
        scrollDirection: Axis.vertical,
        child: Container(
            height: 901.3642578125,
            child: Stack(children: [
              Container(
                  width: constraints.maxWidth,
                  child: Container(
                    width: 416.7637939453125,
                    height: 901.3642578125,
                    child: Stack(
                        fit: StackFit.expand,
                        alignment: Alignment.center,
                        overflow: Overflow.visible,
                        children: [
                          Positioned(
                            left: -9.0,
                            top: 0.0,
                            right: null,
                            bottom: null,
                            width: 425.7637939453125,
                            height: 900.41357421875,
                            child: GeneratedHomeWidget5(),
                          ),
                          Positioned(
                            left: 1.0,
                            top: 44.0,
                            right: null,
                            bottom: null,
                            width: 418.0,
                            height: 34.0,
                            child: GeneratedWidget5(),
                          ),
                          Positioned(
                            left: 22.0,
                            top: 50.0,
                            right: null,
                            bottom: null,
                            width: 20.0,
                            height: 20.0,
                            child: GeneratedFrameWidget12(),
                          ),
                          Positioned(
                            left: 29.0,
                            top: 101.0,
                            right: null,
                            bottom: null,
                            width: 361.0,
                            height: 154.0,
                            child:
                                GeneratedScanyourtickerPayMonthlyPaidatStationWidget2(),
                          ),
                          Positioned(
                            left: 18.0,
                            top: 753.0,
                            right: null,
                            bottom: null,
                            width: 382.0,
                            height: 47.0,
                            child: GeneratedSearchButtonWidget(),
                          ),
                          Positioned(
                            left: 326.0,
                            top: 116.0,
                            right: null,
                            bottom: null,
                            width: 57.0,
                            height: 28.0,
                            child: GeneratedGroup21Widget4(),
                          ),
                          Positioned(
                            left: 326.0,
                            top: 168.0,
                            right: null,
                            bottom: null,
                            width: 57.0,
                            height: 80.0,
                            child: GeneratedGroup22Widget4(),
                          ),
                          Positioned(
                            left: 29.0,
                            top: 270.0,
                            right: null,
                            bottom: null,
                            width: 400.0,
                            height: 33.0,
                            child:
                                GeneratedPleasescanyourticketintheareabelowWidget(),
                          ),
                          Positioned(
                            left: 92.5,
                            top: 325.0,
                            right: null,
                            bottom: null,
                            width: 58.0,
                            height: 55.0,
                            child: GeneratedLine8Widget(),
                          ),
                          Positioned(
                            left: 329.0,
                            top: 702.0,
                            right: null,
                            bottom: null,
                            width: 58.0,
                            height: 55.0,
                            child: GeneratedLine9Widget(),
                          ),
                          Positioned(
                            left: 38.0,
                            top: 647.0,
                            right: null,
                            bottom: null,
                            width: 58.0,
                            height: 55.0,
                            child: GeneratedLine11Widget(),
                          ),
                          Positioned(
                            left: 384.0,
                            top: 380.0,
                            right: null,
                            bottom: null,
                            width: 58.0,
                            height: 55.0,
                            child: GeneratedLine10Widget(),
                          ),
                          Positioned(
                            left: 43.0,
                            top: 328.0,
                            right: null,
                            bottom: null,
                            width: 336.0,
                            height: 370.0,
                            child: GeneratedImage8Widget(),
                          )
                        ]),
                  ))
            ])),
      );
    }));
  }
}
