import 'package:flutter/material.dart';
import 'package:flutterapp/routeeapp/generatedtermsofusewidget1/generated/GeneratedSearchButtonWidget16.dart';
import 'package:flutterapp/helpers/transform/transform.dart';
import 'package:flutterapp/routeeapp/generatedtermsofusewidget1/generated/GeneratedFavoritesButtonWidget.dart';
import 'package:flutterapp/routeeapp/generatedtermsofusewidget1/generated/GeneratedThesearetheTermsandConditionsgoverningtheuseofthisServi.dart';
import 'package:flutterapp/routeeapp/generatedtermsofusewidget1/generated/GeneratedHomeWidget9.dart';
import 'package:flutterapp/routeeapp/generatedtermsofusewidget1/generated/GeneratedPleasereadthesetermsandconditionscarefullybeforeusingOu.dart';
import 'package:flutterapp/routeeapp/generatedtermsofusewidget1/generated/GeneratedInterpretationandDefinitionsWidget.dart';
import 'package:flutterapp/routeeapp/generatedtermsofusewidget1/generated/GeneratedThewordsofwhichtheinitialletteriscapitalizedhavemeaning.dart';
import 'package:flutterapp/routeeapp/generatedtermsofusewidget1/generated/GeneratedMenuBarWidget9.dart';
import 'package:flutterapp/routeeapp/generatedtermsofusewidget1/generated/GeneratedInterpretationWidget.dart';
import 'package:flutterapp/routeeapp/generatedtermsofusewidget1/generated/GeneratedStartNavigationLabelWidget.dart';
import 'package:flutterapp/routeeapp/generatedtermsofusewidget1/generated/GeneratedBackButtonWidget.dart';

/* Frame Terms of Use
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedTermsofUseWidget1 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: LayoutBuilder(
          builder: (BuildContext context, BoxConstraints constraints) {
        return SingleChildScrollView(
          scrollDirection: Axis.vertical,
          child: Container(
              height: 902.4135894775391,
              child: Stack(children: [
                Container(
                    width: constraints.maxWidth,
                    child: Container(
                      width: 416.7637939453125,
                      height: 901.3642578125,
                      child: Stack(
                          fit: StackFit.expand,
                          alignment: Alignment.center,
                          overflow: Overflow.visible,
                          children: [
                            Positioned(
                              left: -3.0,
                              top: 1.0,
                              right: null,
                              bottom: null,
                              width: 416.7637939453125,
                              height: 900.02490234375,
                              child: GeneratedHomeWidget9(),
                            ),
                            Positioned(
                              left: 12.0,
                              top: 765.0,
                              right: null,
                              bottom: null,
                              width: 184.0,
                              height: 47.0,
                              child: GeneratedSearchButtonWidget16(),
                            ),
                            Positioned(
                              left: -11.0,
                              top: 24.0,
                              right: null,
                              bottom: null,
                              width: 416.0,
                              height: 34.0,
                              child: GeneratedStartNavigationLabelWidget(),
                            ),
                            Positioned(
                              left: 16.0,
                              top: 36.0,
                              right: null,
                              bottom: null,
                              width: 20.0,
                              height: 20.0,
                              child: GeneratedBackButtonWidget(),
                            ),
                            Positioned(
                              left: 0.0,
                              top: 0.0,
                              right: 0.0,
                              bottom: 0.0,
                              width: null,
                              height: null,
                              child: LayoutBuilder(builder:
                                  (BuildContext context,
                                      BoxConstraints constraints) {
                                double percentWidth = 0.07511385956711067;
                                double scaleX =
                                    (constraints.maxWidth * percentWidth) /
                                        31.304737091064453;

                                double percentHeight = 0.03328288174284424;
                                double scaleY =
                                    (constraints.maxHeight * percentHeight) /
                                        30.0;

                                return Stack(children: [
                                  TransformHelper.translateAndScale(
                                      translateX: constraints.maxWidth *
                                          0.8757958471985094,
                                      translateY: constraints.maxHeight *
                                          0.03883002869998494,
                                      translateZ: 0,
                                      scaleX: scaleX,
                                      scaleY: scaleY,
                                      scaleZ: 1,
                                      child: GeneratedFavoritesButtonWidget())
                                ]);
                              }),
                            ),
                            Positioned(
                              left: 39.0,
                              top: 127.0,
                              right: null,
                              bottom: null,
                              width: 340.0,
                              height: 53.0,
                              child:
                                  GeneratedPleasereadthesetermsandconditionscarefullybeforeusingOu(),
                            ),
                            Positioned(
                              left: 39.0,
                              top: 238.0,
                              right: null,
                              bottom: null,
                              width: 346.0,
                              height: 167.0,
                              child:
                                  GeneratedThewordsofwhichtheinitialletteriscapitalizedhavemeaning(),
                            ),
                            Positioned(
                              left: 40.0,
                              top: 459.0,
                              right: null,
                              bottom: null,
                              width: 342.0,
                              height: 360.0,
                              child:
                                  GeneratedThesearetheTermsandConditionsgoverningtheuseofthisServi(),
                            ),
                            Positioned(
                              left: 34.0,
                              top: 184.0,
                              right: null,
                              bottom: null,
                              width: 350.0,
                              height: 26.0,
                              child:
                                  GeneratedInterpretationandDefinitionsWidget(),
                            ),
                            Positioned(
                              left: 33.0,
                              top: 246.0,
                              right: null,
                              bottom: null,
                              width: 350.0,
                              height: 26.0,
                              child: GeneratedInterpretationWidget(),
                            ),
                            Positioned(
                              left: -11.0,
                              top: 813.0,
                              right: null,
                              bottom: null,
                              width: 416.1277160644531,
                              height: 89.41358947753906,
                              child: GeneratedMenuBarWidget9(),
                            )
                          ]),
                    ))
              ])),
        );
      }),
    ));
  }
}
