import 'package:flutter/material.dart';
import 'package:flutterapp/routeeapp/generatedmaskgroupwidget2/generated/GeneratedUnionWidget1.dart';

/* Group Mask Group
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedMaskGroupWidget2 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: Container(
      width: 0.0,
      height: 0.0,
      child: Stack(
          fit: StackFit.expand,
          alignment: Alignment.center,
          overflow: Overflow.visible,
          children: [
            Positioned(
              left: 0.0,
              top: 0.0,
              right: null,
              bottom: null,
              width: 416.7637939453125,
              height: 901.3642578125,
              child: GeneratedUnionWidget1(),
            )
          ]),
    ));
  }
}
