import 'package:flutter/material.dart';
import 'package:flutterapp/routeeapp/generatedsearchsresultsactivitywidget1/generated/GeneratedNotificationsWidget4.dart';
import 'package:flutterapp/routeeapp/generatedsearchsresultsactivitywidget1/generated/GeneratedBackButtonWidget10.dart';
import 'package:flutterapp/routeeapp/generatedsearchsresultsactivitywidget1/generated/Generated1Widget1.dart';
import 'package:flutterapp/routeeapp/generatedsearchsresultsactivitywidget1/generated/Generated3Widget1.dart';
import 'package:flutterapp/routeeapp/generatedsearchsresultsactivitywidget1/generated/GeneratedPeopleWidget4.dart';
import 'package:flutterapp/routeeapp/generatedsearchsresultsactivitywidget1/generated/GeneratedRoutesLabelWidget1.dart';
import 'package:flutterapp/routeeapp/generatedsearchsresultsactivitywidget1/generated/GeneratedPeopleWidget3.dart';
import 'package:flutterapp/routeeapp/generatedsearchsresultsactivitywidget1/generated/GeneratedGroup20Widget.dart';
import 'package:flutterapp/routeeapp/generatedsearchsresultsactivitywidget1/generated/GeneratedRouteSelectionsWidget4.dart';
import 'package:flutterapp/routeeapp/generatedsearchsresultsactivitywidget1/generated/GeneratedU3Widget1.dart';
import 'package:flutterapp/routeeapp/generatedsearchsresultsactivitywidget1/generated/GeneratedStartPointButtonWidget1.dart';
import 'package:flutterapp/routeeapp/generatedsearchsresultsactivitywidget1/generated/GeneratedEndPointButtonWidget1.dart';
import 'package:flutterapp/routeeapp/generatedsearchsresultsactivitywidget1/generated/GeneratedRectangle142Widget.dart';
import 'package:flutterapp/routeeapp/generatedsearchsresultsactivitywidget1/generated/GeneratedGroupWidget157.dart';
import 'package:flutterapp/routeeapp/generatedsearchsresultsactivitywidget1/generated/GeneratedStartTimeIconWidget1.dart';
import 'package:flutterapp/routeeapp/generatedsearchsresultsactivitywidget1/generated/GeneratedVectorWidget281.dart';
import 'package:flutterapp/routeeapp/generatedsearchsresultsactivitywidget1/generated/GeneratedU2Widget1.dart';
import 'package:flutterapp/routeeapp/generatedsearchsresultsactivitywidget1/generated/GeneratedEndTimeIconWidget1.dart';
import 'package:flutterapp/routeeapp/generatedsearchsresultsactivitywidget1/generated/GeneratedStartEndTimeButtonWidget1.dart';
import 'package:flutterapp/routeeapp/generatedsearchsresultsactivitywidget1/generated/GeneratedRouteSelectionsWidget3.dart';
import 'package:flutterapp/routeeapp/generatedsearchsresultsactivitywidget1/generated/GeneratedPeopleWidget5.dart';
import 'package:flutterapp/helpers/transform/transform.dart';
import 'package:flutterapp/routeeapp/generatedsearchsresultsactivitywidget1/generated/Generated2Widget1.dart';
import 'package:flutterapp/routeeapp/generatedsearchsresultsactivitywidget1/generated/GeneratedMenuBarWidget12.dart';
import 'package:flutterapp/routeeapp/generatedsearchsresultsactivitywidget1/generated/GeneratedRouteSelectionsWidget5.dart';
import 'package:flutterapp/routeeapp/generatedsearchsresultsactivitywidget1/generated/GeneratedHomeWidget12.dart';
import 'package:flutterapp/routeeapp/generatedsearchsresultsactivitywidget1/generated/GeneratedNotificationsWidget5.dart';

/* Frame Search's Results Activity
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedSearchsResultsActivityWidget1 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(child: LayoutBuilder(
        builder: (BuildContext context, BoxConstraints constraints) {
      return SingleChildScrollView(
        scrollDirection: Axis.vertical,
        child: Container(
            height: 901.4135894775391,
            child: Stack(children: [
              Container(
                  width: constraints.maxWidth,
                  child: Container(
                    width: 416.7637939453125,
                    height: 901.3642578125,
                    child: Stack(
                        fit: StackFit.expand,
                        alignment: Alignment.center,
                        overflow: Overflow.visible,
                        children: [
                          Positioned(
                            left: 0.0,
                            top: 0.0,
                            right: null,
                            bottom: null,
                            width: 416.7637939453125,
                            height: 900.02490234375,
                            child: GeneratedHomeWidget12(),
                          ),
                          Positioned(
                            left: -10.0,
                            top: 812.0,
                            right: null,
                            bottom: null,
                            width: 416.1277160644531,
                            height: 89.41358947753906,
                            child: GeneratedMenuBarWidget12(),
                          ),
                          Positioned(
                            left: 15.0,
                            top: 307.0,
                            right: null,
                            bottom: null,
                            width: 384.0,
                            height: 30.0,
                            child: GeneratedRouteSelectionsWidget3(),
                          ),
                          Positioned(
                            left: 15.0,
                            top: 339.0,
                            right: null,
                            bottom: null,
                            width: 384.0,
                            height: 24.0,
                            child: GeneratedRouteSelectionsWidget4(),
                          ),
                          Positioned(
                            left: 14.0,
                            top: 459.0,
                            right: null,
                            bottom: null,
                            width: 384.0,
                            height: 24.0,
                            child: GeneratedRouteSelectionsWidget5(),
                          ),
                          Positioned(
                            left: 103.0,
                            top: 44.0,
                            right: null,
                            bottom: null,
                            width: 215.0,
                            height: 34.0,
                            child: GeneratedRoutesLabelWidget1(),
                          ),
                          Positioned(
                            left: 16.0,
                            top: 51.0,
                            right: null,
                            bottom: null,
                            width: 20.0,
                            height: 20.0,
                            child: GeneratedBackButtonWidget10(),
                          ),
                          Positioned(
                            left: 15.0,
                            top: 103.0,
                            right: null,
                            bottom: null,
                            width: 382.0,
                            height: 55.0,
                            child: GeneratedStartPointButtonWidget1(),
                          ),
                          Positioned(
                            left: 15.0,
                            top: 166.0,
                            right: null,
                            bottom: null,
                            width: 382.0,
                            height: 55.0,
                            child: GeneratedEndPointButtonWidget1(),
                          ),
                          Positioned(
                            left: 15.0,
                            top: 229.0,
                            right: null,
                            bottom: null,
                            width: 382.0,
                            height: 55.0,
                            child: GeneratedStartEndTimeButtonWidget1(),
                          ),
                          Positioned(
                            left: 36.0,
                            top: 248.0,
                            right: null,
                            bottom: null,
                            width: 20.0,
                            height: 20.0,
                            child: GeneratedStartTimeIconWidget1(),
                          ),
                          Positioned(
                            left: 0.0,
                            top: 0.0,
                            right: 0.0,
                            bottom: 0.0,
                            width: null,
                            height: null,
                            child: LayoutBuilder(builder: (BuildContext context,
                                BoxConstraints constraints) {
                              final double width =
                                  constraints.maxWidth * 0.04879796940888877;

                              final double height =
                                  constraints.maxHeight * 0.02218858782856282;

                              return Stack(children: [
                                TransformHelper.translate(
                                    x: constraints.maxWidth * 0.542273593059899,
                                    y: constraints.maxHeight *
                                        0.27624791846560715,
                                    z: 0,
                                    child: Container(
                                      width: width,
                                      height: height,
                                      child: GeneratedEndTimeIconWidget1(),
                                    ))
                              ]);
                            }),
                          ),
                          Positioned(
                            left: 2.0,
                            top: 366.0,
                            right: null,
                            bottom: null,
                            width: 416.0,
                            height: 90.0,
                            child: Generated1Widget1(),
                          ),
                          Positioned(
                            left: 0.0,
                            top: 485.0,
                            right: null,
                            bottom: null,
                            width: 416.0,
                            height: 92.0,
                            child: Generated2Widget1(),
                          ),
                          Positioned(
                            left: 0.0,
                            top: 0.0,
                            right: 0.0,
                            bottom: 0.0,
                            width: null,
                            height: null,
                            child: LayoutBuilder(builder: (BuildContext context,
                                BoxConstraints constraints) {
                              final double width =
                                  constraints.maxWidth * 0.03552103351250055;

                              final double height =
                                  constraints.maxHeight * 0.033283061608678034;

                              return Stack(children: [
                                TransformHelper.translate(
                                    x: constraints.maxWidth *
                                        0.04079049151335524,
                                    y: constraints.maxHeight *
                                        0.5602618426712113,
                                    z: 0,
                                    child: Container(
                                      width: width,
                                      height: height,
                                      child: GeneratedGroupWidget157(),
                                    ))
                              ]);
                            }),
                          ),
                          Positioned(
                            left: 0.0,
                            top: 584.0,
                            right: null,
                            bottom: null,
                            width: 416.0,
                            height: 90.0,
                            child: Generated3Widget1(),
                          ),
                          Positioned(
                            left: 0.0,
                            top: 0.0,
                            right: 0.0,
                            bottom: 0.0,
                            width: null,
                            height: null,
                            child: LayoutBuilder(builder: (BuildContext context,
                                BoxConstraints constraints) {
                              final double width =
                                  constraints.maxWidth * 0.05038825422238;

                              final double height =
                                  constraints.maxHeight * 0.01664144087142212;

                              return Stack(children: [
                                TransformHelper.translate(
                                    x: constraints.maxWidth * 0.15116476266714,
                                    y: constraints.maxHeight *
                                        0.5924352950226274,
                                    z: 0,
                                    child: Container(
                                      width: width,
                                      height: height,
                                      child: GeneratedU2Widget1(),
                                    ))
                              ]);
                            }),
                          ),
                          Positioned(
                            left: 0.0,
                            top: 0.0,
                            right: 0.0,
                            bottom: 0.0,
                            width: null,
                            height: null,
                            child: LayoutBuilder(builder: (BuildContext context,
                                BoxConstraints constraints) {
                              final double width =
                                  constraints.maxWidth * 0.05038825422238;

                              final double height =
                                  constraints.maxHeight * 0.01664144087142212;

                              return Stack(children: [
                                TransformHelper.translate(
                                    x: constraints.maxWidth *
                                        0.2591395931436686,
                                    y: constraints.maxHeight *
                                        0.6945027990340163,
                                    z: 0,
                                    child: Container(
                                      width: width,
                                      height: height,
                                      child: GeneratedU3Widget1(),
                                    ))
                              ]);
                            }),
                          ),
                          Positioned(
                            left: 307.0,
                            top: 399.0,
                            right: null,
                            bottom: null,
                            width: 30.0,
                            height: 30.0,
                            child: GeneratedPeopleWidget3(),
                          ),
                          Positioned(
                            left: 308.0,
                            top: 513.0,
                            right: null,
                            bottom: null,
                            width: 30.0,
                            height: 30.0,
                            child: GeneratedPeopleWidget4(),
                          ),
                          Positioned(
                            left: 309.0,
                            top: 612.0,
                            right: null,
                            bottom: null,
                            width: 30.0,
                            height: 30.0,
                            child: GeneratedPeopleWidget5(),
                          ),
                          Positioned(
                            left: 360.0,
                            top: 515.0,
                            right: null,
                            bottom: null,
                            width: 26.0,
                            height: 26.0,
                            child: GeneratedNotificationsWidget4(),
                          ),
                          Positioned(
                            left: 360.0,
                            top: 613.0,
                            right: null,
                            bottom: null,
                            width: 26.0,
                            height: 26.0,
                            child: GeneratedNotificationsWidget5(),
                          ),
                          Positioned(
                            left: 0.0,
                            top: 0.0,
                            right: 0.0,
                            bottom: 0.0,
                            width: null,
                            height: null,
                            child: LayoutBuilder(builder: (BuildContext context,
                                BoxConstraints constraints) {
                              double percentWidth = 0.04682852950928333;
                              double scaleX =
                                  (constraints.maxWidth * percentWidth) /
                                      19.516435623168945;

                              double percentHeight = 0.02523951865499021;
                              double scaleY =
                                  (constraints.maxHeight * percentHeight) /
                                      22.75;

                              return Stack(children: [
                                TransformHelper.translateAndScale(
                                    translateX: constraints.maxWidth *
                                        0.8709969658439971,
                                    translateY: constraints.maxHeight *
                                        0.4459906153541127,
                                    translateZ: 0,
                                    scaleX: scaleX,
                                    scaleY: scaleY,
                                    scaleZ: 1,
                                    child: GeneratedVectorWidget281())
                              ]);
                            }),
                          ),
                          Positioned(
                            left: 0.0,
                            top: -14.0,
                            right: null,
                            bottom: null,
                            width: 416.0,
                            height: 901.0,
                            child: GeneratedRectangle142Widget(),
                          ),
                          Positioned(
                            left: 19.0,
                            top: 145.0,
                            right: null,
                            bottom: null,
                            width: 382.0,
                            height: 295.0,
                            child: GeneratedGroup20Widget(),
                          )
                        ]),
                  ))
            ])),
      );
    }));
  }
}
