import 'package:flutter/material.dart';
import 'package:flutterapp/routeeapp/generatedsearchactivitywidget1/generated/GeneratedGroup16Widget.dart';
import 'package:flutterapp/routeeapp/generatedsearchactivitywidget1/generated/GeneratedImage6Widget1.dart';
import 'package:flutterapp/routeeapp/generatedsearchactivitywidget1/generated/GeneratedStartPointButtonWidget4.dart';
import 'package:flutterapp/routeeapp/generatedsearchactivitywidget1/generated/GeneratedMenuBarWidget15.dart';
import 'package:flutterapp/routeeapp/generatedsearchactivitywidget1/generated/GeneratedRectangle110Widget15.dart';

/* Frame Search Activity
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedSearchActivityWidget1 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: LayoutBuilder(
          builder: (BuildContext context, BoxConstraints constraints) {
        return SingleChildScrollView(
          scrollDirection: Axis.vertical,
          child: Container(
              height: 901.3642578125,
              child: Stack(children: [
                Container(
                    width: constraints.maxWidth,
                    child: Container(
                      width: 416.7637939453125,
                      height: 901.3642578125,
                      child: Stack(
                          fit: StackFit.expand,
                          alignment: Alignment.center,
                          overflow: Overflow.visible,
                          children: [
                            Positioned(
                              left: 0.0,
                              top: 0.025390625,
                              right: null,
                              bottom: null,
                              width: 416.0,
                              height: 900.0,
                              child: GeneratedRectangle110Widget15(),
                            ),
                            Positioned(
                              left: -37.0,
                              top: 0.0,
                              right: null,
                              bottom: null,
                              width: 776.0,
                              height: 831.0,
                              child: GeneratedImage6Widget1(),
                            ),
                            Positioned(
                              left: 15.0,
                              top: 36.0,
                              right: null,
                              bottom: null,
                              width: 382.0,
                              height: 55.0,
                              child: GeneratedStartPointButtonWidget4(),
                            ),
                            Positioned(
                              left: -7.0,
                              top: 804.0,
                              right: null,
                              bottom: null,
                              width: 416.1277160644531,
                              height: 89.41358947753906,
                              child: GeneratedMenuBarWidget15(),
                            ),
                            Positioned(
                              left: 31.0,
                              top: 780.0,
                              right: null,
                              bottom: null,
                              width: 356.0,
                              height: 32.0,
                              child: GeneratedGroup16Widget(),
                            )
                          ]),
                    ))
              ])),
        );
      }),
    ));
  }
}
