import 'package:flutter/material.dart';
import 'package:flutterapp/routeeapp/generatedregisterwidget2/generated/GeneratedProfileiconWidget1.dart';
import 'package:flutterapp/routeeapp/generatedregisterwidget2/generated/GeneratedListWidget13.dart';
import 'package:flutterapp/routeeapp/generatedregisterwidget2/generated/GeneratedVectorWidget401.dart';
import 'package:flutterapp/routeeapp/generatedregisterwidget2/generated/GeneratedRectangle110Widget19.dart';
import 'package:flutterapp/routeeapp/generatedregisterwidget2/generated/GeneratedListWidget14.dart';
import 'package:flutterapp/routeeapp/generatedregisterwidget2/generated/GeneratedSurnameWidget1.dart';
import 'package:flutterapp/routeeapp/generatedregisterwidget2/generated/GeneratedListWidget12.dart';
import 'package:flutterapp/routeeapp/generatedregisterwidget2/generated/GeneratedRegisterWidget3.dart';
import 'package:flutterapp/routeeapp/generatedregisterwidget2/generated/GeneratedLinkyouBankAccountWidget1.dart';
import 'package:flutterapp/routeeapp/generatedregisterwidget2/generated/GeneratedListWidget15.dart';
import 'package:flutterapp/routeeapp/generatedregisterwidget2/generated/GeneratedBankInformationWidget.dart';
import 'package:flutterapp/helpers/transform/transform.dart';
import 'package:flutterapp/routeeapp/generatedregisterwidget2/generated/GeneratedNavbarWidget3.dart';
import 'package:flutterapp/routeeapp/generatedregisterwidget2/generated/GeneratedNameWidget1.dart';
import 'package:flutterapp/routeeapp/generatedregisterwidget2/generated/GeneratedRectangle147Widget1.dart';
import 'package:flutterapp/routeeapp/generatedregisterwidget2/generated/GeneratedListWidget11.dart';

/* Frame Register
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedRegisterWidget2 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(child: LayoutBuilder(
        builder: (BuildContext context, BoxConstraints constraints) {
      return SingleChildScrollView(
        scrollDirection: Axis.vertical,
        child: Container(
            height: 901.3642578125,
            child: Stack(children: [
              Container(
                  width: constraints.maxWidth,
                  child: Container(
                    width: 416.7637939453125,
                    height: 901.3642578125,
                    child: Stack(
                        fit: StackFit.expand,
                        alignment: Alignment.center,
                        overflow: Overflow.visible,
                        children: [
                          Positioned(
                            left: 0.0,
                            top: 0.025390625,
                            right: null,
                            bottom: null,
                            width: 416.0,
                            height: 900.0,
                            child: GeneratedRectangle110Widget19(),
                          ),
                          Positioned(
                            left: 36.0,
                            top: 571.0,
                            right: null,
                            bottom: null,
                            width: 20.0,
                            height: 20.0,
                            child: GeneratedRectangle147Widget1(),
                          ),
                          Positioned(
                            left: 0.0,
                            top: 0.0,
                            right: 0.0,
                            bottom: 0.0,
                            width: null,
                            height: null,
                            child: LayoutBuilder(builder: (BuildContext context,
                                BoxConstraints constraints) {
                              final double width =
                                  constraints.maxWidth * 0.9165863387118647;

                              final double height =
                                  constraints.maxHeight * 0.06212804591997591;

                              return Stack(children: [
                                TransformHelper.translate(
                                    x: constraints.maxWidth *
                                        0.04318993219061143,
                                    y: constraints.maxHeight *
                                        0.5569335544969268,
                                    z: 0,
                                    child: Container(
                                      width: width,
                                      height: height,
                                      child: GeneratedListWidget11(),
                                    ))
                              ]);
                            }),
                          ),
                          Positioned(
                            left: 0.0,
                            top: 0.0,
                            right: 0.0,
                            bottom: 0.0,
                            width: null,
                            height: null,
                            child: LayoutBuilder(builder: (BuildContext context,
                                BoxConstraints constraints) {
                              final double width =
                                  constraints.maxWidth * 0.9165863387118647;

                              final double height =
                                  constraints.maxHeight * 0.06212804591997591;

                              return Stack(children: [
                                TransformHelper.translate(
                                    x: constraints.maxWidth *
                                        0.045589372867867614,
                                    y: constraints.maxHeight *
                                        0.7044876635568696,
                                    z: 0,
                                    child: Container(
                                      width: width,
                                      height: height,
                                      child: GeneratedListWidget12(),
                                    ))
                              ]);
                            }),
                          ),
                          Positioned(
                            left: 0.0,
                            top: 0.0,
                            right: 0.0,
                            bottom: 0.0,
                            width: null,
                            height: null,
                            child: LayoutBuilder(builder: (BuildContext context,
                                BoxConstraints constraints) {
                              final double width =
                                  constraints.maxWidth * 0.9165863387118647;

                              final double height =
                                  constraints.maxHeight * 0.06212804591997591;

                              return Stack(children: [
                                TransformHelper.translate(
                                    x: constraints.maxWidth *
                                        0.04318993219061143,
                                    y: constraints.maxHeight *
                                        0.7799288621739833,
                                    z: 0,
                                    child: Container(
                                      width: width,
                                      height: height,
                                      child: GeneratedListWidget13(),
                                    ))
                              ]);
                            }),
                          ),
                          Positioned(
                            left: 0.0,
                            top: 0.0,
                            right: 0.0,
                            bottom: 0.0,
                            width: null,
                            height: null,
                            child: LayoutBuilder(builder: (BuildContext context,
                                BoxConstraints constraints) {
                              final double width =
                                  constraints.maxWidth * 0.9165863387118647;

                              final double height =
                                  constraints.maxHeight * 0.06212804591997591;

                              return Stack(children: [
                                TransformHelper.translate(
                                    x: constraints.maxWidth *
                                        0.04318993219061143,
                                    y: constraints.maxHeight *
                                        0.4859300734455258,
                                    z: 0,
                                    child: Container(
                                      width: width,
                                      height: height,
                                      child: GeneratedListWidget14(),
                                    ))
                              ]);
                            }),
                          ),
                          Positioned(
                            left: 0.0,
                            top: 0.0,
                            right: 0.0,
                            bottom: 0.0,
                            width: null,
                            height: null,
                            child: LayoutBuilder(builder: (BuildContext context,
                                BoxConstraints constraints) {
                              final double width =
                                  constraints.maxWidth * 0.9165863387118647;

                              final double height =
                                  constraints.maxHeight * 0.06212804591997591;

                              return Stack(children: [
                                TransformHelper.translate(
                                    x: constraints.maxWidth *
                                        0.04318993219061143,
                                    y: constraints.maxHeight *
                                        0.41492659239412477,
                                    z: 0,
                                    child: Container(
                                      width: width,
                                      height: height,
                                      child: GeneratedListWidget15(),
                                    ))
                              ]);
                            }),
                          ),
                          Positioned(
                            left: 0.0,
                            top: 0.0,
                            right: 0.0,
                            bottom: 0.0,
                            width: null,
                            height: null,
                            child: LayoutBuilder(builder: (BuildContext context,
                                BoxConstraints constraints) {
                              final double width =
                                  constraints.maxWidth * 0.9165863387118647;

                              final double height =
                                  constraints.maxHeight * 0.06212804591997591;

                              return Stack(children: [
                                TransformHelper.translate(
                                    x: constraints.maxWidth *
                                        0.04318993219061143,
                                    y: constraints.maxHeight *
                                        0.34392311134272374,
                                    z: 0,
                                    child: Container(
                                      width: width,
                                      height: height,
                                      child: GeneratedSurnameWidget1(),
                                    ))
                              ]);
                            }),
                          ),
                          Positioned(
                            left: 18.0,
                            top: 246.0,
                            right: 16.7637939453125,
                            bottom: null,
                            width: null,
                            height: 56.0,
                            child: GeneratedNameWidget1(),
                          ),
                          Positioned(
                            left: 0.0,
                            top: 0.0,
                            right: 0.0,
                            bottom: 0.0,
                            width: null,
                            height: null,
                            child: LayoutBuilder(builder: (BuildContext context,
                                BoxConstraints constraints) {
                              double percentWidth = 0.23994406772561905;
                              double scaleX =
                                  (constraints.maxWidth * percentWidth) / 100.0;

                              double percentHeight = 0.11094293914281411;
                              double scaleY =
                                  (constraints.maxHeight * percentHeight) /
                                      100.0;

                              return Stack(children: [
                                TransformHelper.translateAndScale(
                                    translateX: constraints.maxWidth *
                                        0.3815110676837343,
                                    translateY: constraints.maxHeight *
                                        0.12869380940566438,
                                    translateZ: 0,
                                    scaleX: scaleX,
                                    scaleY: scaleY,
                                    scaleZ: 1,
                                    child: GeneratedProfileiconWidget1())
                              ]);
                            }),
                          ),
                          Positioned(
                            left: 17.0,
                            top: null,
                            right: 17.7637939453125,
                            bottom: 63.3642578125,
                            width: null,
                            height: 49.0,
                            child: GeneratedRegisterWidget3(),
                          ),
                          Positioned(
                            left: 0.999908447265625,
                            top: 0.0,
                            right: null,
                            bottom: null,
                            width: 416.0000915527344,
                            height: 87.671142578125,
                            child: GeneratedNavbarWidget3(),
                          ),
                          Positioned(
                            left: 66.0,
                            top: 566.0,
                            right: null,
                            bottom: null,
                            width: 352.0,
                            height: 32.0,
                            child: GeneratedLinkyouBankAccountWidget1(),
                          ),
                          Positioned(
                            left: 27.0,
                            top: 604.0,
                            right: null,
                            bottom: null,
                            width: 352.0,
                            height: 32.0,
                            child: GeneratedBankInformationWidget(),
                          ),
                          Positioned(
                            left: 0.0,
                            top: 0.0,
                            right: 0.0,
                            bottom: 0.0,
                            width: null,
                            height: null,
                            child: LayoutBuilder(builder: (BuildContext context,
                                BoxConstraints constraints) {
                              double percentWidth = 0.02999300846570238;
                              double scaleX =
                                  (constraints.maxWidth * percentWidth) / 12.5;

                              double percentHeight = 0.01109429391428141;
                              double scaleY =
                                  (constraints.maxHeight * percentHeight) /
                                      10.0;

                              return Stack(children: [
                                TransformHelper.translateAndScale(
                                    translateX: constraints.maxWidth *
                                        0.09597762709024761,
                                    translateY: constraints.maxHeight *
                                        0.6390313294626093,
                                    translateZ: 0,
                                    scaleX: scaleX,
                                    scaleY: scaleY,
                                    scaleZ: 1,
                                    child: GeneratedVectorWidget401())
                              ]);
                            }),
                          )
                        ]),
                  ))
            ])),
      );
    }));
  }
}
