import 'package:flutter/material.dart';
import 'package:flutterapp/routeeapp/generatedprofileactivitywidget/generated/GeneratedLine4Widget.dart';
import 'package:flutterapp/routeeapp/generatedprofileactivitywidget/generated/GeneratedFrameWidget2.dart';
import 'package:flutterapp/routeeapp/generatedprofileactivitywidget/generated/GeneratedLine6Widget.dart';
import 'package:flutterapp/routeeapp/generatedprofileactivitywidget/generated/GeneratedHomeWidget.dart';
import 'package:flutterapp/routeeapp/generatedprofileactivitywidget/generated/GeneratedNotificationsWidget.dart';
import 'package:flutterapp/routeeapp/generatedprofileactivitywidget/generated/GeneratedOnlineWidget.dart';
import 'package:flutterapp/routeeapp/generatedprofileactivitywidget/generated/GeneratedChangePaymentInformationWidget.dart';
import 'package:flutterapp/routeeapp/generatedprofileactivitywidget/generated/GeneratedNotificationsWidget1.dart';
import 'package:flutterapp/routeeapp/generatedprofileactivitywidget/generated/GeneratedWalletoutlineWidget.dart';
import 'package:flutterapp/routeeapp/generatedprofileactivitywidget/generated/GeneratedDocumenttextoutlineWidget.dart';
import 'package:flutterapp/routeeapp/generatedprofileactivitywidget/generated/GeneratedStavroulaSarriWidget.dart';
import 'package:flutterapp/routeeapp/generatedprofileactivitywidget/generated/GeneratedLine5Widget.dart';
import 'package:flutterapp/routeeapp/generatedprofileactivitywidget/generated/GeneratedHelpWidget.dart';
import 'package:flutterapp/routeeapp/generatedprofileactivitywidget/generated/GeneratedLine3Widget.dart';
import 'package:flutterapp/routeeapp/generatedprofileactivitywidget/generated/Generated19920Widget.dart';
import 'package:flutterapp/routeeapp/generatedprofileactivitywidget/generated/GeneratedTermsofUseWidget.dart';
import 'package:flutterapp/routeeapp/generatedprofileactivitywidget/generated/GeneratedWidget.dart';
import 'package:flutterapp/routeeapp/generatedprofileactivitywidget/generated/GeneratedFrameWidget1.dart';
import 'package:flutterapp/routeeapp/generatedprofileactivitywidget/generated/GeneratedSsarrigmailcomWidget.dart';
import 'package:flutterapp/routeeapp/generatedprofileactivitywidget/generated/GeneratedSettingsWidget.dart';

/* Frame Profile Activity
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedProfileActivityWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(child: LayoutBuilder(
        builder: (BuildContext context, BoxConstraints constraints) {
      return SingleChildScrollView(
        scrollDirection: Axis.vertical,
        child: Container(
            height: 901.41357421875,
            child: Stack(children: [
              Container(
                  width: constraints.maxWidth,
                  child: Container(
                    width: 416.7637939453125,
                    height: 901.3642578125,
                    child: Stack(
                        fit: StackFit.expand,
                        alignment: Alignment.center,
                        overflow: Overflow.visible,
                        children: [
                          Positioned(
                            left: -13.0,
                            top: 0.0,
                            right: null,
                            bottom: null,
                            width: 429.7637939453125,
                            height: 901.41357421875,
                            child: GeneratedHomeWidget(),
                          ),
                          Positioned(
                            left: 18.0,
                            top: 244.0,
                            right: null,
                            bottom: null,
                            width: 384.0,
                            height: 27.0,
                            child: GeneratedSsarrigmailcomWidget(),
                          ),
                          Positioned(
                            left: 18.0,
                            top: 275.0,
                            right: null,
                            bottom: null,
                            width: 384.0,
                            height: 27.0,
                            child: GeneratedOnlineWidget(),
                          ),
                          Positioned(
                            left: 16.0,
                            top: 213.0,
                            right: null,
                            bottom: null,
                            width: 389.0,
                            height: 33.0,
                            child: GeneratedStavroulaSarriWidget(),
                          ),
                          Positioned(
                            left: 58.00537109375,
                            top: 359.0,
                            right: null,
                            bottom: null,
                            width: 364.0,
                            height: 36.0,
                            child: GeneratedNotificationsWidget(),
                          ),
                          Positioned(
                            left: 58.00537109375,
                            top: 403.0,
                            right: null,
                            bottom: null,
                            width: 364.0,
                            height: 36.0,
                            child: GeneratedSettingsWidget(),
                          ),
                          Positioned(
                            left: 58.00537109375,
                            top: 443.0,
                            right: null,
                            bottom: null,
                            width: 364.0,
                            height: 36.0,
                            child: GeneratedHelpWidget(),
                          ),
                          Positioned(
                            left: 58.00537109375,
                            top: 482.0,
                            right: null,
                            bottom: null,
                            width: 361.0,
                            height: 33.0,
                            child: GeneratedTermsofUseWidget(),
                          ),
                          Positioned(
                            left: 18.00537109375,
                            top: 404.0,
                            right: null,
                            bottom: null,
                            width: 26.0,
                            height: 26.0,
                            child: GeneratedFrameWidget1(),
                          ),
                          Positioned(
                            left: 18.00537109375,
                            top: 446.0,
                            right: null,
                            bottom: null,
                            width: 26.0,
                            height: 26.0,
                            child: GeneratedFrameWidget2(),
                          ),
                          Positioned(
                            left: 0.0,
                            top: 395.525390625,
                            right: null,
                            bottom: null,
                            width: 416.01080322265625,
                            height: 0.5,
                            child: GeneratedLine3Widget(),
                          ),
                          Positioned(
                            left: 0.00537109375,
                            top: 439.0,
                            right: null,
                            bottom: null,
                            width: 416.0,
                            height: 0.5,
                            child: GeneratedLine4Widget(),
                          ),
                          Positioned(
                            left: 0.00537109375,
                            top: 480.0,
                            right: null,
                            bottom: null,
                            width: 416.01080322265625,
                            height: 0.5,
                            child: GeneratedLine5Widget(),
                          ),
                          Positioned(
                            left: 1.0,
                            top: 44.0,
                            right: null,
                            bottom: null,
                            width: 421.0,
                            height: 37.0,
                            child: GeneratedWidget(),
                          ),
                          Positioned(
                            left: 18.00537109375,
                            top: 364.0,
                            right: null,
                            bottom: null,
                            width: 26.0,
                            height: 26.0,
                            child: GeneratedNotificationsWidget1(),
                          ),
                          Positioned(
                            left: 57.00537109375,
                            top: 323.0,
                            right: null,
                            bottom: null,
                            width: 361.0,
                            height: 33.0,
                            child: GeneratedChangePaymentInformationWidget(),
                          ),
                          Positioned(
                            left: -1.0,
                            top: 359.525390625,
                            right: null,
                            bottom: null,
                            width: 416.01080322265625,
                            height: 0.5,
                            child: GeneratedLine6Widget(),
                          ),
                          Positioned(
                            left: 158.0,
                            top: 113.0,
                            right: null,
                            bottom: null,
                            width: 100.0,
                            height: 100.0,
                            child: Generated19920Widget(),
                          ),
                          Positioned(
                            left: 20.00537109375,
                            top: 485.0,
                            right: null,
                            bottom: null,
                            width: 25.0,
                            height: 25.0,
                            child: GeneratedDocumenttextoutlineWidget(),
                          ),
                          Positioned(
                            left: 21.0,
                            top: 330.0,
                            right: null,
                            bottom: null,
                            width: 20.0,
                            height: 20.0,
                            child: GeneratedWalletoutlineWidget(),
                          )
                        ]),
                  ))
            ])),
      );
    }));
  }
}
