import 'package:flutter/material.dart';
import 'package:flutterapp/routeeapp/generatedregisterwidget6/generated/GeneratedRegisterWidget7.dart';
import 'package:flutterapp/routeeapp/generatedregisterwidget6/generated/GeneratedProfileiconWidget3.dart';
import 'package:flutterapp/routeeapp/generatedregisterwidget6/generated/GeneratedListWidget31.dart';
import 'package:flutterapp/routeeapp/generatedregisterwidget6/generated/GeneratedListWidget32.dart';
import 'package:flutterapp/helpers/transform/transform.dart';
import 'package:flutterapp/routeeapp/generatedregisterwidget6/generated/GeneratedNavbarWidget5.dart';
import 'package:flutterapp/routeeapp/generatedregisterwidget6/generated/GeneratedNameWidget6.dart';
import 'package:flutterapp/routeeapp/generatedregisterwidget6/generated/GeneratedListWidget30.dart';
import 'package:flutterapp/routeeapp/generatedregisterwidget6/generated/GeneratedRectangle110Widget29.dart';
import 'package:flutterapp/routeeapp/generatedregisterwidget6/generated/GeneratedSurnameWidget3.dart';

/* Frame Register
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedRegisterWidget6 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(child: LayoutBuilder(
        builder: (BuildContext context, BoxConstraints constraints) {
      return SingleChildScrollView(
        scrollDirection: Axis.vertical,
        child: Container(
            height: 901.3642578125,
            child: Stack(children: [
              Container(
                  width: constraints.maxWidth,
                  child: Container(
                    width: 416.7637939453125,
                    height: 901.3642578125,
                    child: Stack(
                        fit: StackFit.expand,
                        alignment: Alignment.center,
                        overflow: Overflow.visible,
                        children: [
                          Positioned(
                            left: 0.0,
                            top: 0.025390625,
                            right: null,
                            bottom: null,
                            width: 416.0,
                            height: 900.0,
                            child: GeneratedRectangle110Widget29(),
                          ),
                          Positioned(
                            left: 0.0,
                            top: 0.0,
                            right: 0.0,
                            bottom: 0.0,
                            width: null,
                            height: null,
                            child: LayoutBuilder(builder: (BuildContext context,
                                BoxConstraints constraints) {
                              final double width =
                                  constraints.maxWidth * 0.9165863387118647;

                              final double height =
                                  constraints.maxHeight * 0.06212804591997591;

                              return Stack(children: [
                                TransformHelper.translate(
                                    x: constraints.maxWidth *
                                        0.04318993219061143,
                                    y: constraints.maxHeight *
                                        0.5569335544969268,
                                    z: 0,
                                    child: Container(
                                      width: width,
                                      height: height,
                                      child: GeneratedListWidget30(),
                                    ))
                              ]);
                            }),
                          ),
                          Positioned(
                            left: 0.0,
                            top: 0.0,
                            right: 0.0,
                            bottom: 0.0,
                            width: null,
                            height: null,
                            child: LayoutBuilder(builder: (BuildContext context,
                                BoxConstraints constraints) {
                              final double width =
                                  constraints.maxWidth * 0.9165863387118647;

                              final double height =
                                  constraints.maxHeight * 0.06212804591997591;

                              return Stack(children: [
                                TransformHelper.translate(
                                    x: constraints.maxWidth *
                                        0.04318993219061143,
                                    y: constraints.maxHeight *
                                        0.4859300734455258,
                                    z: 0,
                                    child: Container(
                                      width: width,
                                      height: height,
                                      child: GeneratedListWidget31(),
                                    ))
                              ]);
                            }),
                          ),
                          Positioned(
                            left: 0.0,
                            top: 0.0,
                            right: 0.0,
                            bottom: 0.0,
                            width: null,
                            height: null,
                            child: LayoutBuilder(builder: (BuildContext context,
                                BoxConstraints constraints) {
                              final double width =
                                  constraints.maxWidth * 0.9165863387118647;

                              final double height =
                                  constraints.maxHeight * 0.06212804591997591;

                              return Stack(children: [
                                TransformHelper.translate(
                                    x: constraints.maxWidth *
                                        0.04318993219061143,
                                    y: constraints.maxHeight *
                                        0.41492659239412477,
                                    z: 0,
                                    child: Container(
                                      width: width,
                                      height: height,
                                      child: GeneratedListWidget32(),
                                    ))
                              ]);
                            }),
                          ),
                          Positioned(
                            left: 0.0,
                            top: 0.0,
                            right: 0.0,
                            bottom: 0.0,
                            width: null,
                            height: null,
                            child: LayoutBuilder(builder: (BuildContext context,
                                BoxConstraints constraints) {
                              final double width =
                                  constraints.maxWidth * 0.9165863387118647;

                              final double height =
                                  constraints.maxHeight * 0.06212804591997591;

                              return Stack(children: [
                                TransformHelper.translate(
                                    x: constraints.maxWidth *
                                        0.04318993219061143,
                                    y: constraints.maxHeight *
                                        0.34392311134272374,
                                    z: 0,
                                    child: Container(
                                      width: width,
                                      height: height,
                                      child: GeneratedSurnameWidget3(),
                                    ))
                              ]);
                            }),
                          ),
                          Positioned(
                            left: 18.0,
                            top: 246.0,
                            right: 16.7637939453125,
                            bottom: null,
                            width: null,
                            height: 56.0,
                            child: GeneratedNameWidget6(),
                          ),
                          Positioned(
                            left: 0.0,
                            top: 0.0,
                            right: 0.0,
                            bottom: 0.0,
                            width: null,
                            height: null,
                            child: LayoutBuilder(builder: (BuildContext context,
                                BoxConstraints constraints) {
                              double percentWidth = 0.23994406772561905;
                              double scaleX =
                                  (constraints.maxWidth * percentWidth) / 100.0;

                              double percentHeight = 0.11094293914281411;
                              double scaleY =
                                  (constraints.maxHeight * percentHeight) /
                                      100.0;

                              return Stack(children: [
                                TransformHelper.translateAndScale(
                                    translateX: constraints.maxWidth *
                                        0.3815110676837343,
                                    translateY: constraints.maxHeight *
                                        0.12869380940566438,
                                    translateZ: 0,
                                    scaleX: scaleX,
                                    scaleY: scaleY,
                                    scaleZ: 1,
                                    child: GeneratedProfileiconWidget3())
                              ]);
                            }),
                          ),
                          Positioned(
                            left: 18.0,
                            top: null,
                            right: 16.7637939453125,
                            bottom: 192.3642578125,
                            width: null,
                            height: 49.0,
                            child: GeneratedRegisterWidget7(),
                          ),
                          Positioned(
                            left: 0.999908447265625,
                            top: 0.0,
                            right: null,
                            bottom: null,
                            width: 416.0000915527344,
                            height: 87.671142578125,
                            child: GeneratedNavbarWidget5(),
                          )
                        ]),
                  ))
            ])),
      );
    }));
  }
}
