import 'package:flutter/material.dart';
import 'package:flutterapp/helpers/svg/svg.dart';

/* Line Line 6
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedLine6Widget3 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: Container(
      width: 416.01080322265625,
      height: 0.5,
      child: SvgWidget(painters: [
        SvgPathPainter.stroke(
          0.5,
          strokeJoin: StrokeJoin.miter,
        )
          ..addPath('M0 0L416.011 0L416.011 -0.5L0 -0.5L0 0Z')
          ..color = Color.fromARGB(255, 196, 196, 196),
      ]),
    ));
  }
}
