import 'package:flutter/material.dart';
import 'package:flutterapp/routeeapp/generatedsearchactivitywidget2/generated/GeneratedImage6Widget2.dart';
import 'package:flutterapp/routeeapp/generatedsearchactivitywidget2/generated/GeneratedMenuBarWidget16.dart';
import 'package:flutterapp/routeeapp/generatedsearchactivitywidget2/generated/GeneratedRectangle110Widget16.dart';
import 'package:flutterapp/routeeapp/generatedsearchactivitywidget2/generated/GeneratedNavbarWidget.dart';
import 'package:flutterapp/routeeapp/generatedsearchactivitywidget2/generated/GeneratedGroupWidget238.dart';
import 'package:flutterapp/routeeapp/generatedsearchactivitywidget2/generated/GeneratedEndPointButtonWidget2.dart';
import 'package:flutterapp/routeeapp/generatedsearchactivitywidget2/generated/GeneratedStartPointButtonWidget9.dart';
import 'package:flutterapp/routeeapp/generatedsearchactivitywidget2/generated/GeneratedStartEndTimeButtonWidget2.dart';
import 'package:flutterapp/routeeapp/generatedsearchactivitywidget2/generated/GeneratedStartTimeIconWidget3.dart';
import 'package:flutterapp/routeeapp/generatedsearchactivitywidget2/generated/GeneratedSearchButtonWidget25.dart';
import 'package:flutterapp/helpers/transform/transform.dart';
import 'package:flutterapp/routeeapp/generatedsearchactivitywidget2/generated/GeneratedSearchButtonWidget24.dart';

/* Frame Search Activity
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedSearchActivityWidget2 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: LayoutBuilder(
          builder: (BuildContext context, BoxConstraints constraints) {
        return SingleChildScrollView(
          scrollDirection: Axis.vertical,
          child: Container(
              height: 901.3642578125,
              child: Stack(children: [
                Container(
                    width: constraints.maxWidth,
                    child: Container(
                      width: 416.7637939453125,
                      height: 901.3642578125,
                      child: Stack(
                          fit: StackFit.expand,
                          alignment: Alignment.center,
                          overflow: Overflow.visible,
                          children: [
                            Positioned(
                              left: 0.0,
                              top: 0.025390625,
                              right: null,
                              bottom: null,
                              width: 416.0,
                              height: 900.0,
                              child: GeneratedRectangle110Widget16(),
                            ),
                            Positioned(
                              left: 1.0,
                              top: 88.0,
                              right: null,
                              bottom: null,
                              width: 416.0,
                              height: 743.0,
                              child: GeneratedImage6Widget2(),
                            ),
                            Positioned(
                              left: 15.0,
                              top: 229.0,
                              right: null,
                              bottom: null,
                              width: 382.0,
                              height: 55.0,
                              child: GeneratedStartEndTimeButtonWidget2(),
                            ),
                            Positioned(
                              left: 15.0,
                              top: 103.0,
                              right: null,
                              bottom: null,
                              width: 382.0,
                              height: 55.0,
                              child: GeneratedStartPointButtonWidget9(),
                            ),
                            Positioned(
                              left: 15.0,
                              top: 166.0,
                              right: null,
                              bottom: null,
                              width: 382.0,
                              height: 55.0,
                              child: GeneratedEndPointButtonWidget2(),
                            ),
                            Positioned(
                              left: 15.0,
                              top: 296.0,
                              right: null,
                              bottom: null,
                              width: 179.0,
                              height: 47.0,
                              child: GeneratedSearchButtonWidget24(),
                            ),
                            Positioned(
                              left: 212.0,
                              top: 296.0,
                              right: null,
                              bottom: null,
                              width: 178.0,
                              height: 47.0,
                              child: GeneratedSearchButtonWidget25(),
                            ),
                            Positioned(
                              left: 36.0,
                              top: 248.0,
                              right: null,
                              bottom: null,
                              width: 20.0,
                              height: 20.0,
                              child: GeneratedStartTimeIconWidget3(),
                            ),
                            Positioned(
                              left: 0.0,
                              top: 0.0,
                              right: 0.0,
                              bottom: 0.0,
                              width: null,
                              height: null,
                              child: LayoutBuilder(builder:
                                  (BuildContext context,
                                      BoxConstraints constraints) {
                                final double width =
                                    constraints.maxWidth * 0.04879796940888877;

                                final double height =
                                    constraints.maxHeight * 0.02218858782856282;

                                return Stack(children: [
                                  TransformHelper.translate(
                                      x: constraints.maxWidth *
                                          0.542273593059899,
                                      y: constraints.maxHeight *
                                          0.27624791846560715,
                                      z: 0,
                                      child: Container(
                                        width: width,
                                        height: height,
                                        child: GeneratedGroupWidget238(),
                                      ))
                                ]);
                              }),
                            ),
                            Positioned(
                              left: -12.0,
                              top: 802.0,
                              right: null,
                              bottom: null,
                              width: 416.1277160644531,
                              height: 89.41358947753906,
                              child: GeneratedMenuBarWidget16(),
                            ),
                            Positioned(
                              left: 0.999908447265625,
                              top: 0.0,
                              right: null,
                              bottom: null,
                              width: 415.7637634277344,
                              height: 87.671142578125,
                              child: GeneratedNavbarWidget(),
                            )
                          ]),
                    ))
              ])),
        );
      }),
    ));
  }
}
