import 'package:flutter/material.dart';
import 'package:flutterapp/routeeapp/generatednavigationactivitywidget/generated/GeneratedStartNavigationLabelWidget1.dart';
import 'package:flutterapp/routeeapp/generatednavigationactivitywidget/generated/GeneratedFrame2Widget.dart';
import 'package:flutterapp/routeeapp/generatednavigationactivitywidget/generated/GeneratedHomeWidget10.dart';
import 'package:flutterapp/routeeapp/generatednavigationactivitywidget/generated/GeneratedBackButtonWidget1.dart';
import 'package:flutterapp/helpers/transform/transform.dart';
import 'package:flutterapp/routeeapp/generatednavigationactivitywidget/generated/GeneratedFavoritesButtonWidget1.dart';

/* Frame Navigation Activity
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedNavigationActivityWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(child: LayoutBuilder(
        builder: (BuildContext context, BoxConstraints constraints) {
      return SingleChildScrollView(
        scrollDirection: Axis.vertical,
        child: Container(
            height: 901.3642578125,
            child: Stack(children: [
              Container(
                  width: constraints.maxWidth,
                  child: Container(
                    width: 416.7637939453125,
                    height: 901.3642578125,
                    child: Stack(
                        fit: StackFit.expand,
                        alignment: Alignment.center,
                        overflow: Overflow.visible,
                        children: [
                          Positioned(
                            left: -7.2354736328125,
                            top: 0.0,
                            right: null,
                            bottom: null,
                            width: 425.7637939453125,
                            height: 900.41357421875,
                            child: GeneratedHomeWidget10(),
                          ),
                          Positioned(
                            left: 2.0,
                            top: 44.0,
                            right: null,
                            bottom: null,
                            width: 419.0,
                            height: 37.0,
                            child: GeneratedStartNavigationLabelWidget1(),
                          ),
                          Positioned(
                            left: 16.0,
                            top: 46.0,
                            right: null,
                            bottom: null,
                            width: 20.0,
                            height: 20.0,
                            child: GeneratedBackButtonWidget1(),
                          ),
                          Positioned(
                            left: 0.0,
                            top: 0.0,
                            right: 0.0,
                            bottom: 0.0,
                            width: null,
                            height: null,
                            child: LayoutBuilder(builder: (BuildContext context,
                                BoxConstraints constraints) {
                              double percentWidth = 0.07511385956711067;
                              double scaleX =
                                  (constraints.maxWidth * percentWidth) /
                                      31.304737091064453;

                              double percentHeight = 0.03328288174284424;
                              double scaleY =
                                  (constraints.maxHeight * percentHeight) /
                                      30.0;

                              return Stack(children: [
                                TransformHelper.translateAndScale(
                                    translateX: constraints.maxWidth *
                                        0.8757958471985094,
                                    translateY: constraints.maxHeight *
                                        0.04532842468610407,
                                    translateZ: 0,
                                    scaleX: scaleX,
                                    scaleY: scaleY,
                                    scaleZ: 1,
                                    child: GeneratedFavoritesButtonWidget1())
                              ]);
                            }),
                          ),
                          Positioned(
                            left: 17.0,
                            top: 102.0,
                            right: null,
                            bottom: null,
                            width: 382.0,
                            height: 710.0,
                            child: GeneratedFrame2Widget(),
                          )
                        ]),
                  ))
            ])),
      );
    }));
  }
}
