import 'package:flutter/material.dart';
import 'package:flutterapp/helpers/transform/transform.dart';
import 'package:flutterapp/routeeapp/generatedticketsharpwidget/generated/GeneratedVectorWidget1213.dart';

/* Frame ticket-sharp
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedTicketsharpWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 166.0,
        height: 163.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  double percentWidth = 0.2195122040897967;
                  double scaleX =
                      (constraints.maxWidth * percentWidth) / 36.43902587890625;

                  double percentHeight = 0.18857143846757574;
                  double scaleY = (constraints.maxHeight * percentHeight) /
                      30.737144470214844;

                  return Stack(children: [
                    TransformHelper.translateAndScale(
                        translateX: constraints.maxWidth * 0.2682926683540804,
                        translateY: constraints.maxHeight * 0.3142856995752253,
                        translateZ: 0,
                        scaleX: scaleX,
                        scaleY: scaleY,
                        scaleZ: 1,
                        child: GeneratedVectorWidget1213())
                  ]);
                }),
              )
            ]),
      ),
    ));
  }
}
