import 'package:flutter/material.dart';
import 'package:flutterapp/routeeapp/generatedloginwidget2/generated/GeneratedNotRegisteredSignUpWidget2.dart';
import 'package:flutterapp/routeeapp/generatedloginwidget2/generated/GeneratedFacebookloginWidget2.dart';
import 'package:flutterapp/routeeapp/generatedloginwidget2/generated/GeneratedRouteeWidget2.dart';
import 'package:flutterapp/routeeapp/generatedloginwidget2/generated/GeneratedNameWidget4.dart';
import 'package:flutterapp/routeeapp/generatedloginwidget2/generated/GeneratedGoogleloginWidget2.dart';
import 'package:flutterapp/helpers/transform/transform.dart';
import 'package:flutterapp/routeeapp/generatedloginwidget2/generated/GeneratedRectangle128Widget10.dart';
import 'package:flutterapp/routeeapp/generatedloginwidget2/generated/GeneratedListWidget26.dart';
import 'package:flutterapp/routeeapp/generatedloginwidget2/generated/GeneratedSigninWidget2.dart';
import 'package:flutterapp/routeeapp/generatedloginwidget2/generated/GeneratedGroupWidget669.dart';
import 'package:flutterapp/routeeapp/generatedloginwidget2/generated/GeneratedForgotpasswordWidget2.dart';
import 'package:flutterapp/routeeapp/generatedloginwidget2/generated/GeneratedGroup191Widget1.dart';

/* Frame Login
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedLoginWidget2 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: Container(
      width: 416.0,
      height: 890.0,
      child: Stack(
          fit: StackFit.expand,
          alignment: Alignment.center,
          overflow: Overflow.visible,
          children: [
            Positioned(
              left: 0.0,
              top: -1.0,
              right: null,
              bottom: null,
              width: 416.0,
              height: 900.0,
              child: GeneratedRectangle128Widget10(),
            ),
            Positioned(
              left: 0.0,
              top: 566.0,
              right: null,
              bottom: null,
              width: 417.0,
              height: 32.0,
              child: GeneratedForgotpasswordWidget2(),
            ),
            Positioned(
              left: 0.0,
              top: 608.0,
              right: null,
              bottom: null,
              width: 417.0,
              height: 32.0,
              child: GeneratedNotRegisteredSignUpWidget2(),
            ),
            Positioned(
              left: 17.0,
              top: null,
              right: 17.0,
              bottom: 353.0,
              width: null,
              height: 49.0,
              child: GeneratedSigninWidget2(),
            ),
            Positioned(
              left: 0.0,
              top: 0.0,
              right: 0.0,
              bottom: 0.0,
              width: null,
              height: null,
              child: LayoutBuilder(
                  builder: (BuildContext context, BoxConstraints constraints) {
                final double width = constraints.maxWidth * 0.9182692307692307;

                final double height = constraints.maxHeight * 0.05;

                return Stack(children: [
                  TransformHelper.translate(
                      x: constraints.maxWidth * 0.040865384615384616,
                      y: constraints.maxHeight * 0.7400000411472963,
                      z: 0,
                      child: Container(
                        width: width,
                        height: height,
                        child: GeneratedFacebookloginWidget2(),
                      ))
                ]);
              }),
            ),
            Positioned(
              left: 0.0,
              top: 0.0,
              right: 0.0,
              bottom: 0.0,
              width: null,
              height: null,
              child: LayoutBuilder(
                  builder: (BuildContext context, BoxConstraints constraints) {
                final double width = constraints.maxWidth * 0.9182692307692307;

                final double height =
                    constraints.maxHeight * 0.062222187170821626;

                return Stack(children: [
                  TransformHelper.translate(
                      x: constraints.maxWidth * 0.040865384615384616,
                      y: constraints.maxHeight * 0.8100000274315309,
                      z: 0,
                      child: Container(
                        width: width,
                        height: height,
                        child: GeneratedGoogleloginWidget2(),
                      ))
                ]);
              }),
            ),
            Positioned(
              left: 17.0,
              top: 352.0,
              right: 17.0,
              bottom: null,
              width: null,
              height: 56.0,
              child: GeneratedNameWidget4(),
            ),
            Positioned(
              left: 0.0,
              top: 0.0,
              right: 0.0,
              bottom: 0.0,
              width: null,
              height: null,
              child: LayoutBuilder(
                  builder: (BuildContext context, BoxConstraints constraints) {
                final double width = constraints.maxWidth * 0.9182692307692307;

                final double height =
                    constraints.maxHeight * 0.062222221460235254;

                return Stack(children: [
                  TransformHelper.translate(
                      x: constraints.maxWidth * 0.040865384615384616,
                      y: constraints.maxHeight * 0.47222221460235253,
                      z: 0,
                      child: Container(
                        width: width,
                        height: height,
                        child: GeneratedListWidget26(),
                      ))
                ]);
              }),
            ),
            Positioned(
              left: 0.0,
              top: 0.0,
              right: 0.0,
              bottom: 0.0,
              width: null,
              height: null,
              child: LayoutBuilder(
                  builder: (BuildContext context, BoxConstraints constraints) {
                final double width = constraints.maxWidth * 0.03942042130690355;

                final double height =
                    constraints.maxHeight * 0.015969231423367276;

                return Stack(children: [
                  TransformHelper.translate(
                      x: constraints.maxWidth * 0.496547845693735,
                      y: constraints.maxHeight * 0.2393258426966292,
                      z: 0,
                      child: Container(
                        width: width,
                        height: height,
                        child: GeneratedGroupWidget669(),
                      ))
                ]);
              }),
            ),
            Positioned(
              left: 0.0,
              top: 0.0,
              right: 0.0,
              bottom: 0.0,
              width: null,
              height: null,
              child: LayoutBuilder(
                  builder: (BuildContext context, BoxConstraints constraints) {
                final double width = constraints.maxWidth * 0.11003630894881028;

                final double height =
                    constraints.maxHeight * 0.054836753245150104;

                return Stack(children: [
                  TransformHelper.translate(
                      x: constraints.maxWidth * 0.44675108102651745,
                      y: constraints.maxHeight * 0.23057669307408707,
                      z: 0,
                      child: Container(
                        width: width,
                        height: height,
                        child: GeneratedGroup191Widget1(),
                      ))
                ]);
              }),
            ),
            Positioned(
              left: 12.0,
              top: 184.0,
              right: null,
              bottom: null,
              width: 363.0,
              height: 139.0,
              child: GeneratedRouteeWidget2(),
            )
          ]),
    ));
  }
}
