import 'package:flutter/material.dart';
import 'package:flutterapp/routeeapp/generatedsearchsresultsactivitywidget8/generated/GeneratedArrivedin20minutesWidget8.dart';
import 'package:flutterapp/helpers/transform/transform.dart';
import 'package:flutterapp/routeeapp/generatedsearchsresultsactivitywidget8/generated/GeneratedGroup8Widget19.dart';
import 'package:flutterapp/routeeapp/generatedsearchsresultsactivitywidget8/generated/GeneratedGroup21Widget10.dart';
import 'package:flutterapp/routeeapp/generatedsearchsresultsactivitywidget8/generated/GeneratedEndTimeIconWidget8.dart';
import 'package:flutterapp/routeeapp/generatedsearchsresultsactivitywidget8/generated/GeneratedPeopleWidget45.dart';
import 'package:flutterapp/routeeapp/generatedsearchsresultsactivitywidget8/generated/GeneratedPeopleWidget48.dart';
import 'package:flutterapp/routeeapp/generatedsearchsresultsactivitywidget8/generated/GeneratedExpectedWidget19.dart';
import 'package:flutterapp/routeeapp/generatedsearchsresultsactivitywidget8/generated/GeneratedRectangle132Widget13.dart';
import 'package:flutterapp/routeeapp/generatedsearchsresultsactivitywidget8/generated/GeneratedGroup22Widget8.dart';
import 'package:flutterapp/routeeapp/generatedsearchsresultsactivitywidget8/generated/GeneratedPeopleWidget47.dart';
import 'package:flutterapp/routeeapp/generatedsearchsresultsactivitywidget8/generated/GeneratedRouteSelectionsWidget31.dart';
import 'package:flutterapp/routeeapp/generatedsearchsresultsactivitywidget8/generated/GeneratedEvery10minutesfromFranzSperrWegWidget8.dart';
import 'package:flutterapp/routeeapp/generatedsearchsresultsactivitywidget8/generated/GeneratedNowWidget20.dart';
import 'package:flutterapp/routeeapp/generatedsearchsresultsactivitywidget8/generated/Generated3Widget8.dart';
import 'package:flutterapp/routeeapp/generatedsearchsresultsactivitywidget8/generated/GeneratedRouteSelectionsWidget29.dart';
import 'package:flutterapp/routeeapp/generatedsearchsresultsactivitywidget8/generated/GeneratedRouteSelectionsWidget30.dart';
import 'package:flutterapp/routeeapp/generatedsearchsresultsactivitywidget8/generated/GeneratedU2Widget8.dart';
import 'package:flutterapp/routeeapp/generatedsearchsresultsactivitywidget8/generated/GeneratedSafestWidget2.dart';
import 'package:flutterapp/routeeapp/generatedsearchsresultsactivitywidget8/generated/GeneratedEndPointButtonWidget10.dart';
import 'package:flutterapp/routeeapp/generatedsearchsresultsactivitywidget8/generated/GeneratedBackButtonWidget76.dart';
import 'package:flutterapp/routeeapp/generatedsearchsresultsactivitywidget8/generated/Generated1Widget9.dart';
import 'package:flutterapp/routeeapp/generatedsearchsresultsactivitywidget8/generated/GeneratedStartTimeIconWidget12.dart';
import 'package:flutterapp/routeeapp/generatedsearchsresultsactivitywidget8/generated/GeneratedBackButtonWidget73.dart';
import 'package:flutterapp/routeeapp/generatedsearchsresultsactivitywidget8/generated/Generated2Widget8.dart';
import 'package:flutterapp/routeeapp/generatedsearchsresultsactivitywidget8/generated/GeneratedArrivedin40minutesWidget8.dart';
import 'package:flutterapp/routeeapp/generatedsearchsresultsactivitywidget8/generated/GeneratedRoutesLabelWidget9.dart';
import 'package:flutterapp/routeeapp/generatedsearchsresultsactivitywidget8/generated/GeneratedStartEndTimeButtonWidget10.dart';
import 'package:flutterapp/routeeapp/generatedsearchsresultsactivitywidget8/generated/GeneratedRouteSelectionsWidget32.dart';
import 'package:flutterapp/routeeapp/generatedsearchsresultsactivitywidget8/generated/GeneratedFastestWidget2.dart';
import 'package:flutterapp/routeeapp/generatedsearchsresultsactivitywidget8/generated/GeneratedPeopleWidget49.dart';
import 'package:flutterapp/routeeapp/generatedsearchsresultsactivitywidget8/generated/GeneratedHomeWidget22.dart';
import 'package:flutterapp/routeeapp/generatedsearchsresultsactivitywidget8/generated/GeneratedStartPointButtonWidget18.dart';

/* Frame Search's Results Activity
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedSearchsResultsActivityWidget8 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: Container(
      width: 443.0,
      height: 886.0,
      child: Stack(
          fit: StackFit.expand,
          alignment: Alignment.center,
          overflow: Overflow.visible,
          children: [
            Positioned(
              left: -12.0,
              top: -11.0,
              right: null,
              bottom: null,
              width: 430.3943786621094,
              height: 907.0,
              child: GeneratedHomeWidget22(),
            ),
            Positioned(
              left: 18.0,
              top: 294.0,
              right: null,
              bottom: null,
              width: 384.0,
              height: 30.0,
              child: GeneratedRouteSelectionsWidget29(),
            ),
            Positioned(
              left: 12.0,
              top: 335.0,
              right: null,
              bottom: null,
              width: 384.0,
              height: 24.0,
              child: GeneratedRouteSelectionsWidget30(),
            ),
            Positioned(
              left: 14.0,
              top: 480.0,
              right: null,
              bottom: null,
              width: 384.0,
              height: 24.0,
              child: GeneratedRouteSelectionsWidget31(),
            ),
            Positioned(
              left: 106.0,
              top: 31.0,
              right: null,
              bottom: null,
              width: 215.0,
              height: 34.0,
              child: GeneratedRoutesLabelWidget9(),
            ),
            Positioned(
              left: 19.0,
              top: 38.0,
              right: null,
              bottom: null,
              width: 20.0,
              height: 20.0,
              child: GeneratedBackButtonWidget73(),
            ),
            Positioned(
              left: 18.0,
              top: 90.0,
              right: null,
              bottom: null,
              width: 382.0,
              height: 55.0,
              child: GeneratedStartPointButtonWidget18(),
            ),
            Positioned(
              left: 18.0,
              top: 153.0,
              right: null,
              bottom: null,
              width: 382.0,
              height: 55.0,
              child: GeneratedEndPointButtonWidget10(),
            ),
            Positioned(
              left: 18.0,
              top: 216.0,
              right: null,
              bottom: null,
              width: 382.0,
              height: 55.0,
              child: GeneratedStartEndTimeButtonWidget10(),
            ),
            Positioned(
              left: 39.0,
              top: 235.0,
              right: null,
              bottom: null,
              width: 20.0,
              height: 20.0,
              child: GeneratedStartTimeIconWidget12(),
            ),
            Positioned(
              left: 0.0,
              top: 0.0,
              right: 0.0,
              bottom: 0.0,
              width: null,
              height: null,
              child: LayoutBuilder(
                  builder: (BuildContext context, BoxConstraints constraints) {
                final double width = constraints.maxWidth * 0.04877039648878386;

                final double height =
                    constraints.maxHeight * 0.022123918038189545;

                return Stack(children: [
                  TransformHelper.translate(
                      x: constraints.maxWidth * 0.5610859270289574,
                      y: constraints.maxHeight * 0.26179774781651205,
                      z: 0,
                      child: Container(
                        width: width,
                        height: height,
                        child: GeneratedEndTimeIconWidget8(),
                      ))
                ]);
              }),
            ),
            Positioned(
              left: 9.0,
              top: 360.0,
              right: null,
              bottom: null,
              width: 401.0,
              height: 105.0,
              child: Generated1Widget9(),
            ),
            Positioned(
              left: 49.75,
              top: 411.69232177734375,
              right: null,
              bottom: null,
              width: 12.75,
              height: 14.692307472229004,
              child: GeneratedBackButtonWidget76(),
            ),
            Positioned(
              left: 6.0,
              top: 507.0,
              right: null,
              bottom: null,
              width: 404.0,
              height: 98.0,
              child: Generated2Widget8(),
            ),
            Positioned(
              left: 176.0,
              top: 535.0,
              right: null,
              bottom: null,
              width: 30.0,
              height: 30.0,
              child: GeneratedPeopleWidget45(),
            ),
            Positioned(
              left: 6.0,
              top: 652.0,
              right: null,
              bottom: null,
              width: 404.0,
              height: 94.44444274902344,
              child: Generated3Widget8(),
            ),
            Positioned(
              left: 13.0,
              top: 442.0,
              right: null,
              bottom: null,
              width: 276.1730651855469,
              height: 20.88888931274414,
              child: GeneratedEvery10minutesfromFranzSperrWegWidget8(),
            ),
            Positioned(
              left: 15.0,
              top: 423.0,
              right: null,
              bottom: null,
              width: 157.0,
              height: 29.0,
              child: GeneratedArrivedin40minutesWidget8(),
            ),
            Positioned(
              left: 221.0,
              top: 363.0,
              right: null,
              bottom: null,
              width: 70.0,
              height: 30.0,
              child: GeneratedExpectedWidget19(),
            ),
            Positioned(
              left: 0.0,
              top: 0.0,
              right: 0.0,
              bottom: 0.0,
              width: null,
              height: null,
              child: LayoutBuilder(
                  builder: (BuildContext context, BoxConstraints constraints) {
                final double width = constraints.maxWidth * 0.04965602625035271;

                final double height =
                    constraints.maxHeight * 0.016705239599499152;

                return Stack(children: [
                  TransformHelper.translate(
                      x: constraints.maxWidth * 0.1606333368787916,
                      y: constraints.maxHeight * 0.6326248478943285,
                      z: 0,
                      child: Container(
                        width: width,
                        height: height,
                        child: GeneratedU2Widget8(),
                      ))
                ]);
              }),
            ),
            Positioned(
              left: 223.0,
              top: 393.0,
              right: null,
              bottom: null,
              width: 30.0,
              height: 32.30769348144531,
              child: GeneratedPeopleWidget47(),
            ),
            Positioned(
              left: 178.0,
              top: 391.0,
              right: null,
              bottom: null,
              width: 30.0,
              height: 32.30769348144531,
              child: GeneratedPeopleWidget48(),
            ),
            Positioned(
              left: 9.0,
              top: 629.0,
              right: null,
              bottom: null,
              width: 384.0,
              height: 24.0,
              child: GeneratedRouteSelectionsWidget32(),
            ),
            Positioned(
              left: 16.0,
              top: 708.0,
              right: null,
              bottom: null,
              width: 151.07691955566406,
              height: 30.254438400268555,
              child: GeneratedArrivedin20minutesWidget8(),
            ),
            Positioned(
              left: 179.0,
              top: 654.0,
              right: null,
              bottom: null,
              width: 70.0,
              height: 30.0,
              child: GeneratedNowWidget20(),
            ),
            Positioned(
              left: 0.0,
              top: 0.0,
              right: 0.0,
              bottom: 0.0,
              width: null,
              height: null,
              child: LayoutBuilder(
                  builder: (BuildContext context, BoxConstraints constraints) {
                final double width = constraints.maxWidth * 0.07541475661990336;

                final double height =
                    constraints.maxHeight * 0.03370773280985468;

                return Stack(children: [
                  TransformHelper.translate(
                      x: constraints.maxWidth * 0.42484350613492877,
                      y: constraints.maxHeight * 0.7657006395051495,
                      z: 0,
                      child: Container(
                        width: width,
                        height: height,
                        child: GeneratedPeopleWidget49(),
                      ))
                ]);
              }),
            ),
            Positioned(
              left: 94.0,
              top: 388.0,
              right: null,
              bottom: null,
              width: 24.461538314819336,
              height: 26.66666603088379,
              child: GeneratedGroup8Widget19(),
            ),
            Positioned(
              left: 225.78271484375,
              top: 317.0,
              right: null,
              bottom: null,
              width: 187.1436309814453,
              height: 98.71129608154297,
              child: GeneratedRectangle132Widget13(),
            ),
            Positioned(
              left: 210.0,
              top: 374.0,
              right: null,
              bottom: null,
              width: 142.0,
              height: 31.0,
              child: GeneratedSafestWidget2(),
            ),
            Positioned(
              left: 349.0,
              top: 335.0,
              right: null,
              bottom: null,
              width: 57.0,
              height: 28.0,
              child: GeneratedGroup22Widget8(),
            ),
            Positioned(
              left: 350.0,
              top: 374.0,
              right: null,
              bottom: null,
              width: 57.0,
              height: 28.0,
              child: GeneratedGroup21Widget10(),
            ),
            Positioned(
              left: 224.0,
              top: 333.0,
              right: null,
              bottom: null,
              width: 111.0,
              height: 32.0,
              child: GeneratedFastestWidget2(),
            )
          ]),
    ));
  }
}
