import 'package:flutter/material.dart';
import 'package:flutterapp/routeeapp/generatedsearchactivitywidget7/generated/GeneratedSearchButtonWidget37.dart';
import 'package:flutterapp/helpers/transform/transform.dart';
import 'package:flutterapp/routeeapp/generatedsearchactivitywidget7/generated/GeneratedImage6Widget7.dart';
import 'package:flutterapp/routeeapp/generatedsearchactivitywidget7/generated/GeneratedGroup18Widget1.dart';
import 'package:flutterapp/routeeapp/generatedsearchactivitywidget7/generated/GeneratedSearchButtonWidget36.dart';
import 'package:flutterapp/routeeapp/generatedsearchactivitywidget7/generated/GeneratedStartEndTimeButtonWidget12.dart';
import 'package:flutterapp/routeeapp/generatedsearchactivitywidget7/generated/GeneratedSafestWidget3.dart';
import 'package:flutterapp/routeeapp/generatedsearchactivitywidget7/generated/GeneratedRectangle135Widget2.dart';
import 'package:flutterapp/routeeapp/generatedsearchactivitywidget7/generated/GeneratedStartTimeIconWidget14.dart';
import 'package:flutterapp/routeeapp/generatedsearchactivitywidget7/generated/GeneratedMenuBarWidget32.dart';
import 'package:flutterapp/routeeapp/generatedsearchactivitywidget7/generated/GeneratedEndPointButtonWidget12.dart';
import 'package:flutterapp/routeeapp/generatedsearchactivitywidget7/generated/GeneratedNavbarWidget7.dart';
import 'package:flutterapp/routeeapp/generatedsearchactivitywidget7/generated/GeneratedStartPointButtonWidget26.dart';
import 'package:flutterapp/routeeapp/generatedsearchactivitywidget7/generated/GeneratedRectangle110Widget36.dart';
import 'package:flutterapp/routeeapp/generatedsearchactivitywidget7/generated/GeneratedFastestWidget3.dart';
import 'package:flutterapp/routeeapp/generatedsearchactivitywidget7/generated/GeneratedGroupWidget776.dart';

/* Frame Search Activity
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedSearchActivityWidget7 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: LayoutBuilder(
          builder: (BuildContext context, BoxConstraints constraints) {
        return SingleChildScrollView(
          scrollDirection: Axis.vertical,
          child: Container(
              height: 901.3647613525391,
              child: Stack(children: [
                Container(
                    width: constraints.maxWidth,
                    child: Container(
                      width: 416.7637939453125,
                      height: 901.3642578125,
                      child: Stack(
                          fit: StackFit.expand,
                          alignment: Alignment.center,
                          overflow: Overflow.visible,
                          children: [
                            Positioned(
                              left: 76.0,
                              top: 268.0,
                              right: null,
                              bottom: null,
                              width: 287.0,
                              height: 44.0,
                              child: GeneratedRectangle135Widget2(),
                            ),
                            Positioned(
                              left: 0.0,
                              top: 0.025390625,
                              right: null,
                              bottom: null,
                              width: 416.0,
                              height: 900.0,
                              child: GeneratedRectangle110Widget36(),
                            ),
                            Positioned(
                              left: -37.0,
                              top: 0.0,
                              right: null,
                              bottom: null,
                              width: 776.0,
                              height: 831.0,
                              child: GeneratedImage6Widget7(),
                            ),
                            Positioned(
                              left: 15.0,
                              top: 229.0,
                              right: null,
                              bottom: null,
                              width: 382.0,
                              height: 55.0,
                              child: GeneratedStartEndTimeButtonWidget12(),
                            ),
                            Positioned(
                              left: 15.0,
                              top: 103.0,
                              right: null,
                              bottom: null,
                              width: 382.0,
                              height: 55.0,
                              child: GeneratedStartPointButtonWidget26(),
                            ),
                            Positioned(
                              left: 15.0,
                              top: 166.0,
                              right: null,
                              bottom: null,
                              width: 382.0,
                              height: 55.0,
                              child: GeneratedEndPointButtonWidget12(),
                            ),
                            Positioned(
                              left: 15.0,
                              top: 296.0,
                              right: null,
                              bottom: null,
                              width: 179.0,
                              height: 47.0,
                              child: GeneratedSearchButtonWidget36(),
                            ),
                            Positioned(
                              left: 212.0,
                              top: 296.0,
                              right: null,
                              bottom: null,
                              width: 178.0,
                              height: 47.0,
                              child: GeneratedSearchButtonWidget37(),
                            ),
                            Positioned(
                              left: 36.0,
                              top: 248.0,
                              right: null,
                              bottom: null,
                              width: 20.0,
                              height: 20.0,
                              child: GeneratedStartTimeIconWidget14(),
                            ),
                            Positioned(
                              left: 0.0,
                              top: 0.0,
                              right: 0.0,
                              bottom: 0.0,
                              width: null,
                              height: null,
                              child: LayoutBuilder(builder:
                                  (BuildContext context,
                                      BoxConstraints constraints) {
                                final double width =
                                    constraints.maxWidth * 0.04879796940888877;

                                final double height =
                                    constraints.maxHeight * 0.02218858782856282;

                                return Stack(children: [
                                  TransformHelper.translate(
                                      x: constraints.maxWidth *
                                          0.542273593059899,
                                      y: constraints.maxHeight *
                                          0.27624791846560715,
                                      z: 0,
                                      child: Container(
                                        width: width,
                                        height: height,
                                        child: GeneratedGroupWidget776(),
                                      ))
                                ]);
                              }),
                            ),
                            Positioned(
                              left: 0.5107421875,
                              top: 811.951171875,
                              right: null,
                              bottom: null,
                              width: 416.1277160644531,
                              height: 89.41358947753906,
                              child: GeneratedMenuBarWidget32(),
                            ),
                            Positioned(
                              left: 0.999908447265625,
                              top: 0.0,
                              right: null,
                              bottom: null,
                              width: 415.7637634277344,
                              height: 87.671142578125,
                              child: GeneratedNavbarWidget7(),
                            ),
                            Positioned(
                              left: 0.0,
                              top: -1.0,
                              right: null,
                              bottom: null,
                              width: 417.0,
                              height: 901.0,
                              child: GeneratedGroup18Widget1(),
                            ),
                            Positioned(
                              left: 207.0,
                              top: 343.0,
                              right: null,
                              bottom: null,
                              width: 142.0,
                              height: 42.0,
                              child: GeneratedSafestWidget3(),
                            ),
                            Positioned(
                              left: 93.0,
                              top: 342.0,
                              right: null,
                              bottom: null,
                              width: 111.0,
                              height: 32.0,
                              child: GeneratedFastestWidget3(),
                            )
                          ]),
                    ))
              ])),
        );
      }),
    ));
  }
}
