import 'package:flutter/material.dart';
import 'package:flutterapp/routeeapp/generatedsearchactivitywidget6/generated/GeneratedGroupWidget766.dart';
import 'package:flutterapp/helpers/transform/transform.dart';
import 'package:flutterapp/routeeapp/generatedsearchactivitywidget6/generated/GeneratedStartTimeIconWidget13.dart';
import 'package:flutterapp/routeeapp/generatedsearchactivitywidget6/generated/GeneratedRectangle110Widget35.dart';
import 'package:flutterapp/routeeapp/generatedsearchactivitywidget6/generated/GeneratedSearchButtonWidget34.dart';
import 'package:flutterapp/routeeapp/generatedsearchactivitywidget6/generated/GeneratedMenuBarWidget31.dart';
import 'package:flutterapp/routeeapp/generatedsearchactivitywidget6/generated/GeneratedNavbarWidget6.dart';
import 'package:flutterapp/routeeapp/generatedsearchactivitywidget6/generated/GeneratedSearchButtonWidget35.dart';
import 'package:flutterapp/routeeapp/generatedsearchactivitywidget6/generated/GeneratedImage6Widget6.dart';
import 'package:flutterapp/routeeapp/generatedsearchactivitywidget6/generated/GeneratedStartPointButtonWidget25.dart';
import 'package:flutterapp/routeeapp/generatedsearchactivitywidget6/generated/GeneratedEndPointButtonWidget11.dart';
import 'package:flutterapp/routeeapp/generatedsearchactivitywidget6/generated/GeneratedStartEndTimeButtonWidget11.dart';

/* Frame Search Activity
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedSearchActivityWidget6 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: LayoutBuilder(
          builder: (BuildContext context, BoxConstraints constraints) {
        return SingleChildScrollView(
          scrollDirection: Axis.vertical,
          child: Container(
              height: 901.3642578125,
              child: Stack(children: [
                Container(
                    width: constraints.maxWidth,
                    child: Container(
                      width: 416.7637939453125,
                      height: 901.3642578125,
                      child: Stack(
                          fit: StackFit.expand,
                          alignment: Alignment.center,
                          overflow: Overflow.visible,
                          children: [
                            Positioned(
                              left: 0.0,
                              top: 0.025390625,
                              right: null,
                              bottom: null,
                              width: 416.0,
                              height: 900.0,
                              child: GeneratedRectangle110Widget35(),
                            ),
                            Positioned(
                              left: 1.0,
                              top: 88.0,
                              right: null,
                              bottom: null,
                              width: 416.0,
                              height: 743.0,
                              child: GeneratedImage6Widget6(),
                            ),
                            Positioned(
                              left: 15.0,
                              top: 229.0,
                              right: null,
                              bottom: null,
                              width: 382.0,
                              height: 55.0,
                              child: GeneratedStartEndTimeButtonWidget11(),
                            ),
                            Positioned(
                              left: 15.0,
                              top: 103.0,
                              right: null,
                              bottom: null,
                              width: 382.0,
                              height: 55.0,
                              child: GeneratedStartPointButtonWidget25(),
                            ),
                            Positioned(
                              left: 15.0,
                              top: 166.0,
                              right: null,
                              bottom: null,
                              width: 382.0,
                              height: 55.0,
                              child: GeneratedEndPointButtonWidget11(),
                            ),
                            Positioned(
                              left: 15.0,
                              top: 296.0,
                              right: null,
                              bottom: null,
                              width: 179.0,
                              height: 47.0,
                              child: GeneratedSearchButtonWidget34(),
                            ),
                            Positioned(
                              left: 209.0,
                              top: 296.0,
                              right: null,
                              bottom: null,
                              width: 178.0,
                              height: 47.0,
                              child: GeneratedSearchButtonWidget35(),
                            ),
                            Positioned(
                              left: 36.0,
                              top: 248.0,
                              right: null,
                              bottom: null,
                              width: 20.0,
                              height: 20.0,
                              child: GeneratedStartTimeIconWidget13(),
                            ),
                            Positioned(
                              left: 0.0,
                              top: 0.0,
                              right: 0.0,
                              bottom: 0.0,
                              width: null,
                              height: null,
                              child: LayoutBuilder(builder:
                                  (BuildContext context,
                                      BoxConstraints constraints) {
                                final double width =
                                    constraints.maxWidth * 0.04879796940888877;

                                final double height =
                                    constraints.maxHeight * 0.02218858782856282;

                                return Stack(children: [
                                  TransformHelper.translate(
                                      x: constraints.maxWidth *
                                          0.5350752710281305,
                                      y: constraints.maxHeight *
                                          0.2740290596827509,
                                      z: 0,
                                      child: Container(
                                        width: width,
                                        height: height,
                                        child: GeneratedGroupWidget766(),
                                      ))
                                ]);
                              }),
                            ),
                            Positioned(
                              left: -10.0,
                              top: 804.0,
                              right: null,
                              bottom: null,
                              width: 416.1277160644531,
                              height: 89.41358947753906,
                              child: GeneratedMenuBarWidget31(),
                            ),
                            Positioned(
                              left: 0.999908447265625,
                              top: 0.0,
                              right: null,
                              bottom: null,
                              width: 415.7637634277344,
                              height: 87.671142578125,
                              child: GeneratedNavbarWidget6(),
                            )
                          ]),
                    ))
              ])),
        );
      }),
    ));
  }
}
