import 'package:flutter/material.dart';
import 'package:flutterapp/routeeapp/generatedstartendtimebuttonwidget3/generated/GeneratedArrivedbyWidget1.dart';
import 'package:flutterapp/routeeapp/generatedstartendtimebuttonwidget3/generated/GeneratedRectangle130Widget1.dart';
import 'package:flutterapp/routeeapp/generatedstartendtimebuttonwidget3/generated/GeneratedDepartatWidget1.dart';

/* Group Start-End Time Button
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedStartEndTimeButtonWidget3 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: Container(
      width: 382.0,
      height: 55.0,
      decoration: BoxDecoration(
        boxShadow: [
          BoxShadow(
            color: Color.fromARGB(63, 0, 0, 0),
            offset: Offset(0.0, 4.0),
            blurRadius: 4.0,
          )
        ],
      ),
      child: Stack(
          fit: StackFit.expand,
          alignment: Alignment.center,
          overflow: Overflow.visible,
          children: [
            Positioned(
              left: 0.0,
              top: 0.0,
              right: null,
              bottom: null,
              width: 382.0,
              height: 55.0,
              child: GeneratedRectangle130Widget1(),
            ),
            Positioned(
              left: 39.0,
              top: 21.0,
              right: null,
              bottom: null,
              width: 109.0,
              height: 23.0,
              child: GeneratedDepartatWidget1(),
            ),
            Positioned(
              left: 233.0,
              top: 21.0,
              right: null,
              bottom: null,
              width: 78.0,
              height: 23.0,
              child: GeneratedArrivedbyWidget1(),
            )
          ]),
    ));
  }
}
