import 'package:flutter/material.dart';
import 'package:flutterapp/routeeapp/generatedsearchactivitywidget10/generated/GeneratedGroupWidget824.dart';
import 'package:flutterapp/routeeapp/generatedsearchactivitywidget10/generated/GeneratedStartEndTimeButtonWidget15.dart';
import 'package:flutterapp/routeeapp/generatedsearchactivitywidget10/generated/GeneratedEndPointButtonWidget15.dart';
import 'package:flutterapp/routeeapp/generatedsearchactivitywidget10/generated/GeneratedStartTimeIconWidget20.dart';
import 'package:flutterapp/routeeapp/generatedsearchactivitywidget10/generated/GeneratedStartPointButtonWidget32.dart';
import 'package:flutterapp/routeeapp/generatedsearchactivitywidget10/generated/GeneratedNavbarWidget10.dart';
import 'package:flutterapp/helpers/transform/transform.dart';
import 'package:flutterapp/routeeapp/generatedsearchactivitywidget10/generated/GeneratedSearchButtonWidget55.dart';
import 'package:flutterapp/routeeapp/generatedsearchactivitywidget10/generated/GeneratedRectangle142Widget5.dart';
import 'package:flutterapp/routeeapp/generatedsearchactivitywidget10/generated/GeneratedSearchButtonWidget54.dart';
import 'package:flutterapp/routeeapp/generatedsearchactivitywidget10/generated/GeneratedMenuBarWidget35.dart';
import 'package:flutterapp/routeeapp/generatedsearchactivitywidget10/generated/GeneratedGroup18Widget6.dart';
import 'package:flutterapp/routeeapp/generatedsearchactivitywidget10/generated/GeneratedImage6Widget10.dart';
import 'package:flutterapp/routeeapp/generatedsearchactivitywidget10/generated/GeneratedRectangle110Widget39.dart';

/* Frame Search Activity
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedSearchActivityWidget10 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: LayoutBuilder(
          builder: (BuildContext context, BoxConstraints constraints) {
        return SingleChildScrollView(
          scrollDirection: Axis.vertical,
          child: Container(
              height: 904.9999389648438,
              child: Stack(children: [
                Container(
                    width: constraints.maxWidth,
                    child: Container(
                      width: 416.7637939453125,
                      height: 901.3642578125,
                      child: Stack(
                          fit: StackFit.expand,
                          alignment: Alignment.center,
                          overflow: Overflow.visible,
                          children: [
                            Positioned(
                              left: 0.0,
                              top: 0.025390625,
                              right: null,
                              bottom: null,
                              width: 416.0,
                              height: 900.0,
                              child: GeneratedRectangle110Widget39(),
                            ),
                            Positioned(
                              left: -37.0,
                              top: 0.0,
                              right: null,
                              bottom: null,
                              width: 776.0,
                              height: 831.0,
                              child: GeneratedImage6Widget10(),
                            ),
                            Positioned(
                              left: 15.0,
                              top: 229.0,
                              right: null,
                              bottom: null,
                              width: 382.0,
                              height: 55.0,
                              child: GeneratedStartEndTimeButtonWidget15(),
                            ),
                            Positioned(
                              left: 15.0,
                              top: 103.0,
                              right: null,
                              bottom: null,
                              width: 382.0,
                              height: 55.0,
                              child: GeneratedStartPointButtonWidget32(),
                            ),
                            Positioned(
                              left: 15.0,
                              top: 166.0,
                              right: null,
                              bottom: null,
                              width: 382.0,
                              height: 55.0,
                              child: GeneratedEndPointButtonWidget15(),
                            ),
                            Positioned(
                              left: 15.0,
                              top: 296.0,
                              right: null,
                              bottom: null,
                              width: 179.0,
                              height: 47.0,
                              child: GeneratedSearchButtonWidget54(),
                            ),
                            Positioned(
                              left: 212.0,
                              top: 296.0,
                              right: null,
                              bottom: null,
                              width: 178.0,
                              height: 47.0,
                              child: GeneratedSearchButtonWidget55(),
                            ),
                            Positioned(
                              left: 36.0,
                              top: 248.0,
                              right: null,
                              bottom: null,
                              width: 20.0,
                              height: 20.0,
                              child: GeneratedStartTimeIconWidget20(),
                            ),
                            Positioned(
                              left: 0.0,
                              top: 0.0,
                              right: 0.0,
                              bottom: 0.0,
                              width: null,
                              height: null,
                              child: LayoutBuilder(builder:
                                  (BuildContext context,
                                      BoxConstraints constraints) {
                                final double width =
                                    constraints.maxWidth * 0.04879796940888877;

                                final double height =
                                    constraints.maxHeight * 0.02218858782856282;

                                return Stack(children: [
                                  TransformHelper.translate(
                                      x: constraints.maxWidth *
                                          0.542273593059899,
                                      y: constraints.maxHeight *
                                          0.27624791846560715,
                                      z: 0,
                                      child: Container(
                                        width: width,
                                        height: height,
                                        child: GeneratedGroupWidget824(),
                                      ))
                                ]);
                              }),
                            ),
                            Positioned(
                              left: 1.0,
                              top: 812.0,
                              right: null,
                              bottom: null,
                              width: 416.0,
                              height: 88.0,
                              child: GeneratedMenuBarWidget35(),
                            ),
                            Positioned(
                              left: 0.999908447265625,
                              top: 0.0,
                              right: null,
                              bottom: null,
                              width: 415.7637634277344,
                              height: 87.671142578125,
                              child: GeneratedNavbarWidget10(),
                            ),
                            Positioned(
                              left: -3.0,
                              top: 0.0,
                              right: null,
                              bottom: null,
                              width: 419.0,
                              height: 904.9999389648438,
                              child: GeneratedRectangle142Widget5(),
                            ),
                            Positioned(
                              left: 46.0,
                              top: 158.0,
                              right: null,
                              bottom: null,
                              width: 337.1462097167969,
                              height: 337.0,
                              child: GeneratedGroup18Widget6(),
                            )
                          ]),
                    ))
              ])),
        );
      }),
    ));
  }
}
