import 'package:flutter/material.dart';
import 'package:flutterapp/routeeapp/generatedsearchsresultsactivitywidget3/generated/GeneratedVectorWidget434.dart';
import 'package:flutterapp/routeeapp/generatedsearchsresultsactivitywidget3/generated/GeneratedStartPointButtonWidget12.dart';
import 'package:flutterapp/routeeapp/generatedsearchsresultsactivitywidget3/generated/GeneratedArrivedin20minutesWidget2.dart';
import 'package:flutterapp/routeeapp/generatedsearchsresultsactivitywidget3/generated/GeneratedGroup8Widget4.dart';
import 'package:flutterapp/routeeapp/generatedsearchsresultsactivitywidget3/generated/GeneratedBackButtonWidget32.dart';
import 'package:flutterapp/routeeapp/generatedsearchsresultsactivitywidget3/generated/GeneratedPeopleWidget12.dart';
import 'package:flutterapp/routeeapp/generatedsearchsresultsactivitywidget3/generated/GeneratedPeopleWidget13.dart';
import 'package:flutterapp/routeeapp/generatedsearchsresultsactivitywidget3/generated/GeneratedEndPointButtonWidget4.dart';
import 'package:flutterapp/routeeapp/generatedsearchsresultsactivitywidget3/generated/GeneratedRouteSelectionsWidget8.dart';
import 'package:flutterapp/routeeapp/generatedsearchsresultsactivitywidget3/generated/GeneratedRouteSelectionsWidget9.dart';
import 'package:flutterapp/routeeapp/generatedsearchsresultsactivitywidget3/generated/GeneratedPeopleWidget9.dart';
import 'package:flutterapp/helpers/transform/transform.dart';
import 'package:flutterapp/routeeapp/generatedsearchsresultsactivitywidget3/generated/GeneratedStartTimeIconWidget6.dart';
import 'package:flutterapp/routeeapp/generatedsearchsresultsactivitywidget3/generated/Generated2Widget2.dart';
import 'package:flutterapp/routeeapp/generatedsearchsresultsactivitywidget3/generated/Generated3Widget2.dart';
import 'package:flutterapp/routeeapp/generatedsearchsresultsactivitywidget3/generated/GeneratedEndPointIconWidget2.dart';
import 'package:flutterapp/routeeapp/generatedsearchsresultsactivitywidget3/generated/GeneratedRoutesLabelWidget3.dart';
import 'package:flutterapp/routeeapp/generatedsearchsresultsactivitywidget3/generated/GeneratedBackButtonWidget25.dart';
import 'package:flutterapp/routeeapp/generatedsearchsresultsactivitywidget3/generated/GeneratedPeopleWidget6.dart';
import 'package:flutterapp/routeeapp/generatedsearchsresultsactivitywidget3/generated/Generated1Widget3.dart';
import 'package:flutterapp/routeeapp/generatedsearchsresultsactivitywidget3/generated/GeneratedStartEndTimeButtonWidget4.dart';
import 'package:flutterapp/routeeapp/generatedsearchsresultsactivitywidget3/generated/GeneratedHomeWidget17.dart';
import 'package:flutterapp/routeeapp/generatedsearchsresultsactivitywidget3/generated/GeneratedRouteSelectionsWidget10.dart';
import 'package:flutterapp/routeeapp/generatedsearchsresultsactivitywidget3/generated/GeneratedRouteSelectionsWidget11.dart';

/* Frame Search's Results Activity
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedSearchsResultsActivityWidget3 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: Container(
      width: 413.0,
      height: 876.0,
      child: Stack(
          fit: StackFit.expand,
          alignment: Alignment.center,
          overflow: Overflow.visible,
          children: [
            Positioned(
              left: -7.0,
              top: -4.191680908203125,
              right: null,
              bottom: null,
              width: 419.0,
              height: 880.5601196289062,
              child: GeneratedHomeWidget17(),
            ),
            Positioned(
              left: 0.0,
              top: 0.0,
              right: 0.0,
              bottom: 0.0,
              width: null,
              height: null,
              child: LayoutBuilder(
                  builder: (BuildContext context, BoxConstraints constraints) {
                double percentWidth = 0.058115592014414345;
                double scaleX =
                    (constraints.maxWidth * percentWidth) / 24.001739501953125;

                double percentHeight = 0.010770545158212044;
                double scaleY =
                    (constraints.maxHeight * percentHeight) / 9.43499755859375;

                return Stack(children: [
                  TransformHelper.translateAndScale(
                      translateX: constraints.maxWidth * 0.7433035714285714,
                      translateY: constraints.maxHeight * 0.17385054287845142,
                      translateZ: 0,
                      scaleX: scaleX,
                      scaleY: scaleY,
                      scaleZ: 1,
                      child: GeneratedVectorWidget434())
                ]);
              }),
            ),
            Positioned(
              left: 103.0,
              top: 29.0,
              right: null,
              bottom: null,
              width: 215.0,
              height: 34.0,
              child: GeneratedRoutesLabelWidget3(),
            ),
            Positioned(
              left: 10.0,
              top: 34.0,
              right: null,
              bottom: null,
              width: 20.0,
              height: 20.0,
              child: GeneratedBackButtonWidget25(),
            ),
            Positioned(
              left: 24.0,
              top: 93.0,
              right: null,
              bottom: null,
              width: 365.0,
              height: 49.0,
              child: GeneratedStartPointButtonWidget12(),
            ),
            Positioned(
              left: 23.0,
              top: 153.0,
              right: null,
              bottom: null,
              width: 367.0,
              height: 49.0,
              child: GeneratedEndPointButtonWidget4(),
            ),
            Positioned(
              left: 0.0,
              top: 0.0,
              right: 0.0,
              bottom: 0.0,
              width: null,
              height: null,
              child: LayoutBuilder(
                  builder: (BuildContext context, BoxConstraints constraints) {
                final double width = constraints.maxWidth * 0.0574999848520496;

                final double height =
                    constraints.maxHeight * 0.021689497716894976;

                return Stack(children: [
                  TransformHelper.translate(
                      x: constraints.maxWidth * 0.10765744410184624,
                      y: constraints.maxHeight * 0.1917808219178082,
                      z: 0,
                      child: Container(
                        width: width,
                        height: height,
                        child: GeneratedEndPointIconWidget2(),
                      ))
                ]);
              }),
            ),
            Positioned(
              left: 22.0,
              top: 213.0,
              right: null,
              bottom: null,
              width: 363.0,
              height: 49.0,
              child: GeneratedStartEndTimeButtonWidget4(),
            ),
            Positioned(
              left: 46.0,
              top: 227.0,
              right: null,
              bottom: null,
              width: 20.0,
              height: 20.0,
              child: GeneratedStartTimeIconWidget6(),
            ),
            Positioned(
              left: 9.0,
              top: 297.0,
              right: null,
              bottom: null,
              width: 384.0,
              height: 30.0,
              child: GeneratedRouteSelectionsWidget8(),
            ),
            Positioned(
              left: 9.0,
              top: 341.0,
              right: null,
              bottom: null,
              width: 384.0,
              height: 24.0,
              child: GeneratedRouteSelectionsWidget9(),
            ),
            Positioned(
              left: 0.0,
              top: 1399.7003173828125,
              right: null,
              bottom: null,
              width: 384.0,
              height: 24.0,
              child: GeneratedRouteSelectionsWidget10(),
            ),
            Positioned(
              left: 0.0,
              top: 1421.7003173828125,
              right: null,
              bottom: null,
              width: 30.0,
              height: 30.0,
              child: GeneratedPeopleWidget6(),
            ),
            Positioned(
              left: 11.0,
              top: 500.0,
              right: null,
              bottom: null,
              width: 392.0,
              height: 88.0,
              child: Generated2Widget2(),
            ),
            Positioned(
              left: 91.0,
              top: 517.0,
              right: null,
              bottom: null,
              width: 35.0,
              height: 26.0,
              child: GeneratedGroup8Widget4(),
            ),
            Positioned(
              left: 0.0,
              top: 1559.61181640625,
              right: null,
              bottom: null,
              width: 384.0,
              height: 24.0,
              child: GeneratedRouteSelectionsWidget11(),
            ),
            Positioned(
              left: 0.0,
              top: 1581.61181640625,
              right: null,
              bottom: null,
              width: 30.0,
              height: 32.30769348144531,
              child: GeneratedPeopleWidget9(),
            ),
            Positioned(
              left: 11.0,
              top: 310.1768798828125,
              right: null,
              bottom: null,
              width: 392.0,
              height: 412.63934326171875,
              child: Generated3Widget2(),
            ),
            Positioned(
              left: 10.0,
              top: 363.0,
              right: null,
              bottom: null,
              width: 392.0,
              height: 88.4014663696289,
              child: Generated1Widget3(),
            ),
            Positioned(
              left: 20.0,
              top: 419.0,
              right: null,
              bottom: null,
              width: 153.62213134765625,
              height: 25.787940979003906,
              child: GeneratedArrivedin20minutesWidget2(),
            ),
            Positioned(
              left: 37.75,
              top: 412.69232177734375,
              right: null,
              bottom: null,
              width: 12.75,
              height: 14.692307472229004,
              child: GeneratedBackButtonWidget32(),
            ),
            Positioned(
              left: 209.0,
              top: 391.0,
              right: null,
              bottom: null,
              width: 30.0,
              height: 30.0,
              child: GeneratedPeopleWidget12(),
            ),
            Positioned(
              left: 0.0,
              top: 0.0,
              right: 0.0,
              bottom: 0.0,
              width: null,
              height: null,
              child: LayoutBuilder(
                  builder: (BuildContext context, BoxConstraints constraints) {
                final double width = constraints.maxWidth * 0.08793965263459065;

                final double height =
                    constraints.maxHeight * 0.030821917808219176;

                return Stack(children: [
                  TransformHelper.translate(
                      x: constraints.maxWidth * 0.3768844419761085,
                      y: constraints.maxHeight * 0.4520547945205479,
                      z: 0,
                      child: Container(
                        width: width,
                        height: height,
                        child: GeneratedPeopleWidget13(),
                      ))
                ]);
              }),
            )
          ]),
    ));
  }
}
