import 'package:flutter/material.dart';
import 'package:flutterapp/routeeapp/generatedsearchsresultsactivitywidget5/generated/GeneratedBackButtonWidget43.dart';
import 'package:flutterapp/routeeapp/generatedsearchsresultsactivitywidget5/generated/GeneratedPeopleWidget25.dart';
import 'package:flutterapp/routeeapp/generatedsearchsresultsactivitywidget5/generated/GeneratedRectangle132Widget7.dart';
import 'package:flutterapp/routeeapp/generatedsearchsresultsactivitywidget5/generated/GeneratedRouteSelectionsWidget16.dart';
import 'package:flutterapp/routeeapp/generatedsearchsresultsactivitywidget5/generated/GeneratedSafestWidget.dart';
import 'package:flutterapp/routeeapp/generatedsearchsresultsactivitywidget5/generated/GeneratedBackButtonWidget41.dart';
import 'package:flutterapp/routeeapp/generatedsearchsresultsactivitywidget5/generated/GeneratedStartTimeIconWidget8.dart';
import 'package:flutterapp/routeeapp/generatedsearchsresultsactivitywidget5/generated/GeneratedRouteSelectionsWidget18.dart';
import 'package:flutterapp/routeeapp/generatedsearchsresultsactivitywidget5/generated/GeneratedFastestWidget.dart';
import 'package:flutterapp/routeeapp/generatedsearchsresultsactivitywidget5/generated/Generated2Widget4.dart';
import 'package:flutterapp/routeeapp/generatedsearchsresultsactivitywidget5/generated/GeneratedU2Widget4.dart';
import 'package:flutterapp/routeeapp/generatedsearchsresultsactivitywidget5/generated/GeneratedGroup21Widget7.dart';
import 'package:flutterapp/routeeapp/generatedsearchsresultsactivitywidget5/generated/GeneratedEndPointButtonWidget6.dart';
import 'package:flutterapp/routeeapp/generatedsearchsresultsactivitywidget5/generated/GeneratedGroup22Widget5.dart';
import 'package:flutterapp/routeeapp/generatedsearchsresultsactivitywidget5/generated/GeneratedPeopleWidget23.dart';
import 'package:flutterapp/routeeapp/generatedsearchsresultsactivitywidget5/generated/GeneratedRouteSelectionsWidget19.dart';
import 'package:flutterapp/routeeapp/generatedsearchsresultsactivitywidget5/generated/GeneratedHomeWidget19.dart';
import 'package:flutterapp/routeeapp/generatedsearchsresultsactivitywidget5/generated/GeneratedStartEndTimeButtonWidget6.dart';
import 'package:flutterapp/routeeapp/generatedsearchsresultsactivitywidget5/generated/GeneratedPeopleWidget21.dart';
import 'package:flutterapp/routeeapp/generatedsearchsresultsactivitywidget5/generated/GeneratedStartPointButtonWidget14.dart';
import 'package:flutterapp/routeeapp/generatedsearchsresultsactivitywidget5/generated/Generated3Widget4.dart';
import 'package:flutterapp/routeeapp/generatedsearchsresultsactivitywidget5/generated/GeneratedRouteSelectionsWidget17.dart';
import 'package:flutterapp/routeeapp/generatedsearchsresultsactivitywidget5/generated/GeneratedEndTimeIconWidget4.dart';
import 'package:flutterapp/helpers/transform/transform.dart';
import 'package:flutterapp/routeeapp/generatedsearchsresultsactivitywidget5/generated/GeneratedVectorWidget568.dart';
import 'package:flutterapp/routeeapp/generatedsearchsresultsactivitywidget5/generated/GeneratedPeopleWidget24.dart';
import 'package:flutterapp/routeeapp/generatedsearchsresultsactivitywidget5/generated/Generated1Widget5.dart';
import 'package:flutterapp/routeeapp/generatedsearchsresultsactivitywidget5/generated/GeneratedRoutesLabelWidget5.dart';

/* Frame Search's Results Activity
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedSearchsResultsActivityWidget5 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(child: LayoutBuilder(
        builder: (BuildContext context, BoxConstraints constraints) {
      return SingleChildScrollView(
        scrollDirection: Axis.vertical,
        child: Container(
            height: 905.0,
            child: Stack(children: [
              Container(
                  width: constraints.maxWidth,
                  child: Container(
                    width: 430.0,
                    height: 905.0,
                    child: Stack(
                        fit: StackFit.expand,
                        alignment: Alignment.center,
                        overflow: Overflow.visible,
                        children: [
                          Positioned(
                            left: -6.0,
                            top: -8.0,
                            right: null,
                            bottom: null,
                            width: 436.0,
                            height: 904.0,
                            child: GeneratedHomeWidget19(),
                          ),
                          Positioned(
                            left: 0.0,
                            top: 0.0,
                            right: 0.0,
                            bottom: 0.0,
                            width: null,
                            height: null,
                            child: LayoutBuilder(builder: (BuildContext context,
                                BoxConstraints constraints) {
                              double percentWidth = 0.05890534423118414;
                              double scaleX =
                                  (constraints.maxWidth * percentWidth) /
                                      25.32929801940918;

                              double percentHeight = 0.02053536051544695;
                              double scaleY =
                                  (constraints.maxHeight * percentHeight) /
                                      18.584501266479492;

                              return Stack(children: [
                                TransformHelper.translateAndScale(
                                    translateX: constraints.maxWidth *
                                        0.8923516561818677,
                                    translateY: constraints.maxHeight *
                                        0.33861144682320443,
                                    translateZ: 0,
                                    scaleX: scaleX,
                                    scaleY: scaleY,
                                    scaleZ: 1,
                                    child: GeneratedVectorWidget568())
                              ]);
                            }),
                          ),
                          Positioned(
                            left: 18.0,
                            top: 294.0,
                            right: null,
                            bottom: null,
                            width: 384.0,
                            height: 30.0,
                            child: GeneratedRouteSelectionsWidget16(),
                          ),
                          Positioned(
                            left: 12.0,
                            top: 335.0,
                            right: null,
                            bottom: null,
                            width: 384.0,
                            height: 24.0,
                            child: GeneratedRouteSelectionsWidget17(),
                          ),
                          Positioned(
                            left: 14.0,
                            top: 480.0,
                            right: null,
                            bottom: null,
                            width: 384.0,
                            height: 24.0,
                            child: GeneratedRouteSelectionsWidget18(),
                          ),
                          Positioned(
                            left: 106.0,
                            top: 31.0,
                            right: null,
                            bottom: null,
                            width: 215.0,
                            height: 34.0,
                            child: GeneratedRoutesLabelWidget5(),
                          ),
                          Positioned(
                            left: 19.0,
                            top: 38.0,
                            right: null,
                            bottom: null,
                            width: 20.0,
                            height: 20.0,
                            child: GeneratedBackButtonWidget41(),
                          ),
                          Positioned(
                            left: 18.0,
                            top: 90.0,
                            right: null,
                            bottom: null,
                            width: 382.0,
                            height: 55.0,
                            child: GeneratedStartPointButtonWidget14(),
                          ),
                          Positioned(
                            left: 18.0,
                            top: 153.0,
                            right: null,
                            bottom: null,
                            width: 382.0,
                            height: 55.0,
                            child: GeneratedEndPointButtonWidget6(),
                          ),
                          Positioned(
                            left: 18.0,
                            top: 216.0,
                            right: null,
                            bottom: null,
                            width: 382.0,
                            height: 55.0,
                            child: GeneratedStartEndTimeButtonWidget6(),
                          ),
                          Positioned(
                            left: 39.0,
                            top: 235.0,
                            right: null,
                            bottom: null,
                            width: 20.0,
                            height: 20.0,
                            child: GeneratedStartTimeIconWidget8(),
                          ),
                          Positioned(
                            left: 0.0,
                            top: 0.0,
                            right: 0.0,
                            bottom: 0.0,
                            width: null,
                            height: null,
                            child: LayoutBuilder(builder: (BuildContext context,
                                BoxConstraints constraints) {
                              final double width =
                                  constraints.maxWidth * 0.04877035451489826;

                              final double height =
                                  constraints.maxHeight * 0.022123895297392955;

                              return Stack(children: [
                                TransformHelper.translate(
                                    x: constraints.maxWidth *
                                        0.5610859715661337,
                                    y: constraints.maxHeight *
                                        0.261797758492317,
                                    z: 0,
                                    child: Container(
                                      width: width,
                                      height: height,
                                      child: GeneratedEndTimeIconWidget4(),
                                    ))
                              ]);
                            }),
                          ),
                          Positioned(
                            left: 9.0,
                            top: 360.0,
                            right: null,
                            bottom: null,
                            width: 397.0,
                            height: 105.0,
                            child: Generated1Widget5(),
                          ),
                          Positioned(
                            left: 50.75,
                            top: 411.69232177734375,
                            right: null,
                            bottom: null,
                            width: 12.75,
                            height: 14.692307472229004,
                            child: GeneratedBackButtonWidget43(),
                          ),
                          Positioned(
                            left: 6.0,
                            top: 507.0,
                            right: null,
                            bottom: null,
                            width: 400.0,
                            height: 98.0,
                            child: Generated2Widget4(),
                          ),
                          Positioned(
                            left: 176.0,
                            top: 535.0,
                            right: null,
                            bottom: null,
                            width: 30.0,
                            height: 30.0,
                            child: GeneratedPeopleWidget21(),
                          ),
                          Positioned(
                            left: 6.0,
                            top: 652.0,
                            right: null,
                            bottom: null,
                            width: 400.0,
                            height: 94.44444274902344,
                            child: Generated3Widget4(),
                          ),
                          Positioned(
                            left: 0.0,
                            top: 0.0,
                            right: 0.0,
                            bottom: 0.0,
                            width: null,
                            height: null,
                            child: LayoutBuilder(builder: (BuildContext context,
                                BoxConstraints constraints) {
                              final double width =
                                  constraints.maxWidth * 0.04999724099802416;

                              final double height =
                                  constraints.maxHeight * 0.016586792666609115;

                              return Stack(children: [
                                TransformHelper.translate(
                                    x: constraints.maxWidth *
                                        0.13454760174418604,
                                    y: constraints.maxHeight *
                                        0.6183313190607734,
                                    z: 0,
                                    child: Container(
                                      width: width,
                                      height: height,
                                      child: GeneratedU2Widget4(),
                                    ))
                              ]);
                            }),
                          ),
                          Positioned(
                            left: 224.0,
                            top: 395.0,
                            right: null,
                            bottom: null,
                            width: 30.0,
                            height: 30.0,
                            child: GeneratedPeopleWidget23(),
                          ),
                          Positioned(
                            left: 219.0,
                            top: 678.0,
                            right: null,
                            bottom: null,
                            width: 30.0,
                            height: 32.30769348144531,
                            child: GeneratedPeopleWidget24(),
                          ),
                          Positioned(
                            left: 0.0,
                            top: 0.0,
                            right: 0.0,
                            bottom: 0.0,
                            width: null,
                            height: null,
                            child: LayoutBuilder(builder: (BuildContext context,
                                BoxConstraints constraints) {
                              final double width =
                                  constraints.maxWidth * 0.07541479066360829;

                              final double height =
                                  constraints.maxHeight * 0.03370786213743094;

                              return Stack(children: [
                                TransformHelper.translate(
                                    x: constraints.maxWidth *
                                        0.39573832667151165,
                                    y: constraints.maxHeight *
                                        0.436029558550587,
                                    z: 0,
                                    child: Container(
                                      width: width,
                                      height: height,
                                      child: GeneratedPeopleWidget25(),
                                    ))
                              ]);
                            }),
                          ),
                          Positioned(
                            left: 9.0,
                            top: 629.0,
                            right: null,
                            bottom: null,
                            width: 384.0,
                            height: 24.0,
                            child: GeneratedRouteSelectionsWidget19(),
                          ),
                          Positioned(
                            left: 228.8507080078125,
                            top: 310.0,
                            right: null,
                            bottom: null,
                            width: 184.6526641845703,
                            height: 107.28369903564453,
                            child: GeneratedRectangle132Widget7(),
                          ),
                          Positioned(
                            left: 349.0,
                            top: 371.0,
                            right: null,
                            bottom: null,
                            width: 57.0,
                            height: 28.0,
                            child: GeneratedGroup22Widget5(),
                          ),
                          Positioned(
                            left: 349.0,
                            top: 332.0,
                            right: null,
                            bottom: null,
                            width: 57.0,
                            height: 28.0,
                            child: GeneratedGroup21Widget7(),
                          ),
                          Positioned(
                            left: 210.0,
                            top: 374.0,
                            right: null,
                            bottom: null,
                            width: 142.0,
                            height: 31.0,
                            child: GeneratedSafestWidget(),
                          ),
                          Positioned(
                            left: 224.0,
                            top: 333.0,
                            right: null,
                            bottom: null,
                            width: 111.0,
                            height: 32.0,
                            child: GeneratedFastestWidget(),
                          )
                        ]),
                  ))
            ])),
      );
    }));
  }
}
