import 'package:flutter/material.dart';
import 'package:flutterapp/routeeapp/generatedsearchsresultsactivitywidget/generated/GeneratedPeopleWidget1.dart';
import 'package:flutterapp/routeeapp/generatedsearchsresultsactivitywidget/generated/GeneratedStartEndTimeButtonWidget.dart';
import 'package:flutterapp/routeeapp/generatedsearchsresultsactivitywidget/generated/GeneratedRouteSelectionsWidget2.dart';
import 'package:flutterapp/routeeapp/generatedsearchsresultsactivitywidget/generated/GeneratedNotificationsWidget3.dart';
import 'package:flutterapp/routeeapp/generatedsearchsresultsactivitywidget/generated/GeneratedStartPointButtonWidget.dart';
import 'package:flutterapp/routeeapp/generatedsearchsresultsactivitywidget/generated/GeneratedEndPointButtonWidget.dart';
import 'package:flutterapp/routeeapp/generatedsearchsresultsactivitywidget/generated/GeneratedPeopleWidget2.dart';
import 'package:flutterapp/routeeapp/generatedsearchsresultsactivitywidget/generated/GeneratedBackButtonWidget2.dart';
import 'package:flutterapp/routeeapp/generatedsearchsresultsactivitywidget/generated/GeneratedRouteSelectionsWidget1.dart';
import 'package:flutterapp/routeeapp/generatedsearchsresultsactivitywidget/generated/GeneratedGroupWidget100.dart';
import 'package:flutterapp/routeeapp/generatedsearchsresultsactivitywidget/generated/GeneratedStartTimeIconWidget.dart';
import 'package:flutterapp/routeeapp/generatedsearchsresultsactivitywidget/generated/GeneratedPeopleWidget.dart';
import 'package:flutterapp/routeeapp/generatedsearchsresultsactivitywidget/generated/GeneratedVectorWidget216.dart';
import 'package:flutterapp/routeeapp/generatedsearchsresultsactivitywidget/generated/Generated1Widget.dart';
import 'package:flutterapp/routeeapp/generatedsearchsresultsactivitywidget/generated/GeneratedRouteSelectionsWidget.dart';
import 'package:flutterapp/routeeapp/generatedsearchsresultsactivitywidget/generated/Generated3Widget.dart';
import 'package:flutterapp/routeeapp/generatedsearchsresultsactivitywidget/generated/GeneratedEndTimeIconWidget.dart';
import 'package:flutterapp/routeeapp/generatedsearchsresultsactivitywidget/generated/GeneratedHomeWidget11.dart';
import 'package:flutterapp/routeeapp/generatedsearchsresultsactivitywidget/generated/GeneratedRoutesLabelWidget.dart';
import 'package:flutterapp/routeeapp/generatedsearchsresultsactivitywidget/generated/Generated2Widget.dart';
import 'package:flutterapp/routeeapp/generatedsearchsresultsactivitywidget/generated/GeneratedU3Widget.dart';
import 'package:flutterapp/routeeapp/generatedsearchsresultsactivitywidget/generated/GeneratedNotificationsWidget2.dart';
import 'package:flutterapp/helpers/transform/transform.dart';
import 'package:flutterapp/routeeapp/generatedsearchsresultsactivitywidget/generated/GeneratedU2Widget.dart';

/* Frame Search's Results Activity
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedSearchsResultsActivityWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(child: LayoutBuilder(
        builder: (BuildContext context, BoxConstraints constraints) {
      return SingleChildScrollView(
        scrollDirection: Axis.vertical,
        child: Container(
            height: 901.3642578125,
            child: Stack(children: [
              Container(
                  width: constraints.maxWidth,
                  child: Container(
                    width: 416.7637939453125,
                    height: 901.3642578125,
                    child: Stack(
                        fit: StackFit.expand,
                        alignment: Alignment.center,
                        overflow: Overflow.visible,
                        children: [
                          Positioned(
                            left: -12.0,
                            top: 0.0,
                            right: null,
                            bottom: null,
                            width: 428.7637939453125,
                            height: 900.02490234375,
                            child: GeneratedHomeWidget11(),
                          ),
                          Positioned(
                            left: 15.0,
                            top: 307.0,
                            right: null,
                            bottom: null,
                            width: 384.0,
                            height: 30.0,
                            child: GeneratedRouteSelectionsWidget(),
                          ),
                          Positioned(
                            left: 15.0,
                            top: 339.0,
                            right: null,
                            bottom: null,
                            width: 384.0,
                            height: 24.0,
                            child: GeneratedRouteSelectionsWidget1(),
                          ),
                          Positioned(
                            left: 14.0,
                            top: 459.0,
                            right: null,
                            bottom: null,
                            width: 384.0,
                            height: 24.0,
                            child: GeneratedRouteSelectionsWidget2(),
                          ),
                          Positioned(
                            left: 103.0,
                            top: 44.0,
                            right: null,
                            bottom: null,
                            width: 215.0,
                            height: 34.0,
                            child: GeneratedRoutesLabelWidget(),
                          ),
                          Positioned(
                            left: 16.0,
                            top: 51.0,
                            right: null,
                            bottom: null,
                            width: 20.0,
                            height: 20.0,
                            child: GeneratedBackButtonWidget2(),
                          ),
                          Positioned(
                            left: 15.0,
                            top: 103.0,
                            right: null,
                            bottom: null,
                            width: 382.0,
                            height: 55.0,
                            child: GeneratedStartPointButtonWidget(),
                          ),
                          Positioned(
                            left: 15.0,
                            top: 166.0,
                            right: null,
                            bottom: null,
                            width: 382.0,
                            height: 55.0,
                            child: GeneratedEndPointButtonWidget(),
                          ),
                          Positioned(
                            left: 15.0,
                            top: 229.0,
                            right: null,
                            bottom: null,
                            width: 382.0,
                            height: 55.0,
                            child: GeneratedStartEndTimeButtonWidget(),
                          ),
                          Positioned(
                            left: 36.0,
                            top: 248.0,
                            right: null,
                            bottom: null,
                            width: 20.0,
                            height: 20.0,
                            child: GeneratedStartTimeIconWidget(),
                          ),
                          Positioned(
                            left: 0.0,
                            top: 0.0,
                            right: 0.0,
                            bottom: 0.0,
                            width: null,
                            height: null,
                            child: LayoutBuilder(builder: (BuildContext context,
                                BoxConstraints constraints) {
                              final double width =
                                  constraints.maxWidth * 0.04879796940888877;

                              final double height =
                                  constraints.maxHeight * 0.02218858782856282;

                              return Stack(children: [
                                TransformHelper.translate(
                                    x: constraints.maxWidth * 0.542273593059899,
                                    y: constraints.maxHeight *
                                        0.27624791846560715,
                                    z: 0,
                                    child: Container(
                                      width: width,
                                      height: height,
                                      child: GeneratedEndTimeIconWidget(),
                                    ))
                              ]);
                            }),
                          ),
                          Positioned(
                            left: 2.0,
                            top: 366.0,
                            right: null,
                            bottom: null,
                            width: 416.0,
                            height: 90.0,
                            child: Generated1Widget(),
                          ),
                          Positioned(
                            left: 0.0,
                            top: 485.0,
                            right: null,
                            bottom: null,
                            width: 416.0,
                            height: 92.0,
                            child: Generated2Widget(),
                          ),
                          Positioned(
                            left: 0.0,
                            top: 0.0,
                            right: 0.0,
                            bottom: 0.0,
                            width: null,
                            height: null,
                            child: LayoutBuilder(builder: (BuildContext context,
                                BoxConstraints constraints) {
                              final double width =
                                  constraints.maxWidth * 0.03552103351250055;

                              final double height =
                                  constraints.maxHeight * 0.033283061608678034;

                              return Stack(children: [
                                TransformHelper.translate(
                                    x: constraints.maxWidth *
                                        0.04079049151335524,
                                    y: constraints.maxHeight *
                                        0.5602618426712113,
                                    z: 0,
                                    child: Container(
                                      width: width,
                                      height: height,
                                      child: GeneratedGroupWidget100(),
                                    ))
                              ]);
                            }),
                          ),
                          Positioned(
                            left: 0.0,
                            top: 584.0,
                            right: null,
                            bottom: null,
                            width: 416.0,
                            height: 90.0,
                            child: Generated3Widget(),
                          ),
                          Positioned(
                            left: 0.0,
                            top: 0.0,
                            right: 0.0,
                            bottom: 0.0,
                            width: null,
                            height: null,
                            child: LayoutBuilder(builder: (BuildContext context,
                                BoxConstraints constraints) {
                              final double width =
                                  constraints.maxWidth * 0.05038825422238;

                              final double height =
                                  constraints.maxHeight * 0.01664144087142212;

                              return Stack(children: [
                                TransformHelper.translate(
                                    x: constraints.maxWidth *
                                        0.1535642033443962,
                                    y: constraints.maxHeight *
                                        0.5924352950226274,
                                    z: 0,
                                    child: Container(
                                      width: width,
                                      height: height,
                                      child: GeneratedU2Widget(),
                                    ))
                              ]);
                            }),
                          ),
                          Positioned(
                            left: 0.0,
                            top: 0.0,
                            right: 0.0,
                            bottom: 0.0,
                            width: null,
                            height: null,
                            child: LayoutBuilder(builder: (BuildContext context,
                                BoxConstraints constraints) {
                              final double width =
                                  constraints.maxWidth * 0.05038825422238;

                              final double height =
                                  constraints.maxHeight * 0.01664144087142212;

                              return Stack(children: [
                                TransformHelper.translate(
                                    x: constraints.maxWidth *
                                        0.26153903382092475,
                                    y: constraints.maxHeight *
                                        0.6967216578168727,
                                    z: 0,
                                    child: Container(
                                      width: width,
                                      height: height,
                                      child: GeneratedU3Widget(),
                                    ))
                              ]);
                            }),
                          ),
                          Positioned(
                            left: 307.0,
                            top: 399.0,
                            right: null,
                            bottom: null,
                            width: 30.0,
                            height: 30.0,
                            child: GeneratedPeopleWidget(),
                          ),
                          Positioned(
                            left: 308.0,
                            top: 513.0,
                            right: null,
                            bottom: null,
                            width: 30.0,
                            height: 30.0,
                            child: GeneratedPeopleWidget1(),
                          ),
                          Positioned(
                            left: 309.0,
                            top: 612.0,
                            right: null,
                            bottom: null,
                            width: 30.0,
                            height: 30.0,
                            child: GeneratedPeopleWidget2(),
                          ),
                          Positioned(
                            left: 360.0,
                            top: 515.0,
                            right: null,
                            bottom: null,
                            width: 26.0,
                            height: 26.0,
                            child: GeneratedNotificationsWidget2(),
                          ),
                          Positioned(
                            left: 360.0,
                            top: 613.0,
                            right: null,
                            bottom: null,
                            width: 26.0,
                            height: 26.0,
                            child: GeneratedNotificationsWidget3(),
                          ),
                          Positioned(
                            left: 0.0,
                            top: 0.0,
                            right: 0.0,
                            bottom: 0.0,
                            width: null,
                            height: null,
                            child: LayoutBuilder(builder: (BuildContext context,
                                BoxConstraints constraints) {
                              double percentWidth = 0.04682852950928333;
                              double scaleX =
                                  (constraints.maxWidth * percentWidth) /
                                      19.516435623168945;

                              double percentHeight = 0.02523951865499021;
                              double scaleY =
                                  (constraints.maxHeight * percentHeight) /
                                      22.75;

                              return Stack(children: [
                                TransformHelper.translateAndScale(
                                    translateX: constraints.maxWidth *
                                        0.8709969658439971,
                                    translateY: constraints.maxHeight *
                                        0.4459906153541127,
                                    translateZ: 0,
                                    scaleX: scaleX,
                                    scaleY: scaleY,
                                    scaleZ: 1,
                                    child: GeneratedVectorWidget216())
                              ]);
                            }),
                          )
                        ]),
                  ))
            ])),
      );
    }));
  }
}
