import 'package:flutter/material.dart';
import 'package:flutterapp/routeeapp/generatedsearchsresultsactivitywidget7/generated/GeneratedGroup22Widget7.dart';
import 'package:flutterapp/routeeapp/generatedsearchsresultsactivitywidget7/generated/GeneratedHomeWidget21.dart';
import 'package:flutterapp/routeeapp/generatedsearchsresultsactivitywidget7/generated/GeneratedStartTimeIconWidget11.dart';
import 'package:flutterapp/routeeapp/generatedsearchsresultsactivitywidget7/generated/GeneratedStartPointButtonWidget17.dart';
import 'package:flutterapp/routeeapp/generatedsearchsresultsactivitywidget7/generated/GeneratedFastestWidget1.dart';
import 'package:flutterapp/routeeapp/generatedsearchsresultsactivitywidget7/generated/GeneratedEndPointButtonWidget9.dart';
import 'package:flutterapp/routeeapp/generatedsearchsresultsactivitywidget7/generated/GeneratedGroup21Widget9.dart';
import 'package:flutterapp/helpers/transform/transform.dart';
import 'package:flutterapp/routeeapp/generatedsearchsresultsactivitywidget7/generated/GeneratedRectangle132Widget11.dart';
import 'package:flutterapp/routeeapp/generatedsearchsresultsactivitywidget7/generated/GeneratedRouteSelectionsWidget28.dart';
import 'package:flutterapp/routeeapp/generatedsearchsresultsactivitywidget7/generated/GeneratedSafestWidget1.dart';
import 'package:flutterapp/routeeapp/generatedsearchsresultsactivitywidget7/generated/GeneratedBackButtonWidget72.dart';
import 'package:flutterapp/routeeapp/generatedsearchsresultsactivitywidget7/generated/GeneratedPeopleWidget43.dart';
import 'package:flutterapp/routeeapp/generatedsearchsresultsactivitywidget7/generated/GeneratedRoutesLabelWidget8.dart';
import 'package:flutterapp/routeeapp/generatedsearchsresultsactivitywidget7/generated/GeneratedVectorWidget808.dart';
import 'package:flutterapp/routeeapp/generatedsearchsresultsactivitywidget7/generated/GeneratedStartEndTimeButtonWidget9.dart';
import 'package:flutterapp/routeeapp/generatedsearchsresultsactivitywidget7/generated/GeneratedEndTimeIconWidget7.dart';

/* Frame Search's Results Activity
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedSearchsResultsActivityWidget7 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(child: LayoutBuilder(
        builder: (BuildContext context, BoxConstraints constraints) {
      return SingleChildScrollView(
        scrollDirection: Axis.vertical,
        child: Container(
            height: 905.0,
            child: Stack(children: [
              Container(
                  width: constraints.maxWidth,
                  child: Container(
                    width: 430.0,
                    height: 905.0,
                    child: Stack(
                        fit: StackFit.expand,
                        alignment: Alignment.center,
                        overflow: Overflow.visible,
                        children: [
                          Positioned(
                            left: -14.0,
                            top: -8.0,
                            right: null,
                            bottom: null,
                            width: 444.0,
                            height: 892.0,
                            child: GeneratedHomeWidget21(),
                          ),
                          Positioned(
                            left: 0.0,
                            top: 0.0,
                            right: 0.0,
                            bottom: 0.0,
                            width: null,
                            height: null,
                            child: LayoutBuilder(builder: (BuildContext context,
                                BoxConstraints constraints) {
                              double percentWidth = 0.06227483971174373;
                              double scaleX =
                                  (constraints.maxWidth * percentWidth) /
                                      26.778181076049805;

                              double percentHeight = 0.023815717749832745;
                              double scaleY =
                                  (constraints.maxHeight * percentHeight) /
                                      21.553224563598633;

                              return Stack(children: [
                                TransformHelper.translateAndScale(
                                    translateX: constraints.maxWidth *
                                        0.9012028184047965,
                                    translateY: constraints.maxHeight *
                                        0.34998216154825623,
                                    translateZ: 0,
                                    scaleX: scaleX,
                                    scaleY: scaleY,
                                    scaleZ: 1,
                                    child: GeneratedVectorWidget808())
                              ]);
                            }),
                          ),
                          Positioned(
                            left: 18.0,
                            top: 294.0,
                            right: null,
                            bottom: null,
                            width: 384.0,
                            height: 30.0,
                            child: GeneratedRouteSelectionsWidget28(),
                          ),
                          Positioned(
                            left: 106.0,
                            top: 31.0,
                            right: null,
                            bottom: null,
                            width: 215.0,
                            height: 34.0,
                            child: GeneratedRoutesLabelWidget8(),
                          ),
                          Positioned(
                            left: 19.0,
                            top: 38.0,
                            right: null,
                            bottom: null,
                            width: 20.0,
                            height: 20.0,
                            child: GeneratedBackButtonWidget72(),
                          ),
                          Positioned(
                            left: 18.0,
                            top: 90.0,
                            right: null,
                            bottom: null,
                            width: 382.0,
                            height: 55.0,
                            child: GeneratedStartPointButtonWidget17(),
                          ),
                          Positioned(
                            left: 18.0,
                            top: 153.0,
                            right: null,
                            bottom: null,
                            width: 382.0,
                            height: 55.0,
                            child: GeneratedEndPointButtonWidget9(),
                          ),
                          Positioned(
                            left: 18.0,
                            top: 216.0,
                            right: null,
                            bottom: null,
                            width: 382.0,
                            height: 55.0,
                            child: GeneratedStartEndTimeButtonWidget9(),
                          ),
                          Positioned(
                            left: 39.0,
                            top: 235.0,
                            right: null,
                            bottom: null,
                            width: 20.0,
                            height: 20.0,
                            child: GeneratedStartTimeIconWidget11(),
                          ),
                          Positioned(
                            left: 0.0,
                            top: 0.0,
                            right: 0.0,
                            bottom: 0.0,
                            width: null,
                            height: null,
                            child: LayoutBuilder(builder: (BuildContext context,
                                BoxConstraints constraints) {
                              final double width =
                                  constraints.maxWidth * 0.04877035451489826;

                              final double height =
                                  constraints.maxHeight * 0.022123895297392955;

                              return Stack(children: [
                                TransformHelper.translate(
                                    x: constraints.maxWidth *
                                        0.5610859715661337,
                                    y: constraints.maxHeight *
                                        0.261797758492317,
                                    z: 0,
                                    child: Container(
                                      width: width,
                                      height: height,
                                      child: GeneratedEndTimeIconWidget7(),
                                    ))
                              ]);
                            }),
                          ),
                          Positioned(
                            left: 170.0,
                            top: 625.0,
                            right: null,
                            bottom: null,
                            width: 30.0,
                            height: 32.30769348144531,
                            child: GeneratedPeopleWidget43(),
                          ),
                          Positioned(
                            left: 259.6365966796875,
                            top: 318.0,
                            right: null,
                            bottom: null,
                            width: 162.63882446289062,
                            height: 107.28221130371094,
                            child: GeneratedRectangle132Widget11(),
                          ),
                          Positioned(
                            left: 352.408203125,
                            top: 340.0,
                            right: null,
                            bottom: null,
                            width: 57.3922004699707,
                            height: 28.0,
                            child: GeneratedGroup22Widget7(),
                          ),
                          Positioned(
                            left: 352.408203125,
                            top: 383.0,
                            right: null,
                            bottom: null,
                            width: 57.3922004699707,
                            height: 28.0,
                            child: GeneratedGroup21Widget9(),
                          ),
                          Positioned(
                            left: 263.1943359375,
                            top: 342.0,
                            right: null,
                            bottom: null,
                            width: 84.318603515625,
                            height: 32.0,
                            child: GeneratedFastestWidget1(),
                          ),
                          Positioned(
                            left: 248.303466796875,
                            top: 386.0,
                            right: null,
                            bottom: null,
                            width: 107.51555633544922,
                            height: 31.0,
                            child: GeneratedSafestWidget1(),
                          )
                        ]),
                  ))
            ])),
      );
    }));
  }
}
