import 'package:flutter/material.dart';
import 'package:flutterapp/routeeapp/generatedsearchsresultsactivitywidget2/generated/GeneratedEllipse12Widget.dart';
import 'package:flutterapp/routeeapp/generatedsearchsresultsactivitywidget2/generated/GeneratedEllipse11Widget.dart';
import 'package:flutterapp/routeeapp/generatedsearchsresultsactivitywidget2/generated/GeneratedEllipse9Widget.dart';
import 'package:flutterapp/routeeapp/generatedsearchsresultsactivitywidget2/generated/GeneratedSearchButtonWidget22.dart';
import 'package:flutterapp/routeeapp/generatedsearchsresultsactivitywidget2/generated/GeneratedTXTSubheadingRegular16spWidget8.dart';
import 'package:flutterapp/routeeapp/generatedsearchsresultsactivitywidget2/generated/GeneratedEllipse13Widget1.dart';
import 'package:flutterapp/routeeapp/generatedsearchsresultsactivitywidget2/generated/GeneratedEllipse16Widget.dart';
import 'package:flutterapp/routeeapp/generatedsearchsresultsactivitywidget2/generated/GeneratedFrameWidget38.dart';
import 'package:flutterapp/routeeapp/generatedsearchsresultsactivitywidget2/generated/GeneratedEllipse8Widget.dart';
import 'package:flutterapp/routeeapp/generatedsearchsresultsactivitywidget2/generated/Generated1Widget2.dart';
import 'package:flutterapp/routeeapp/generatedsearchsresultsactivitywidget2/generated/GeneratedEllipse19Widget.dart';
import 'package:flutterapp/routeeapp/generatedsearchsresultsactivitywidget2/generated/GeneratedEllipse10Widget.dart';
import 'package:flutterapp/routeeapp/generatedsearchsresultsactivitywidget2/generated/GeneratedGroup12Widget.dart';
import 'package:flutterapp/routeeapp/generatedsearchsresultsactivitywidget2/generated/GeneratedFrameWidget37.dart';
import 'package:flutterapp/routeeapp/generatedsearchsresultsactivitywidget2/generated/GeneratedGroup13Widget.dart';
import 'package:flutterapp/routeeapp/generatedsearchsresultsactivitywidget2/generated/GeneratedEllipse15Widget.dart';
import 'package:flutterapp/routeeapp/generatedsearchsresultsactivitywidget2/generated/GeneratedBackButtonWidget19.dart';
import 'package:flutterapp/routeeapp/generatedsearchsresultsactivitywidget2/generated/GeneratedRoutesLabelWidget2.dart';
import 'package:flutterapp/helpers/transform/transform.dart';
import 'package:flutterapp/routeeapp/generatedsearchsresultsactivitywidget2/generated/GeneratedEllipse14Widget.dart';
import 'package:flutterapp/routeeapp/generatedsearchsresultsactivitywidget2/generated/GeneratedTXTSubheadingRegular16spWidget10.dart';
import 'package:flutterapp/routeeapp/generatedsearchsresultsactivitywidget2/generated/GeneratedEllipse18Widget.dart';
import 'package:flutterapp/routeeapp/generatedsearchsresultsactivitywidget2/generated/GeneratedHomeWidget13.dart';
import 'package:flutterapp/routeeapp/generatedsearchsresultsactivitywidget2/generated/GeneratedTXTSubheadingRegular16spWidget13.dart';
import 'package:flutterapp/routeeapp/generatedsearchsresultsactivitywidget2/generated/GeneratedTXTSubheadingRegular16spWidget9.dart';
import 'package:flutterapp/routeeapp/generatedsearchsresultsactivitywidget2/generated/GeneratedTXTSubheadingRegular16spWidget12.dart';
import 'package:flutterapp/routeeapp/generatedsearchsresultsactivitywidget2/generated/GeneratedTXTSubheadingRegular16spWidget11.dart';

/* Frame Search's Results Activity
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedSearchsResultsActivityWidget2 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(child: LayoutBuilder(
        builder: (BuildContext context, BoxConstraints constraints) {
      return SingleChildScrollView(
        scrollDirection: Axis.vertical,
        child: Container(
            height: 901.3642578125,
            child: Stack(children: [
              Container(
                  width: constraints.maxWidth,
                  child: Container(
                    width: 416.7637939453125,
                    height: 901.3642578125,
                    child: Stack(
                        fit: StackFit.expand,
                        alignment: Alignment.center,
                        overflow: Overflow.visible,
                        children: [
                          Positioned(
                            left: -10.0,
                            top: 0.0,
                            right: null,
                            bottom: null,
                            width: 426.7637939453125,
                            height: 900.02490234375,
                            child: GeneratedHomeWidget13(),
                          ),
                          Positioned(
                            left: 103.0,
                            top: 44.0,
                            right: null,
                            bottom: null,
                            width: 215.0,
                            height: 34.0,
                            child: GeneratedRoutesLabelWidget2(),
                          ),
                          Positioned(
                            left: 16.0,
                            top: 51.0,
                            right: null,
                            bottom: null,
                            width: 20.0,
                            height: 20.0,
                            child: GeneratedBackButtonWidget19(),
                          ),
                          Positioned(
                            left: 0.0,
                            top: 88.0,
                            right: null,
                            bottom: null,
                            width: 417.0,
                            height: 403.0,
                            child: Generated1Widget2(),
                          ),
                          Positioned(
                            left: 16.0,
                            top: 471.0,
                            right: null,
                            bottom: null,
                            width: 14.0,
                            height: 14.0,
                            child: GeneratedFrameWidget37(),
                          ),
                          Positioned(
                            left: 0.0,
                            top: 0.0,
                            right: 0.0,
                            bottom: 0.0,
                            width: null,
                            height: null,
                            child: LayoutBuilder(builder: (BuildContext context,
                                BoxConstraints constraints) {
                              final double width =
                                  constraints.maxWidth * 0.045589372867867614;

                              final double height =
                                  constraints.maxHeight * 0.021079158437134683;

                              return Stack(children: [
                                TransformHelper.translate(
                                    x: constraints.maxWidth *
                                        0.033592169481586664,
                                    y: constraints.maxHeight *
                                        0.17307098506279003,
                                    z: 0,
                                    child: Container(
                                      width: width,
                                      height: height,
                                      child: GeneratedFrameWidget38(),
                                    ))
                              ]);
                            }),
                          ),
                          Positioned(
                            left: 0.0,
                            top: 0.0,
                            right: 0.0,
                            bottom: 0.0,
                            width: null,
                            height: null,
                            child: LayoutBuilder(builder: (BuildContext context,
                                BoxConstraints constraints) {
                              double percentWidth = 0.016796084740793332;
                              double scaleX =
                                  (constraints.maxWidth * percentWidth) / 7.0;

                              double percentHeight = 0.0077660057399969885;
                              double scaleY =
                                  (constraints.maxHeight * percentHeight) / 7.0;

                              return Stack(children: [
                                TransformHelper.translateAndScale(
                                    translateX: constraints.maxWidth *
                                        0.047988813545123805,
                                    translateY: constraints.maxHeight *
                                        0.1996972904570654,
                                    translateZ: 0,
                                    scaleX: scaleX,
                                    scaleY: scaleY,
                                    scaleZ: 1,
                                    child: GeneratedEllipse8Widget())
                              ]);
                            }),
                          ),
                          Positioned(
                            left: 0.0,
                            top: 0.0,
                            right: 0.0,
                            bottom: 0.0,
                            width: null,
                            height: null,
                            child: LayoutBuilder(builder: (BuildContext context,
                                BoxConstraints constraints) {
                              double percentWidth = 0.016796084740793332;
                              double scaleX =
                                  (constraints.maxWidth * percentWidth) / 7.0;

                              double percentHeight = 0.0077660057399969885;
                              double scaleY =
                                  (constraints.maxHeight * percentHeight) / 7.0;

                              return Stack(children: [
                                TransformHelper.translateAndScale(
                                    translateX: constraints.maxWidth *
                                        0.047988813545123805,
                                    translateY: constraints.maxHeight *
                                        0.2130104431542031,
                                    translateZ: 0,
                                    scaleX: scaleX,
                                    scaleY: scaleY,
                                    scaleZ: 1,
                                    child: GeneratedEllipse9Widget())
                              ]);
                            }),
                          ),
                          Positioned(
                            left: 0.0,
                            top: 0.0,
                            right: 0.0,
                            bottom: 0.0,
                            width: null,
                            height: null,
                            child: LayoutBuilder(builder: (BuildContext context,
                                BoxConstraints constraints) {
                              double percentWidth = 0.016796084740793332;
                              double scaleX =
                                  (constraints.maxWidth * percentWidth) / 7.0;

                              double percentHeight = 0.0077660057399969885;
                              double scaleY =
                                  (constraints.maxHeight * percentHeight) / 7.0;

                              return Stack(children: [
                                TransformHelper.translateAndScale(
                                    translateX: constraints.maxWidth *
                                        0.047988813545123805,
                                    translateY: constraints.maxHeight *
                                        0.2263235958513408,
                                    translateZ: 0,
                                    scaleX: scaleX,
                                    scaleY: scaleY,
                                    scaleZ: 1,
                                    child: GeneratedEllipse10Widget())
                              ]);
                            }),
                          ),
                          Positioned(
                            left: 0.0,
                            top: 0.0,
                            right: 0.0,
                            bottom: 0.0,
                            width: null,
                            height: null,
                            child: LayoutBuilder(builder: (BuildContext context,
                                BoxConstraints constraints) {
                              double percentWidth = 0.016796084740793332;
                              double scaleX =
                                  (constraints.maxWidth * percentWidth) / 7.0;

                              double percentHeight = 0.0077660057399969885;
                              double scaleY =
                                  (constraints.maxHeight * percentHeight) / 7.0;

                              return Stack(children: [
                                TransformHelper.translateAndScale(
                                    translateX: constraints.maxWidth *
                                        0.047988813545123805,
                                    translateY: constraints.maxHeight *
                                        0.2396367485484785,
                                    translateZ: 0,
                                    scaleX: scaleX,
                                    scaleY: scaleY,
                                    scaleZ: 1,
                                    child: GeneratedEllipse11Widget())
                              ]);
                            }),
                          ),
                          Positioned(
                            left: 0.0,
                            top: 0.0,
                            right: 0.0,
                            bottom: 0.0,
                            width: null,
                            height: null,
                            child: LayoutBuilder(builder: (BuildContext context,
                                BoxConstraints constraints) {
                              double percentWidth = 0.016796084740793332;
                              double scaleX =
                                  (constraints.maxWidth * percentWidth) / 7.0;

                              double percentHeight = 0.0077660057399969885;
                              double scaleY =
                                  (constraints.maxHeight * percentHeight) / 7.0;

                              return Stack(children: [
                                TransformHelper.translateAndScale(
                                    translateX: constraints.maxWidth *
                                        0.047988813545123805,
                                    translateY: constraints.maxHeight *
                                        0.25294990124561617,
                                    translateZ: 0,
                                    scaleX: scaleX,
                                    scaleY: scaleY,
                                    scaleZ: 1,
                                    child: GeneratedEllipse12Widget())
                              ]);
                            }),
                          ),
                          Positioned(
                            left: 0.0,
                            top: 0.0,
                            right: 0.0,
                            bottom: 0.0,
                            width: null,
                            height: null,
                            child: LayoutBuilder(builder: (BuildContext context,
                                BoxConstraints constraints) {
                              double percentWidth = 0.014396644063537143;
                              double scaleX =
                                  (constraints.maxWidth * percentWidth) / 6.0;

                              double percentHeight = 0.0066565763485688465;
                              double scaleY =
                                  (constraints.maxHeight * percentHeight) / 6.0;

                              return Stack(children: [
                                TransformHelper.translateAndScale(
                                    translateX: constraints.maxWidth *
                                        0.047988813545123805,
                                    translateY: constraints.maxHeight *
                                        0.42491145691697807,
                                    translateZ: 0,
                                    scaleX: scaleX,
                                    scaleY: scaleY,
                                    scaleZ: 1,
                                    child: GeneratedEllipse13Widget1())
                              ]);
                            }),
                          ),
                          Positioned(
                            left: 0.0,
                            top: 0.0,
                            right: 0.0,
                            bottom: 0.0,
                            width: null,
                            height: null,
                            child: LayoutBuilder(builder: (BuildContext context,
                                BoxConstraints constraints) {
                              double percentWidth = 0.014396644063537143;
                              double scaleX =
                                  (constraints.maxWidth * percentWidth) / 6.0;

                              double percentHeight = 0.0066565763485688465;
                              double scaleY =
                                  (constraints.maxHeight * percentHeight) / 6.0;

                              return Stack(children: [
                                TransformHelper.translateAndScale(
                                    translateX: constraints.maxWidth *
                                        0.047988813545123805,
                                    translateY: constraints.maxHeight *
                                        0.4393340390055439,
                                    translateZ: 0,
                                    scaleX: scaleX,
                                    scaleY: scaleY,
                                    scaleZ: 1,
                                    child: GeneratedEllipse14Widget())
                              ]);
                            }),
                          ),
                          Positioned(
                            left: 0.0,
                            top: 0.0,
                            right: 0.0,
                            bottom: 0.0,
                            width: null,
                            height: null,
                            child: LayoutBuilder(builder: (BuildContext context,
                                BoxConstraints constraints) {
                              double percentWidth = 0.014396644063537143;
                              double scaleX =
                                  (constraints.maxWidth * percentWidth) / 6.0;

                              double percentHeight = 0.0066565763485688465;
                              double scaleY =
                                  (constraints.maxHeight * percentHeight) / 6.0;

                              return Stack(children: [
                                TransformHelper.translateAndScale(
                                    translateX: constraints.maxWidth *
                                        0.047988813545123805,
                                    translateY: constraints.maxHeight *
                                        0.4515377623112535,
                                    translateZ: 0,
                                    scaleX: scaleX,
                                    scaleY: scaleY,
                                    scaleZ: 1,
                                    child: GeneratedEllipse15Widget())
                              ]);
                            }),
                          ),
                          Positioned(
                            left: 0.0,
                            top: 0.0,
                            right: 0.0,
                            bottom: 0.0,
                            width: null,
                            height: null,
                            child: LayoutBuilder(builder: (BuildContext context,
                                BoxConstraints constraints) {
                              double percentWidth = 0.014396644063537143;
                              double scaleX =
                                  (constraints.maxWidth * percentWidth) / 6.0;

                              double percentHeight = 0.0066565763485688465;
                              double scaleY =
                                  (constraints.maxHeight * percentHeight) / 6.0;

                              return Stack(children: [
                                TransformHelper.translateAndScale(
                                    translateX: constraints.maxWidth *
                                        0.047988813545123805,
                                    translateY: constraints.maxHeight *
                                        0.4626320562255349,
                                    translateZ: 0,
                                    scaleX: scaleX,
                                    scaleY: scaleY,
                                    scaleZ: 1,
                                    child: GeneratedEllipse16Widget())
                              ]);
                            }),
                          ),
                          Positioned(
                            left: 0.0,
                            top: 0.0,
                            right: 0.0,
                            bottom: 0.0,
                            width: null,
                            height: null,
                            child: LayoutBuilder(builder: (BuildContext context,
                                BoxConstraints constraints) {
                              double percentWidth = 0.014396644063537143;
                              double scaleX =
                                  (constraints.maxWidth * percentWidth) / 6.0;

                              double percentHeight = 0.0066565763485688465;
                              double scaleY =
                                  (constraints.maxHeight * percentHeight) / 6.0;

                              return Stack(children: [
                                TransformHelper.translateAndScale(
                                    translateX: constraints.maxWidth *
                                        0.047988813545123805,
                                    translateY: constraints.maxHeight *
                                        0.5003526555340917,
                                    translateZ: 0,
                                    scaleX: scaleX,
                                    scaleY: scaleY,
                                    scaleZ: 1,
                                    child: GeneratedEllipse18Widget())
                              ]);
                            }),
                          ),
                          Positioned(
                            left: 0.0,
                            top: 0.0,
                            right: 0.0,
                            bottom: 0.0,
                            width: null,
                            height: null,
                            child: LayoutBuilder(builder: (BuildContext context,
                                BoxConstraints constraints) {
                              double percentWidth = 0.014396644063537143;
                              double scaleX =
                                  (constraints.maxWidth * percentWidth) / 6.0;

                              double percentHeight = 0.0066565763485688465;
                              double scaleY =
                                  (constraints.maxHeight * percentHeight) / 6.0;

                              return Stack(children: [
                                TransformHelper.translateAndScale(
                                    translateX: constraints.maxWidth *
                                        0.047988813545123805,
                                    translateY: constraints.maxHeight *
                                        0.5103375200569449,
                                    translateZ: 0,
                                    scaleX: scaleX,
                                    scaleY: scaleY,
                                    scaleZ: 1,
                                    child: GeneratedEllipse19Widget())
                              ]);
                            }),
                          ),
                          Positioned(
                            left: 0.0,
                            top: 0.0,
                            right: 0.0,
                            bottom: 0.0,
                            width: null,
                            height: null,
                            child: LayoutBuilder(builder: (BuildContext context,
                                BoxConstraints constraints) {
                              final double width =
                                  constraints.maxWidth * 0.6022596099913038;

                              final double height =
                                  constraints.maxHeight * 0.029954593568559812;

                              return Stack(children: [
                                TransformHelper.translate(
                                    x: constraints.maxWidth *
                                        0.09837706776750381,
                                    y: constraints.maxHeight *
                                        0.17307098506279003,
                                    z: 0,
                                    child: Container(
                                      width: width,
                                      height: height,
                                      child:
                                          GeneratedTXTSubheadingRegular16spWidget8(),
                                    ))
                              ]);
                            }),
                          ),
                          Positioned(
                            left: 0.0,
                            top: 0.0,
                            right: 0.0,
                            bottom: 0.0,
                            width: null,
                            height: null,
                            child: LayoutBuilder(builder: (BuildContext context,
                                BoxConstraints constraints) {
                              final double width =
                                  constraints.maxWidth * 0.6094579320230723;

                              final double height =
                                  constraints.maxHeight * 0.03328288174284424;

                              return Stack(children: [
                                TransformHelper.translate(
                                    x: constraints.maxWidth *
                                        0.09837706776750381,
                                    y: constraints.maxHeight *
                                        0.26515362455132574,
                                    z: 0,
                                    child: Container(
                                      width: width,
                                      height: height,
                                      child:
                                          GeneratedTXTSubheadingRegular16spWidget9(),
                                    ))
                              ]);
                            }),
                          ),
                          Positioned(
                            left: 0.0,
                            top: 0.0,
                            right: 0.0,
                            bottom: 0.0,
                            width: null,
                            height: null,
                            child: LayoutBuilder(builder: (BuildContext context,
                                BoxConstraints constraints) {
                              final double width =
                                  constraints.maxWidth * 0.6094579320230723;

                              final double height =
                                  constraints.maxHeight * 0.03328288174284424;

                              return Stack(children: [
                                TransformHelper.translate(
                                    x: constraints.maxWidth *
                                        0.10557538979927238,
                                    y: constraints.maxHeight *
                                        0.41492659239412477,
                                    z: 0,
                                    child: Container(
                                      width: width,
                                      height: height,
                                      child:
                                          GeneratedTXTSubheadingRegular16spWidget10(),
                                    ))
                              ]);
                            }),
                          ),
                          Positioned(
                            left: 0.0,
                            top: 0.0,
                            right: 0.0,
                            bottom: 0.0,
                            width: null,
                            height: null,
                            child: LayoutBuilder(builder: (BuildContext context,
                                BoxConstraints constraints) {
                              final double width =
                                  constraints.maxWidth * 0.6022596099913038;

                              final double height =
                                  constraints.maxHeight * 0.029954593568559812;

                              return Stack(children: [
                                TransformHelper.translate(
                                    x: constraints.maxWidth *
                                        0.09837706776750381,
                                    y: constraints.maxHeight *
                                        0.2207764488942001,
                                    z: 0,
                                    child: Container(
                                      width: width,
                                      height: height,
                                      child:
                                          GeneratedTXTSubheadingRegular16spWidget11(),
                                    ))
                              ]);
                            }),
                          ),
                          Positioned(
                            left: 0.0,
                            top: 0.0,
                            right: 0.0,
                            bottom: 0.0,
                            width: null,
                            height: null,
                            child: LayoutBuilder(builder: (BuildContext context,
                                BoxConstraints constraints) {
                              final double width =
                                  constraints.maxWidth * 0.6022596099913038;

                              final double height =
                                  constraints.maxHeight * 0.029954593568559812;

                              return Stack(children: [
                                TransformHelper.translate(
                                    x: constraints.maxWidth *
                                        0.10557538979927238,
                                    y: constraints.maxHeight *
                                        0.46485091500839115,
                                    z: 0,
                                    child: Container(
                                      width: width,
                                      height: height,
                                      child:
                                          GeneratedTXTSubheadingRegular16spWidget12(),
                                    ))
                              ]);
                            }),
                          ),
                          Positioned(
                            left: 0.0,
                            top: 0.0,
                            right: 0.0,
                            bottom: 0.0,
                            width: null,
                            height: null,
                            child: LayoutBuilder(builder: (BuildContext context,
                                BoxConstraints constraints) {
                              final double width =
                                  constraints.maxWidth * 0.6022596099913038;

                              final double height =
                                  constraints.maxHeight * 0.029954593568559812;

                              return Stack(children: [
                                TransformHelper.translate(
                                    x: constraints.maxWidth *
                                        0.10557538979927238,
                                    y: constraints.maxHeight *
                                        0.5225412433626545,
                                    z: 0,
                                    child: Container(
                                      width: width,
                                      height: height,
                                      child:
                                          GeneratedTXTSubheadingRegular16spWidget13(),
                                    ))
                              ]);
                            }),
                          ),
                          Positioned(
                            left: 40.99148178100586,
                            top: 308.0,
                            right: null,
                            bottom: null,
                            width: 357.00921630859375,
                            height: 17.0,
                            child: GeneratedGroup12Widget(),
                          ),
                          Positioned(
                            left: 41.0,
                            top: 275.0,
                            right: null,
                            bottom: null,
                            width: 357.00921630859375,
                            height: 17.0,
                            child: GeneratedGroup13Widget(),
                          ),
                          Positioned(
                            left: 13.0,
                            top: 743.0,
                            right: null,
                            bottom: null,
                            width: 382.0,
                            height: 47.0,
                            child: GeneratedSearchButtonWidget22(),
                          )
                        ]),
                  ))
            ])),
      );
    }));
  }
}
