import 'package:flutter/material.dart';
import 'package:flutterapp/helpers/transform/transform.dart';
import 'package:flutterapp/routeeapp/generatednavigationactivitywidget1/generated/GeneratedStep3Widget.dart';
import 'package:flutterapp/routeeapp/generatednavigationactivitywidget1/generated/GeneratedStep9Widget1.dart';
import 'package:flutterapp/routeeapp/generatednavigationactivitywidget1/generated/GeneratedFavoritesButtonWidget2.dart';
import 'package:flutterapp/routeeapp/generatednavigationactivitywidget1/generated/GeneratedStep1Widget.dart';
import 'package:flutterapp/routeeapp/generatednavigationactivitywidget1/generated/GeneratedStep4Widget.dart';
import 'package:flutterapp/routeeapp/generatednavigationactivitywidget1/generated/GeneratedStep5Widget1.dart';
import 'package:flutterapp/routeeapp/generatednavigationactivitywidget1/generated/GeneratedHomeWidget16.dart';
import 'package:flutterapp/routeeapp/generatednavigationactivitywidget1/generated/GeneratedStep2Widget.dart';
import 'package:flutterapp/routeeapp/generatednavigationactivitywidget1/generated/GeneratedStartNavigationLabelWidget2.dart';
import 'package:flutterapp/routeeapp/generatednavigationactivitywidget1/generated/GeneratedBackButtonWidget24.dart';
import 'package:flutterapp/routeeapp/generatednavigationactivitywidget1/generated/GeneratedStep8Widget1.dart';
import 'package:flutterapp/routeeapp/generatednavigationactivitywidget1/generated/GeneratedStep7Widget1.dart';

/* Frame Navigation Activity
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedNavigationActivityWidget1 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: GestureDetector(
      onTap: () =>
          Navigator.pushNamed(context, '/GeneratedNavigationActivityWidget'),
      child: LayoutBuilder(
          builder: (BuildContext context, BoxConstraints constraints) {
        return SingleChildScrollView(
          scrollDirection: Axis.vertical,
          child: Container(
              height: 901.3642578125,
              child: Stack(children: [
                Container(
                    width: constraints.maxWidth,
                    child: Container(
                      width: 416.7637939453125,
                      height: 901.3642578125,
                      child: Stack(
                          fit: StackFit.expand,
                          alignment: Alignment.center,
                          overflow: Overflow.visible,
                          children: [
                            Positioned(
                              left: -9.0,
                              top: 0.0,
                              right: null,
                              bottom: null,
                              width: 425.7637939453125,
                              height: 900.41357421875,
                              child: GeneratedHomeWidget16(),
                            ),
                            Positioned(
                              left: 2.0,
                              top: 44.0,
                              right: null,
                              bottom: null,
                              width: 419.0,
                              height: 37.0,
                              child: GeneratedStartNavigationLabelWidget2(),
                            ),
                            Positioned(
                              left: 16.0,
                              top: 46.0,
                              right: null,
                              bottom: null,
                              width: 20.0,
                              height: 20.0,
                              child: GeneratedBackButtonWidget24(),
                            ),
                            Positioned(
                              left: 0.0,
                              top: 0.0,
                              right: 0.0,
                              bottom: 0.0,
                              width: null,
                              height: null,
                              child: LayoutBuilder(builder:
                                  (BuildContext context,
                                      BoxConstraints constraints) {
                                double percentWidth = 0.07511385956711067;
                                double scaleX =
                                    (constraints.maxWidth * percentWidth) /
                                        31.304737091064453;

                                double percentHeight = 0.03328288174284424;
                                double scaleY =
                                    (constraints.maxHeight * percentHeight) /
                                        30.0;

                                return Stack(children: [
                                  TransformHelper.translateAndScale(
                                      translateX: constraints.maxWidth *
                                          0.8757958471985094,
                                      translateY: constraints.maxHeight *
                                          0.04532842468610407,
                                      translateZ: 0,
                                      scaleX: scaleX,
                                      scaleY: scaleY,
                                      scaleZ: 1,
                                      child: GeneratedFavoritesButtonWidget2())
                                ]);
                              }),
                            ),
                            Positioned(
                              left: 17.0,
                              top: 101.0,
                              right: 17.7637939453125,
                              bottom: null,
                              width: null,
                              height: 56.0,
                              child: GeneratedStep1Widget(),
                            ),
                            Positioned(
                              left: 16.0,
                              top: 162.0,
                              right: 18.7637939453125,
                              bottom: null,
                              width: null,
                              height: 56.0,
                              child: GeneratedStep2Widget(),
                            ),
                            Positioned(
                              left: 17.0,
                              top: 223.0,
                              right: 17.7637939453125,
                              bottom: null,
                              width: null,
                              height: 56.0,
                              child: GeneratedStep3Widget(),
                            ),
                            Positioned(
                              left: 16.0,
                              top: 284.0,
                              right: 18.7637939453125,
                              bottom: null,
                              width: null,
                              height: 56.0,
                              child: GeneratedStep4Widget(),
                            ),
                            Positioned(
                              left: 16.0,
                              top: 345.0,
                              right: 18.7637939453125,
                              bottom: null,
                              width: null,
                              height: 56.0,
                              child: GeneratedStep7Widget1(),
                            ),
                            Positioned(
                              left: 16.0,
                              top: 467.0,
                              right: 18.7637939453125,
                              bottom: null,
                              width: null,
                              height: 56.0,
                              child: GeneratedStep9Widget1(),
                            ),
                            Positioned(
                              left: 16.0,
                              top: 406.0,
                              right: 18.7637939453125,
                              bottom: null,
                              width: null,
                              height: 56.0,
                              child: GeneratedStep8Widget1(),
                            ),
                            Positioned(
                              left: 16.0,
                              top: 528.0,
                              right: 18.7637939453125,
                              bottom: null,
                              width: null,
                              height: 56.0,
                              child: GeneratedStep5Widget1(),
                            )
                          ]),
                    ))
              ])),
        );
      }),
    ));
  }
}
